### ISSUE TITLE
Option to modify XLSForms

### ISSUE THREAD

**Issue by ivangayton** [hotosm/fmtm#10]
Campaign Managers often need to collect data specific to their project, context, client, or community. It's impossible to cover all eventual needs in a library of XLSForms. Therefore we will need to allow people to create or modify their own XLSForms to collect the data they need.

At the moment, it's quite straightforward to create a project with any XLSForm; as long as the form adheres to a specific structure:
- The `select_one_from_file` question _must_ be row 9 of the `survey` tab
- The `form_title` and `form_id` _must_ be row 2 (cell A2 and B2 respectively) of the `settings` tab

If the forms adhere to these constraints, the FMTM tools can already ingest them an link them to geography files for individual tasks. We just need a way to allow users to upload them. For example, when persuing the library of forms (see issue #9), the user should probably have the option to "Upload my own XLSForm", and ideally also download one of the forms from the library to modify and re-upload (with some checks to make sure the name and ID are appropriately changed).

**Comment by robsavoye** [comment]
Currently in main it this works. You can upload a custom XLSFile if you want. or use the XLSForm library if you want. A single ODK XML is generated from the XLSForm, and the output file is edited with these changes.
