### ISSUE TITLE
Add attribute task id to when the user downloads the task polygon in a project

### ISSUE THREAD

**Issue by susmina94** [hotosm/fmtm#1033]
**Describe the bug**
I downloaded the task polygons of a project, but the attribute table was empty.

**To Reproduce**

1. Go to Project
2. Click Tasks button

**Expected behavior**
I would want to have the task ids as an attribute column in the tasks geojson file that I download from the project.

**Screenshots**
![image](https://github.com/hotosm/fmtm/assets/108750444/1e3eda9a-9a0e-4f95-9e59-0f5844effd79)
![image](https://github.com/hotosm/fmtm/assets/108750444/74ef9cf2-15c3-4708-858e-883716d9a9a0)

**Comment by Sujanadh** [comment]
This issue is prior to janakpur project, and it is already done in fmtm. So, closing this issue now.
