### ISSUE TITLE
Analyse database structure for what is required or redundant

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1043]
**Is your feature request related to a problem? Please describe.**

- We have a lot of database tables and field, but use very few.
- The base schema was modified from Tasking Manager I believe.
- The public.projects table has a lot of fields in particular.

**Describe the solution you'd like**

- Assess the schema for what is needed and what can be removed.
- Tie this in with the user roles design #243.
- Simplify where possible and remove complexity.

**Comment by robsavoye** [comment]
The FMTM database schema was based on TM, changes made when needed. The new schema is implemented in the tm-admin project. Currently the work has been focused on improving the existing schema for TM. After some performance and API compliance testing using TM, then those improvements can be applied to the FMTM schema.

**Comment by spwoodcock** [comment]
Thanks for clarifying 😄 

As this is part of the planned roadmap anyway with tm-admin integration, I will close this issue in FMTM then.
