### ISSUE TITLE
Allow users to visualize data extracts while creating a project

### ISSUE THREAD

**Issue by susmina94** [hotosm/fmtm#1056]
**Is your feature request related to a problem? Please describe.**
I chose the option to Use OSM data extract but I can't validate if I wanted these data extracts on my project unless I complete the project creation process completely. Once the QR code is generated I can't edit these inputs.

**Describe the solution you'd like**
If I could view the data extracts right at the time I am creating a project I can validate them before creating a project.
It would help me validate if it's working for me or not.

I would like to have the map interface zoomed in full screen as well, so a full screen and collapse button on the map would be of great help.

**Additional context**
![image](https://github.com/hotosm/fmtm/assets/108750444/b499df7a-1bc9-4197-afbf-7fb2e7396193)

**Comment by spwoodcock** [comment]
![image](https://github.com/hotosm/fmtm/assets/78538841/ecdab96d-9b80-45dd-83f4-61cec22dc6fe)

this has been implemented.

The request for a fullscreen map is a separate issue 👍
