### ISSUE TITLE
Easier loading of mbtiles in ODK Collect

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1063]
**Is your feature request related to a problem? Please describe.**
When i need to add mbtiles for each task. It is very tedious that we have to download it manually, then go to specific place on your mobile and upload it there. then we can fetch it on odkcollect.

**Describe the solution you'd like**
A single button should be added which could facilitate automatic download of mbtiles of that task upon scanning the qr code.

**Comment by spwoodcock** [comment]
See https://forum.getodk.org/t/provide-a-way-to-get-mbtiles-to-collect-without-having-to-connect-to-a-computer/42206/41

**Comment by robsavoye** [comment]
There have been meetings with the ODK developers on this exact topic, and I believe we've agree to work on a solution. The idea is the QR code will load the XForm, the OSM data extract, and the mbtiles basemap at the same time. But yes, needing to use adb to load mbtiles is not efficient, especially for group mapping.

**Comment by spwoodcock** [comment]
Most of the development was complete by Nishon a while ago. 

ODK have taken over to finalise and refine. 

The feature should be available in a release or two. 

For now, we have improved support for offline maps directly in FMTM. Closing.
