### ISSUE TITLE
User Roles: Create user roles in backend for super admin and organization admin

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1066]
**Is your feature request related to a problem? Please describe.**
To kick start user permission on FMTM, the roles of super admin and organisational admin should be created. 
The credentials are provided for those roles by backend as per now. 

**Additional context**
The permissions are specified by the file below:
[https://docs.google.com/spreadsheets/d/1crWztvXvuewE8Zv-qxbv0t_-eYHUqSlrJQgeto8kmf4/edit#gid=1497569844](url)

**Comment by spwoodcock** [comment]
Added in https://github.com/hotosm/fmtm/pull/1094
