### ISSUE TITLE
Configure editable vector layers in OpenLayers map

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1081]
**Describe the bug**

- Any vector layer added to the map is editable by default.
- We need a way to toggle this in `VectorLayer.js`.
- Task areas are editable (as they should be), but so are data extracts (which should not be).

**To Reproduce**

- Create a new project with a data extract.
- The entire data extract is editable, adding lots of orange circles (draggable vertices).
- Editing is rendered useless by too much info on the map.

**Expected behavior**

- Only the project area and task areas are editable.
- Data extracts are not editable.

**Screenshots**

![image](https://github.com/hotosm/fmtm/assets/78538841/61b42730-d082-4031-be9b-6bd8f998de7f)

**Comment by varun2948** [comment]
oh the props got default added onto that will fix it thanks @spwoodcock for letting me know the bug
