### ISSUE TITLE
Limit size of project area during creation

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1084]
**Describe the bug**

- Any size project can be generated currently.

**To Reproduce**

- Draw a project area over the entire world during creation.

**Expected behavior**

- Prevent going to the next step if area is >1000km^2
- Give a warning if area if >100km^2
- The warning should also encompass the max data extract size: `80000 Sq.KM` (282.84km^2)
  - If a project is generated larger than this, a data extract can not be automatically generated (one must be uploaded instead).

**Comment by NSUWAL123** [comment]
@spwoodcock I am a bit confused about this: 
> The warning should also encompass the max data extract size: 80000 Sq.KM (282.84km^2)
> If a project is generated larger than this, a data extract can not be automatically generated (one must be uploaded instead).

Could you elaborate this point.

**Comment by spwoodcock** [comment]
I actually think the m2 limit (80000m2) defined in the raw data api error message is incorrect. The area would be huge.

I think the area should be about 283km2, which is a square of about 17km x 17km, enough to cover most cities in the world (probably not the entire metropolitan area of Tokyo 😂)

The proof will come from testing.

To assess geometry area in meters using openlayers, we need to.use the geodesic calculation from ol/sphere.

It will be something like.

```js
import {getArea} from 'ol/sphere';

const projectAreaMeters = getArea(polygonGeom, {projection: 'EPSG:4326'});

if (projectAreaMeters > 283) {
    # do stuff
};
```
