### ISSUE TITLE
invalid projection system on uploading geojson during project creation

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1087]
**Describe the bug**
On second step of project creation, the invalid msg appears saying the projection system is invalid. However on checking same file on GIS, it has WGS 84 projection system.  

**To Reproduce**

1. Go to create project step 2
2. Click on upload file and upload any geojson file
3. See error

**Expected behavior**
the projection system is accepted without any error msg and smooth creation of project.

**Screenshots**
![image](https://github.com/hotosm/fmtm/assets/97273021/c121fe82-f402-4fc6-8e80-85157c782098)

**Comment by spwoodcock** [comment]
Thanks @manjitapandey 
Could you also upload the geojson file here for testing?

**Comment by manjitapandey** [comment]
This is the geojson file I used.
[21011 jnkpur.zip](https://github.com/hotosm/fmtm/files/13871664/21011.jnkpur.zip)

**Comment by varun2948** [comment]
@NSUWAL123 if there is multidimentional array user `.flatten` function to flatten the array to single dimentional and check for the lat lon to be -90 to +90. which will help out to check the geojson for different geojson too

**Comment by varun2948** [comment]
@spwoodcock and if the bounds is between -90 and +90.... then validate it otherwise not allow it ?

**Comment by varun2948** [comment]
wouldn't it take more time to create a polygon by using whole AOI geojson instead of using the first index of geojson feature and flatten it to check one index only ?

**Comment by spwoodcock** [comment]
I guess it depends on if a multipolygon project area is common or not.

I suggested using ol as it outsources the geojson parsing, including error handling, to an existing lib. I can't imagine loading a simple AOI would be a slow process. Plus we have to load the geometry to display it anyway.

**Comment by varun2948** [comment]
hmm okay then let's stick to your suggestion...

**Comment by spwoodcock** [comment]
Just giving ideas - you are free to solve however you think is best 😉
