### ISSUE TITLE
Adding user feedback form

### ISSUE THREAD

**Issue by synneolsen** [hotosm/fmtm#11]
# Nobody likes getting negative feedback. But...

Our most unhappy users will be our greatest source of learning! (^o^)/ 

I am therefore suggesting to add a **rapid feedback function** very simple way for the field mappers to add their feedback directly in the tool we are creating. This can be done in various ways. I would be curious to hear what people are thinking here, but here is one very straight forward example:

## Score + free text:
This is a simple and overall score which would ask the field mapper how satisfied they are with the solution.

![Screenshot 2022-10-19 at 18 59 34](https://user-images.githubusercontent.com/107098623/196756516-efb6e056-35a7-41c5-ac8f-3e71fa53043b.png)

## 

## Some useful articles:

- [25 Tools for Website Feedback Button and How to Set It Up](https://medium.com/@usersnap/25-tools-for-website-feedback-button-and-how-to-set-it-up-6f732f5f214f)

- [Negative User Feedback? Handle it like Bill Gates!](https://medium.com/@userpilot/negative-user-feedback-handle-it-like-bill-gates-9ad392bbe143)

- [13 user feedback best practices for collecting in-app feedback](https://medium.com/@userpilot/13-user-feedback-best-practices-for-collecting-in-app-feedback-2038bd5e3e8)

**Comment by spwoodcock** [comment]
I love this idea. 

Currently we have a `Support` button that links to the GitHub repo issues. Fine for technical users.

![Screenshot_20231216-191743.png](https://github.com/hotosm/fmtm/assets/78538841/b518ea6e-fd63-4bfe-ab48-9064c3db6213)

I imagine most users of FMTM eventually would like a feedback form outside of making a GitHub issue, and I think a basic version of this would be trivial to implement. 

@varun2948 what do you think if we have an additional menu link `Feedback` with a page containing a simple form at the top (it doesn't have to be pretty):
- a text box for users to write free text
- a submit button
(The user must be logged in, as the username is sent too)

Then all we need is an endpoint to POST to and a database table `public.feedback` with fields `username` and `comment`.

On the page below the form, we just list the username and comments, almost like blog posts.

**Comment by robsavoye** [comment]
I'm a huge fan of end user feedback, but this has a tendency to generate so much junk it gets ignored. This also wouldn't work with people self hosting FMTM. To really get feedback it'd need to create a github issue anyway, or send an email to a developers list. I believe the issue entry form in github can be customized. Petya had added an actual bug category, it might be worth seeing if that can be further customized to be simpler.

Also an FMTM mapper is probably not going to be submitting any feedback, once they have their QR code, they have nothing to do with the website. So this is really just for the project manager, who I am going to assume is at least somewhat technical.
