### ISSUE TITLE
Convert markdown inline links to reference style links

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1100]
### Problem

We use the inline style of markdown links for all `.md` files:
`[link here](https://website.com/some/link)`

This creates linting errors due to line length, and is also not the preferred approach with markdown.

### Solution

Use reference style links in all markdown files:
```
[link here][1]

... end of file
[1]: https://website.com/some/link
```

The reference is not limited by line length.

### Task

Update all `.md` files under `docs` to use references for **links** and **images**.

An example of the correct format can be found here: https://github.com/hotosm/fmtm/blob/development/docs/index.md

### Related Tasks

A smaller chunk of #921

**Comment by cordovez** [comment]
Hi all,
I would like to have a crack at this if you still need it done.

**Comment by spwoodcock** [comment]
Hi @cordovez !

It would be a huge help if you could - thanks so much 🙏
