### ISSUE TITLE
Extract generated is not respective of geometry selected.

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1115]
**Describe the bug**
The extract generated is not respective of geometry selected.

**To Reproduce**

1. Go to Create project
2. Click on use osm data extract and any geometry (polygon lets say)
3. See error(both line and polygons are seen in all cases )

**Expected behavior**
only the custom extract of selected geometry data should be generated.

**Screenshots**
![image](https://github.com/hotosm/fmtm/assets/97273021/a9d518f3-2898-427d-9b7a-dfebd245aad3)

**Comment by spwoodcock** [comment]
As part of this, we need to use osm-rawdata for the extract generation and filtering.

raw-data-api was used directly for the flatgeobuf prototype, but should be replaced (once we can set `bind_zip=True` in osm-rawdata).

**Comment by spwoodcock** [comment]
This was completed with the recent refactoring of data extract generation. 

I don't think the selection of data extract type is required now, as the extract filter options are determined from the form category (data model in osm fieldwork). 

There is also logic in the backend to automatically determine the geometry type for custom extracts. 

Data extracts can also be multilple geometry types, but this logic just determines the predominant type.
