### ISSUE TITLE
Issues concerned with drawing of project Boundary

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1147]
**Describe the bug**

- [x] User can draw multiple times without clicking on reset button.
- [ ]  User can draw although they select upload file option. 

**To Reproduce**

1. Go to 'create project step 2"
2. Click on 'draw
3. See error 

**Screenshots**

![image](https://github.com/hotosm/fmtm/assets/97273021/803e4bd3-130e-408b-99ba-c15d77c3d026)

https://vimeo.com/907806718/c256b44cf8?share=copy

**Comment by spwoodcock** [comment]
- Issue 2 should be solved by disabling editing when the file upload radio is checked.
- Issue 1 is actually an issue of documentation: to finalise a geometry you must double click the map area. Once you do that, the old geometry disappears.
