### ISSUE TITLE
How to handle features that have not been digitised

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1152]
**Is your feature request related to a problem? Please describe.**

- If a mapper in the field encounters a feature that has not been digitised, what do we do?

**Describe the solution you'd like**

- To be discussed.

**Comment by nrjadkry** [comment]
We will have a geopoint select form field on the form for those people who want to add a point field on that specific place.

**Comment by spwoodcock** [comment]
This will be solved by fAIr & TM integration.
