### ISSUE TITLE
Generate data extract fails during project creation

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1156]
**Describe the bug**
The generate data extract fails showing 404 error on console panel. 

**To Reproduce**

1. Go to 'create project step 4'
2. Click on 'generate data extract
3. See error

**Expected behavior**
data extract visible on map section.

**Screenshots**
![image](https://github.com/hotosm/fmtm/assets/97273021/34fb1ca3-22d4-4f1a-9abb-caf92827ab38)

**Comment by spwoodcock** [comment]
Thanks @manjitapandey, I will look into this.
I think the raw-data-api response format might have changed.
