### ISSUE TITLE
Notification to users when QR code generation is completed

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1164]
**Is your feature request related to a problem? Please describe.**
I'm always confused to check whether the QR code of the project I created has been completed or not. And I end up checking many times if QR of the task is completed.

**Describe the solution you'd like**
A Notification icon on title bar of explore project page. Users will be notified when the project creation is completed saying "The project you created/ project name has been completed. check it out"

**Describe alternatives you've considered**
There could be other alternatives too but goal is to notify user the project creation is completed.

**Comment by spwoodcock** [comment]
Project creation speed has been improved with Entities.

No longer an issue. Closing.
