### ISSUE TITLE
Custom data extracts are not passed through during project creation

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1172]
**Describe the bug**
The custom data is not visible on map step 4 of project creation.  No API is called for loading custom data extracts. 

**To Reproduce**

1. Go to create project step 4
2. Upload custom data extracts
3. See error

**Expected behavior**
custom data extract to be visible on map 

**Screenshots**
![image](https://github.com/hotosm/fmtm/assets/97273021/6bb7b684-62d3-422e-923b-f41e50649266)

**Comment by spwoodcock** [comment]
Is the geojson valid? Perhaps it threw an error silently.

I just uploaded a custom data extract:
![image](https://github.com/hotosm/fmtm/assets/78538841/334a2911-3a3a-4f5b-aaf0-fa11c520f681)

Related https://github.com/hotosm/fmtm/issues/1145 (uploading flatgeobuf doesn't work properly, but geojson should)

**Comment by spwoodcock** [comment]
The bbox
[kathmandu.txt](https://github.com/hotosm/fmtm/files/14179832/kathmandu.txt)

The extract
[kathmandu_extract.txt](https://github.com/hotosm/fmtm/files/14179833/kathmandu_extract.txt)

They are txt file, as geojson is not supported by github.

**Comment by spwoodcock** [comment]
Two aspects need to be looked into:
- Check that the data extract correctly displays on the split-tasks page, and if not display an adequate error.
- Ensure the data extract is passed through to the project during creation. Currently raw-data-api is used to generate the extract every time (the custom data extract is ignored).

**Comment by spwoodcock** [comment]
Oops accidentally deleted my previous comment.

So data extracts are not getting passed through to the `generate` stage correctly - only a `false` value gets passed:

![image](https://github.com/hotosm/fmtm/assets/78538841/9f642af8-fd52-44c4-9e7b-f2241fce64ad)


Two things to investigate:
- Are the geojson extracts correctly loading on the split-tasks stage? Is there adequate error handling here if the geojson is not valid?
- Why the geojson is not passed to the `generate` endpoint, but instead a boolean value is.
