### ISSUE TITLE
Unable to upload clipping boundary downloaded from export tool

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1175]
**Describe the bug**
I am unable to upload boundary geojson downloaded from export tool or Tasking manager

**To Reproduce**

1. Go to export tool and download a file in geojson format.
2. Go to FMTM create project 
3. upload clipping boundary downloaded from Export tool

**Expected behavior**
The boundary downloaded from one HOT tool should be able to be uploaded on other HOT tool.

**Screenshots**
![image](https://github.com/hotosm/fmtm/assets/97273021/ef0faec1-7580-45fe-b4bc-a85e77b4364a)

**Comment by spwoodcock** [comment]
Great catch - could you upload the sample geojson for testing? 😄

**Comment by manjitapandey** [comment]
[FMTM_data_extract_geojson_uid_db153b3d-5429-44a0-aa6e-d89159a62cf0.zip](https://github.com/hotosm/fmtm/files/14193372/FMTM_data_extract_geojson_uid_db153b3d-5429-44a0-aa6e-d89159a62cf0.zip)

this is the geojson I downloaded from Export tool
