### ISSUE TITLE
Task splitting algorithm fails to split tasks when custom data extracts uploaded

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1176]
**Describe the bug**
Task splitting algorithm fails to split tasks. The API shows 200 but response shows null in the features. This can be reproduced by choosing custom data extracts. 

**To Reproduce**

1. Go to create project 
2. Click on Upload custom data extracts
3. select Task splitting algorithm

**Expected behavior**
Smooth task splitting and project creation

**Screenshots**
![image](https://github.com/hotosm/fmtm/assets/97273021/0f1f80db-1722-4c86-8628-270d4f47f837)

**Comment by manjitapandey** [comment]
Related: https://github.com/hotosm/fmtm/issues/1172

**Comment by spwoodcock** [comment]
We have point 3 covered - I wrote quite a few tests for fmtm-splitter 😄 

You can run them with:
```python
docker compose run --rm splitter pytest
```

With this in mind, I just wrote a very quick guide to testing updates to fmtm-splitter visually: https://hotosm.github.io/fmtm-splitter/testing-visually/
Hopefully it helps debugging @ivangayton
