### ISSUE TITLE
Task splitting algorithm fails to split tasks when osm data extracts is selected

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1177]
**Describe the bug**
The tasks splitting algorithm fails if default osm data extract is selected. 500 internal server error is shown on network panel. 

**To Reproduce**

1. Go to create project step 4
2. Select osm data extract option
3. select Task splitting algorithm

**Expected behavior**
Smooth task splitting and project creatiion

**Screenshots**
![image](https://github.com/hotosm/fmtm/assets/97273021/92cf7721-2c40-4ded-b1aa-e1aa3c09db1b)

**Comment by manjitapandey** [comment]
I get error on selecting upload custom boundary and default osm data extracts.

![image](https://github.com/hotosm/fmtm/assets/97273021/826d41a0-dd42-4918-aeaa-92cf269e3f8a)

**Comment by spwoodcock** [comment]
This may be because the data doesn't exist in raw-data-api yet (I could be wrong).

Where in the world is the area?

**Comment by spwoodcock** [comment]
Ah looks like Nepal, so nevermind!

**Comment by manjitapandey** [comment]
Hello, @spwoodcock , Have you got some initial findings about this issue? I am unable to create project, causing this issue to be somewhat urgent.

**Comment by spwoodcock** [comment]
Hi @manjitapandey , thanks for the prompt! I'm working on these data extract issues currently. 

The data extract flow needed a significant overhaul, as it is currently generating extracts twice, not filtering, and not storing the final extract properly.

The work involves some updates to osm-rawdata too. I will make a PR for FMTM today that fixes it.

**Comment by manjitapandey** [comment]
I still encountered the issue of 500 on both splitting using splitting algorithm and dividing on square. 
![image](https://github.com/hotosm/fmtm/assets/97273021/58177d61-0a89-4656-98d7-4728ad73b114)

**Comment by manjitapandey** [comment]
This is the file I used as AOI.
[20.zip](https://github.com/hotosm/fmtm/files/14237595/20.zip)
