### ISSUE TITLE
QR code doesn't contain any forms on scanning

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1188]
**Describe the bug**
On scanning the QR code, no form is available and shows "nothing available for display". 

**To Reproduce**

1. Go to 'any project's detail page.
2. Scan QR for any tasks
3. click on start new form

**Expected behavior**
the series of qns of the form should be seen on the odk

**Screenshots**
![Screenshot_2024-02-12-11-12-46-60_171725cd2e369f62c287134214eaed67](https://github.com/hotosm/fmtm/assets/97273021/70c11515-e186-428a-92c5-8114463ab479)

**Additional Information**
You can still download template form from download form section of odk. get the selected form and start filling the form.

**Comment by spwoodcock** [comment]
Please test again in 5 minutes now #1183 is merged 🙏

**Comment by manjitapandey** [comment]
@spwoodcock , Now QR generation fails during project creation.
![image](https://github.com/hotosm/fmtm/assets/97273021/817c70d8-bb0b-4ec9-b107-ea43ec356101)
