### ISSUE TITLE
Unable to extract osm data during project creation

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1193]
**Describe the bug**
I get FGB error on trying to extract osm data. It shows 307 and 404 error on get data extract api.

**To Reproduce**

1. Go to 'create project
2. Click on 'osm data extract
3. Click on generate data extracts

**Expected behavior**
The osm data extracts should be visible on the map. 

**Screenshots**
![image](https://github.com/hotosm/fmtm/assets/97273021/c4a3cf95-e638-4a7c-a290-8d701f5e02d8)

**Additional context**
This issue is reproducible if you Upload AOI or draw your own API.

**Comment by manjitapandey** [comment]
Sorry, I was able to solve this issue through hard refreshing of the page.

**Comment by spwoodcock** [comment]
Creation relies on an external API, so there is potential for it to fail sometimes.

It looks like an error was displayed to the user.

As long as they can click the button and try again, this is fine.
