### ISSUE TITLE
Run Frontend Independently without docker using staging server URL/API

### ISSUE THREAD

**Issue by varun2948** [hotosm/fmtm#1196]
**Is your feature request related to a problem? Please describe.**
Rightnow if anyone wants to contribute just on the frontend side, they can't be able to do so as they need to setup docker and run docker with frontend service and api service.

**Describe the solution you'd like**
Implement build tools configuration and setup an ENV to make it accessible without docker setup just like TM works.

**Additional context**
Lookover on the vite config and env config

**Comment by spwoodcock** [comment]
For now it would be very difficult to implement this:
- It would mean setting a CORS origin policy to `*` for the staging server, which isn't great security.
- We couldn't configure OSM login to work properly, as we need to specify `OSM_LOGIN_REDIRECT_URI` to `127.0.0.1` on the staging server to work with a local frontend.
- The OSM OAuth2 app would also need the redirect URI set to localhost for staging (that's possible).

Docker is the recommended way to set up the dev env.
Using the `Justfile` makes it even easier.
Hopefully this isn't a major barrier.

We may re-visit this if it is a blocker for any contribution in the future.

**Comment by royallsilwallz** [comment]
Hey @spwoodcock, the points you mentioned have already been resolved in Tasking Manager.
I think it is way easier for a frontend developer if they are able to code without having to setup docker.
They can just do npm install, make changes, and push the code.
So, I think we should prioritize this sooner or later.

**Comment by spwoodcock** [comment]
I'm open to ideas, although do still believe it's not much hassle to simply run:
`docker compose up -d ui --build`

By 'already implemented' I would be interested in hear what has been done on TM without impacting security 😄 
We could enable OSM login to work work from staging --> localhost, but this would reduce security and open up the OSM token to be stolen (granted it is low risk - OSM isn't exactly a crypto exchange).

More than happy to discuss this further 👍
