### ISSUE TITLE
Mapper role integration - frontend

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1198]
**Is your feature request related to a problem? Please describe.**
Mappers role should be implemented in the frontend. 

Please follow the following sheet if features are visible or not for mapper level user.
https://docs.google.com/spreadsheets/d/1crWztvXvuewE8Zv-qxbv0t_-eYHUqSlrJQgeto8kmf4/edit?pli=1#gid=1497569844 

**Additional context**
The backend work for mapper role has been completed.

**Comment by spwoodcock** [comment]
Examples of things that a mapper can't do:
- Create projects
- Access organisation management

Potentially we can restrict buttons if the user only has mapper role.

**Comment by manjitapandey** [comment]
with the mapper's mobile page, the user roles needs to be slightly modified. Now, every user who uses mapper's mobile UI is a mapper which removes the complexity of mapper's role. Let's say we have already implemented mapper's role in frontend too. Hence, this is now unrelevant, I would say.
