### ISSUE TITLE
unable to edit project description

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1201]
**Describe the bug**
The recent api doesn't match with UI update. I am unable to update project description and get 400 error on network panel.

**To Reproduce**

1. Go to 'edit project
2. edit project description
3. save the changes

**Expected behavior**
Changed fields should be updated smoothly without any error

**Screenshots**
![image](https://github.com/hotosm/fmtm/assets/97273021/c1912e90-7557-4c33-a066-00319ba53815)

**Comment by Sujanadh** [comment]
I think issue is related to access token.
