### ISSUE TITLE
Addition of instruction field during project creation

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1213]
**Is your feature request related to a problem? Please describe.**
the mapping projects are used by different levels of mapper, some may be completely unaware of how to map on the filed. Or some project manager want to add instructions on how to map on field which may vary from project to project. 

**Describe the solution you'd like**
The addition of instructions field during project creation may be a nice feature to have. 

**Additional context**
open to discussion and welcome to all the suggestions and alternatives. 
@spwoodcock

**Comment by spwoodcock** [comment]
Do you think we should have instructions as text, perhaps markdown format or similar?

Or we should allow the manager to upload a document containing instructions?

Both are easy to implement technically

**Comment by manjitapandey** [comment]
Depends on how long the instruction could be. As Far as i know, we can have user add instruction as text, but can also upload necessary images or document's link if necessary. 
Markdown format would be cherry on the top. 
Shall we go with that?

**Comment by spwoodcock** [comment]
1

We have an instructions field for projects we could use for this.

We store the text in the database, so the user could write in markdown format if they like.

To display it properly we just need a markdown renderer - something simple like snarkdown would do.

2

For uploading an instructions file and storing the URL we would need another database field. 
So maybe best to leave this for now until needed.
