### ISSUE TITLE
handling of info messages on frontend

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1216]
**Describe the bug**
The message during task updates are said as "task has been updated to 1". This doesn't convey proper information to users.
also when user try to click update button without updating form. It also should show the message like "No change to update"

**To Reproduce**

1. Go to 'project page'
2. Click on 'any task to map '
3. See error

**Expected behavior**
The message like "Task id updated to locked for mapping". 

**Screenshots**
![image](https://github.com/hotosm/fmtm/assets/97273021/6e501ad1-2163-4a60-b9d7-8a5fd08254bd)

**Comment by spwoodcock** [comment]
The frontend needs reverse enums for TaskStatus, converting the numbers into string values
