### ISSUE TITLE
Validation Pop- up to approve or reject submissions

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1238]
**Is your feature request related to a problem? Please describe.**
I am unable to validate the submission for now

**Describe the solution you'd like**
I should be able to review the submissions and approve or reject submissions. Also, i should be able to comment on the submissions. 
The design for validation pop-up is similar to odk submission validation pop-up.

![image](https://github.com/hotosm/fmtm/assets/97273021/f855098e-8363-47f0-b2f3-991a753f5f0b)

**Additional context**

- [ ] The action column on submission table should freeze on right of the table. 
- [ ] The delete option of submission table should be removed since we can't directly remove submissions from FMTM. User should do it from ODK,

**Comment by NSUWAL123** [comment]
Frontend api integration is remaining

**Comment by Sujanadh** [comment]
@NSUWAL123  review state pop up is not seen.
