### ISSUE TITLE
Issues on QR pop up

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1243]
**Describe the bug**

- [x] The download icon and view submission icon should be removed from start mapping QR pop-up.
![image](https://github.com/hotosm/fmtm/assets/97273021/cb7b44b3-fe7d-4d8c-ad49-2168e460cd2f)

- [ ] The download icon and view submission icon should have tool tips as in design.

- [x] The download QR icon should be functional. 
![image](https://github.com/hotosm/fmtm/assets/97273021/7e67b35a-6e34-4925-ae18-4a93feaaf93b)

- [ ] The respective icons should lead to respective pop-up or page. 

The download icon should be linked with download mb tiles pop- up 
the view task submission icon should redirect to task submission page.

**To Reproduce**

1. Go to 'project page
2. Click on 'select Tasks to start mapping
3. See error

**Comment by spwoodcock** [comment]
Same issue for me - the QR code is either not generated from the `odk_token` or not displayed properly

**Comment by spwoodcock** [comment]
I think the download icon should remain, in case the user wants to download the QR code and distribute it (e.g. via whatsapp)
