### ISSUE TITLE
Remove organisations/unapproved endpoints

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1254]
**Describe the bug**

- We have two GET endpoints `/organisations/unapproved/` and `/organisations/unapproved/{org_id}` that I don't think are necessary.

**Expected behavior**

- They should be removed in favour of the `/organisations/` endpoint, which filters approved/unapproved based on admin access.
  (https://github.com/hotosm/fmtm/pull/1253)
- Requires coordination with the frontend to remove references to these endpoints.
- The DELETE `/unapproved` endpoint is required, due to different role access level.

**Comment by Sujanadh** [comment]
What about returning a requested organisation by the user in my organisation even though it is not approved?

**Comment by Sujanadh** [comment]
So, we don't need an unapproved organisation tab? since it was only made for the super admin so that he could approve or unapprove them. What do you think? Do we allow an admin to approve or reject an organization request via mail or api docs?

**Comment by spwoodcock** [comment]
We don't end a separate endpoint to list only unapproved orgs, as the organization endpoint lists both approved and unapproved (if the user is admin). They are stored in a variable in the frontend, so it's easy to split them as needed.

**Comment by Sujanadh** [comment]
> What about returning a requested organisation by the user in my organisation even though it is not approved?

what about this?

**Comment by spwoodcock** [comment]
I'm not sure if any user other than admin should be able to see unapproved orgs.

Unapproved orgs are returned by default if the user is an admin.

Perhaps I'm missing a use case here, so feel free to correct me 👍

**Comment by Sujanadh** [comment]
The use case is to let the user know that the organisation is not approved yet and to review the details in case the superuser requests some changes or something, which might be a future case. Since it is not a priority for now, we can just let the role do all the work.

**Comment by spwoodcock** [comment]
Ah ok that makes sense 👍

We should probably only remove the endpoint that gets all unapproved orgs then, as that is duplicated.

The endpoint that gets a specific unapproved org can be used for the feature you mentioned
