### ISSUE TITLE
Custom data extract may cause task splitting to fail

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1263]
**This is not a high priority item, but something to consider for the future. Custom extracts need to work well, but the majority of users will generate the extract.**

## The Issue

During project creation we have two uses for the data extract:

1. As the geoms that are passed to ODK Collect for mapping.
2. As the geoms used for task splitting. 

#### Case 1: generate extract

If the user generates a data extract, this is used for (1).

Then for task splitting another extract is generated containing buildings, rivers, roads, airstrips, railways, only for the purpose of splitting.

#### Case 2: custom extract upload

If the user uploads a custom extract this is used for both (1) and (2).

The issue here is that the user only wants to map buildings, so the extract does not contain any lines.

Task splitting would fail.

#### Option 1: enforce data extract format

We could enforce uploading a data extract in a standardised format, always containing polylines.

I am not against this approach as it would make our lives easier and prevent issues from edge cases.

For example we could point users to [Export Tool](https://export.hotosm.org)

#### Option 2: configuration for task splitting

On the task splitting page, if the user selects the task splitting option we can add extra config options.

If a data extract was uploaded in the previous stage we can ask the user if they wish to use this extract for task splitting (giving a warning that it needs to contain polylines), or we can give the option to generate a new extract for splitting. 

Input / opinions welcomed @susmina94 @manjitapandey

**Comment by manjitapandey** [comment]
Have started discussion regarding this issue:
https://github.com/hotosm/fmtm/discussions/1405

**Comment by manjitapandey** [comment]
For now, we extract the linestring from OSM in case user upload custom map features. Further tasks canbe done through interactive task splitting. So closing this issue for now.
