### ISSUE TITLE
Project Instructions and task details

### ISSUE THREAD

**Issue by Mudi-business** [hotosm/fmtm#127]
**Is your feature request related to a problem? Please describe.**
Project Instructions are not currently being returned in a response from projects API endpoints

**Describe the solution you'd like**
According to Figma design , there should be Instructions dropdown which  will Instruct the user on a particular project , those Instruction are not currently being returned in a project.

**Describe alternatives you've considered**

**Additional context**

**Comment by spwoodcock** [comment]
Could you please clarify what is missing from the response?

I have tested with: https://fmtm-api.hotosm.org/docs#/projects/read_project_projects__project_id__get

The response includes the **project_info.instructions** key:
```
  "project_info": [
    {
      ...
      "instructions": "do stuff",
      "per_task_instructions": "map the things"
    }
  ],
```

Each task is also listed, with all of the task keys, including task status.

**Comment by spwoodcock** [comment]
Closing, as this is implemented as far as I can see.

**Comment by Mudi-business** [comment]
Yes you can close this one , I didn't  see the Instruction at first
