### ISSUE TITLE
Task creation status does not update

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1273]
**Describe the bug**

The task status does not update while the backend is processing task files / ODK token etc:

![image](https://github.com/hotosm/fmtm/assets/78538841/10cc734e-8d90-46e2-8deb-99b73fd5b0f5)

The screenshots shows the task about 50/74 complete, but the progress bar is not updated.

**To Reproduce**

- Create a project with a lot of tasks, e.g. 50+.

**Expected behavior**

- The progress bar updates to give an indication for how long the process will take.

** Device(please complete the following information):**

- OS: Windows
- Browser: Firefox

**Comment by manjitapandey** [comment]
Seems the progress is shown 0 from backend 
![image](https://github.com/hotosm/fmtm/assets/97273021/e77aea20-3077-4042-8203-8436351a4b88)
Can be backend issue.

**Comment by spwoodcock** [comment]
Fixed this 👍

However, it's not perfect as the project creation can overwhelm the backend resources a bit.
This means the server takes time to respond to requests, or responds in batches between the project creation steps.

1. I will decrease the polling interval from 2 seconds to 5 seconds to help with this.
2. This will not be an issue if we use a task queue and websockets in future.
    https://github.com/hotosm/fmtm/issues/1124
    https://github.com/hotosm/fmtm/issues/1048
