### ISSUE TITLE
Some data models for osm data extracts do not work

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1275]
**Describe the bug**
I get error generating data extract when trying to generate data extracts for few form categories like camping and anemities. Is it because we don't have the feature within my AOI? I still get 200 error on network panel.

**To Reproduce**

1. Go to 'create projects
2. Click on 'camping as category'
3. generate osm data extracts

**Expected behavior**
If its becoz we don't have any feature, we should be adding proper error msg saying something like No such features on your AOI 

**Screenshots**
![image](https://github.com/hotosm/fmtm/assets/97273021/f7185a39-3be6-44f1-ae2e-e6decc5fc4d1)

**Comment by NSUWAL123** [comment]
@manjitapandey, have you seen the network tab to see the actual reason of the error or if any error response has been sent from the backend??

**Comment by NSUWAL123** [comment]
The generate-data-extract api is returning an object of errors in reponse status code of 200 due to which it is showing that error.
![image](https://github.com/hotosm/fmtm/assets/81785002/6b336bf2-c5b3-415c-a14a-355c13d3fd10)

**Comment by spwoodcock** [comment]
As discussed, we can solve this by removing the types that fail for now. 

They can be debugged and fixed in osm-fieldwork. 

We should probably make an issue in that repo.

**Comment by manjitapandey** [comment]
This also may need error handling on FMTM in case there is no feature of that category on that project's AOI.

**Comment by spwoodcock** [comment]
I think the data extract would be an empty FeatureCollection in this case, so

```js
if (geojson.features.length === 0) {
    showError()
}
```
