### ISSUE TITLE
Data extracts not updated after AOI is edited

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1276]
**Describe the bug**
Once i created the AOI during project creation and generate data extracts. When i go back and reset or edit original AOI, the data extracts doesn't erased and when i go to data extract page to generate updated data extracts. The generate data extract button is disabled and already existing extracts are seen on map.

**To Reproduce**

1. Go to 'project creation and generate data extract'
2. Come back to upload area page and edit AOI
3. Go to generate extract page again

**Expected behavior**
The generate data extract button should be enabled and extracts of original AOI should be updated.

**Comment by spwoodcock** [comment]
The data extracts are reset when a new category is set in the dropdown. 

The logic should also catch when the user uploads a new AOI geojson - good catch!
