### ISSUE TITLE
Unable to see form questions on odk mobile

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1277]
**Describe the bug**
when i scan the QR for any task, I am unable to view any forms and says `No blank forms`. when i download the form  and start new form i again get the error msg. 

**To Reproduce**

1. Go to 'project page'
2. Scan Qr code for any tasks
3. See error

**Expected behavior**
The form should appear and user should be able to fill new forms.

**Screenshots**
![Screenshot_2024-02-26-10-11-45-85_171725cd2e369f62c287134214eaed67](https://github.com/hotosm/fmtm/assets/97273021/ef1cd031-ca3b-4d2e-b11d-c030bf426a75)

![Screenshot_2024-02-26-11-35-23-20_171725cd2e369f62c287134214eaed67](https://github.com/hotosm/fmtm/assets/97273021/e5cb8030-e26d-4725-97dd-652838766535)

**Comment by spwoodcock** [comment]
Is this on staging? Looking into it

**Comment by spwoodcock** [comment]
Fixed - it was an issue not having the domain set on ODK Central server (required to generate form download URL).

**Comment by manjitapandey** [comment]
Reopening this issue since I am again unable to see questions form on odk.

**Comment by spwoodcock** [comment]
Working on this in #1449 👍
