### ISSUE TITLE
Add endpoint for updating task history

### ISSUE THREAD

**Issue by Mudi-business** [hotosm/fmtm#128]
### OLD DESCRIPTION

**Is your feature request related to a problem? Please describe.**
 Comments needs to be implemented in the backend

**Describe the solution you'd like**
Currently the frontend is waiting for this feature to be implemented in the backend.

**Describe alternatives you've considered**

**Additional context**

### NEW DESCRIPTION

See comment: https://github.com/hotosm/fmtm/issues/128#issuecomment-1858926743

**Comment by spwoodcock** [comment]
Where do you want comments to be included?

Currently tasks return:
{
   "id":1,
   "project_id":1,
   "project_task_index":1,
   "project_task_name":"0001",
   "outline_geojson":{GEOJSON},
   "outline_centroid":{GEOJSON},
   "task_status":0,
   "locked_by_uid":null,
   "locked_by_username":null,
   "task_history":[HISTORY],
   "task_status_str":"READY"
}

projects return:
{
   "id":1,
   "odkid":1,
   "author":{
      "username":"admin",
      "id":1
   },
   "default_locale":"en",
   "project_info":[
      {
         "locale":"en",
         "name":"SUZA",
         "short_description":"SUZA project",
         "description":"This is a long description",
         "instructions":"go go go",
         "per_task_instructions":"map the things"
      }
   ],
   "status":2,
   "location_str":"Zanzibar, Tanzania",
   "outline_geojson":{
      "GEOJSON"
   },
   "project_tasks":[
      "TASKS"
   ]
}

Do projects, tasks, or both require comments?

**Comment by Mudi-business** [comment]
Comments are needed in Tasks part referring to Figma design
https://www.figma.com/file/C1fKGnYiTdsTTxrRSobE11/HOT-FMTM?node-id=0%3A1&t=KVW0qFqiBm8MH19t-0

**Comment by Mudi-business** [comment]
I think you need a separate Controller for that it's a full CRUD

**Comment by Mudi-business** [comment]
User should create comment based on Task selected , update comment ,delete
comment , you can discuss it more with Rob and Ivan if it's still needed
I'm just referring to Figma

**Comment by robsavoye** [comment]
Unlike the Tasking Manager, FMTM mappers will never see the webpage, so I'm not really sure this is necessary. I think the Figma design was roughly based on the existing Tasking Manager, but FMTM works quite differently.

**Comment by robsavoye** [comment]
After thinking about it, letting a mapper add comments is probably a good idea. They may be things like the XForm is confusing, the basemap is poor quality, or the weather is so bad they can't finish. I'm going to rename this issue to be more clear.

**Comment by spwoodcock** [comment]
There is the field `public.task_history.action` which should be set to enum value `COMMENT` (from taskaction enum) and field `public.task_history.action_text` which can include the comment.

We can keep this structure which includes action options

```sql
CREATE TYPE public.taskaction AS ENUM (
    'RELEASED_FOR_MAPPING',
    'LOCKED_FOR_MAPPING',
    'MARKED_MAPPED',
    'LOCKED_FOR_VALIDATION',
    'VALIDATED',
    'MARKED_INVALID',
    'MARKED_BAD',
    'SPLIT_NEEDED',
    'RECREATED',
    'COMMENT'
);
```

So this task does not require a specific endpoint per se, just an endpoint for updating the task history, which we should definitely work on.
