### ISSUE TITLE
Frontend login state is sometimes incorrect

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1289]
**Describe the bug**

- Calling `/me` sets the users login cookie.
- It also sets the frontend store login details.

Two scenarios could put these out of sync:
- The cookie expires, but the frontend state has not been cleared (i.e. because the logout endpoint was not called).
- The user was logged in, but the server had an update. The cookie is invalidated, but the login state persists (uncertain about this one, as in theory the cookie value should always be the same).

This would mean the user is not blocked on the frontend to e.g. create a project, but when they call the API they will get an error because they are not logged in.

**To Reproduce**

- Log in via FMTM, delete your cookie manually, attempt project creation.

or

- Log in via FMTM on dev, wait for a server update (quite regular), attempt project creation after.

**Expected behavior**

- We need a quick and simple way to check the login state for a user when they refresh or enter the FMTM website.
- If the loginSlice store contains user details, but the user is in fact no logged in, then the values in loginSlice should be cleared.
- In theory any endpoint with a simple `login_required` on the backend would work for this, but to reduce server load it would be best to create a new minimal endpoint: `/auth/introspect`.
- This endpoint should be called by the frontend at certain points, either:
  - At first page load.
  - Or on specific functions (harder to maintain, but lower load). E.g. at the start of project creation.

@manjitapandey

**Comment by manjitapandey** [comment]
@spwoodcock , Is it working fine? Are we good to close this issue for now. I am unable to replicate it now.

**Comment by spwoodcock** [comment]
I think we probably need an endpoint that can be used to renew the login cookie on first page load.

Else if auth fails when doing this then start the login flow again to regenerate the login cookie.

**Comment by spwoodcock** [comment]
/auth/me is called when the user logs in, but if they logged in 3 days ago and the cookie doesn't work for some reason, we need a way to test this and ensure they are logged in

**Comment by spwoodcock** [comment]
Reopening, as this isn't fixed. Only the backend part is.

**Comment by spwoodcock** [comment]
@manjitapandey I planned to look at this today, but didn't get time.

There is an endpoint that Sujan made `/auth/introspect`.
It simply returns the current logged in user.

**Success**:

```json
{
  "id": 12455,
  "username": "xxxx",
  "img_url": "https://www.openstreetmap.org/rails/active_storage/representations/redirect/xxx.jpg",
  "role": 0
}
```

**Fail** (both HTTP 401)

No cookie / token = 401:

```json
{
  "detail": "No access token provided"
}

Invalid cookie / token = 401:

```json
{
  "detail": "Access token not valid"
}
```

## TODO on the frontend
- Call this endpoint on first page load.
- If 401 is returned, then clear the loginSlice user details (i.e. log the user out on the frontend).
- This will prevent mismatch between backend and frontend login state.
