### ISSUE TITLE
Add documentation for React frontend

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#129]
Currently the React frontend is undocumented.

We should describe:

- The Microfrontend configuration.
- How to set up the development environment.
- How to contribute to the frontend.
- How it is deployed in production.

Pages should be added to the /docs directory via PR. They will be automatically published on the Wiki via CI.

Related to #84

**Comment by mohammadareeb95** [comment]
Hey! @spwoodcock 
Can I start to work towards submitting a PR to this issue?

**Comment by spwoodcock** [comment]
Of course! Thank you so much @mohammadareeb95 😄 

The currently Wiki only really references the backend, so it seems logical to rename: https://github.com/hotosm/fmtm/wiki/DEV-2.-Deployment --> `DEV-2.-Backend Deployment` first.

Then I think we should have a frontend page next: `DEV-3.-Frontend Deployment` & rename the subsequent pages too.

I will do the rename quickly now, then you can get started on the Frontend page whenever works best!

**Comment by spwoodcock** [comment]
Main should have the edits I mentioned now:
- Frontend wiki page: https://github.com/hotosm/fmtm/wiki/DEV-3.-Frontend
- The docs file to edit: https://github.com/hotosm/fmtm/blob/main/docs/DEV-3.-Frontend.md

**Comment by mohammadareeb95** [comment]
Thank you for structuring this. :smile: 
I believe the Frontend wiki page will also follow the same pattern as the [Backend](https://github.com/hotosm/fmtm/wiki/DEV-2.-Backend) wiki page

**Comment by spwoodcock** [comment]
Agreed 👍 I would be great to add a little bit of extra context at the start to explain that it is a microfrontend & uses Webpack remote modules to federate that (if you can, no worries if not).

**Comment by octonawish-akcodes** [comment]
I cannot join the slack, I am an outreach applicant and there are no more issues available to work on @spwoodcock can you help here,

**Comment by biomassives** [comment]
Hi Abhishek [@octonawish-akcodes](https://github.com/octonawish-akcodes)  [https://github.com/hotosm/fmtm/issues](https://github.com/hotosm/fmtm/issues) Have a look at the github issues to track current FMTM issues.

**Comment by octonawish-akcodes** [comment]
Where can I get the slack link ?
@biomassives

**Comment by KesharwaniArpita** [comment]
Hey there, This is Arpita , An Outreachy applicant .I am excited to express my interest in participating in the contribution period for the Outreachy internship program in this project.

**Comment by CartoonistDev** [comment]
Hey everyone. My name is Chizzy, I am an outreachy applicant. I am excited to contribute to this project

**Comment by mohammadareeb95** [comment]
Hey @spwoodcock! 
I've opened a [PR](https://github.com/hotosm/fmtm/pull/137) to the best of what I understood. Please feel free to make any suggestions. :smiley:

**Comment by Linda-Njau** [comment]
The frontend documentation has now been added, should we still make our own?

**Comment by spwoodcock** [comment]
Hi @Linda-Njau, I merged the frontend docs PR yesterday and made some edits too. We have a good base, so I will close this issue, but feel free to correct / refine anything!
