### ISSUE TITLE
unable to search projects

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1292]
**Describe the bug**
on projects page i am unable to search any projects by its name or project id, I encounter 500 internal server error with search project API trying to search projects.

**To Reproduce**

1. Go to 'home page'
2. search any projects with project name or project id
3. See error

**Expected behavior**
The projects should be searched according to project name or project id.

**Screenshots**
![image](https://github.com/hotosm/fmtm/assets/97273021/80c9e717-d4df-4c9b-bf55-05008e9c2ea9)

**Comment by spwoodcock** [comment]
Ah crap, I think that was my bad!
Thanks for picking this up.

I refactored so that project.project_name_prefix is actually a prefix with underscores, while project_info.name is the project name.

The search should be using project_info.name.
Raw SQL would probably be best
