### ISSUE TITLE
Unable to view form on scanning QR

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1302]
**Describe the bug**
After solving the recent submission table crashing issue, I have encountered the problem where i scan the QR code of any task and get blank form. Moreover, I get no download form section too for downloading form. 

**To Reproduce**

1. Go to 'project page'
2. Click on 'any task to open QR pop-up'
3. Scan the QR on odk collect

**Expected behavior**
the qns on the form should be visible and user should be able to fill and submit the form

**Screenshots**
![Screenshot_2024-02-29-11-31-42-35_171725cd2e369f62c287134214eaed67](https://github.com/hotosm/fmtm/assets/97273021/068aaa8b-9336-494b-8e6f-5534d880821f)
![Screenshot_2024-02-29-11-31-38-57_171725cd2e369f62c287134214eaed67](https://github.com/hotosm/fmtm/assets/97273021/a7cc5da4-4854-4ecf-92c4-f7e1f644a3fd)

**Additional context**

**Comment by spwoodcock** [comment]
This is the issue I mentioned I had solved yesterday but haven't had a chance to finalise with the mapping support. Will finish this morning 👍
