### ISSUE TITLE
There is no indication of whether a feature/building has already been mapped.

### ISSUE THREAD

**Issue by susmina94** [hotosm/fmtm#1344]
**Is your feature request related to a problem? Please describe.**
The mappers cannot recognize the buildings that has already been surveyed/mapped. It creates a confusion for the mappers to understand whether they've already mapped those or not because there's no such indication on FMTM or ODK. This can eventually sometimes, cause data redundancy, difficulty in identifying the correct ones.

**Describe the solution you'd like**
It would be great to see the building change color once they are mapped or a submission has been made using that feature.

This will help the users to understand:
1. The building has already been mapped 
2. The users also get an insight on how many buildings are left to be mapped

**Comment by spwoodcock** [comment]
Related to #1383

This is now possible use Entities.

I propose:
- We load the Entity info on project detail page via OData endpoint (osm-fieldwork) has this.
- When user clicks start mapping, we update the entity `status` field to 'IN_PROGRESS` via API and also update their local state to colour the building yellow locally for the user (also useful if mapping offline).
- All other users that load the Entities will also see a yellow building in progress.
- When user clicks mapping complete then we update status to 'COMPLETE' and colour green.

**Comment by spwoodcock** [comment]
Superseded by https://github.com/hotosm/fmtm/issues/1417
