### ISSUE TITLE
The drone imagery overlay would assist in better navigation to the desired feature/building before I start mapping 

### ISSUE THREAD

**Issue by susmina94** [hotosm/fmtm#1345]
**Is your feature request related to a problem? Please describe.**
The current userflow is:

1. User selects a random task/ task around their neighbourhodd based on GPS location -> fetches the QR code -> Setup form in ODK via qr code
2. User opens a new form -> selects a field to choose a building/feature 
3. Before the user selects a feature ->  overlays the drone imagery -> navigates around to identify the building
4. Finally identifies -> selects a building -> submits a form

It is quite okay for a project with just a single form but for example :
A project with multiple form choices:

- Health institution
- Educational institution, etc

The user should be able to identify the type of building before they select the form

**Describe the solution you'd like**
The expected workflow:

1. User overlays the drone imagery -> overlays the drone imagery -> navigates around to identify the building
2. Finally identifies -> selects a building -> submits a form

That means, the project page should load the basemap with the building/features and task boundaries such that the user identifies the type of building he/she is going to map.

**Comment by spwoodcock** [comment]
This is solved by generating custom TMS imagery, then loading the PMTiles into OPFS as a offline basemap layer. Solved.
