### ISSUE TITLE
Boundary of AOI changes when task are splitted based on square

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1351]
**Describe the bug**

**To Reproduce**

1. Go to 'create project
2. Draw or upload the AOI
3. Split the AOI by square of fixed size.

**Expected behavior**
The AOI shouldn't change, when the task are splitted based on square of certain size

**Screenshots**
![image](https://github.com/hotosm/fmtm/assets/97273021/861e5b4b-f49e-4c62-87a8-1ba6d9e96283)
![image](https://github.com/hotosm/fmtm/assets/97273021/5595b80d-3161-44f0-afbe-9f64c2bc6e1a)

additional information:
This can be issue of high priority since this is affecting form. 
The tasks which doesn't touch uploaded AOI, the scan is available but shows issue in ODK.

**Comment by manjitapandey** [comment]
@Sujanadh Is this issue ready for QA?

**Comment by Sujanadh** [comment]
Yes
