### ISSUE TITLE
List automated test case scenarios for project creation workflow

### ISSUE THREAD

**Issue by susmina94** [hotosm/fmtm#1354]
**Is your feature request related to a problem? Please describe.**
The purpose of a test case is to determine if different features within a system are performing as expected and to confirm that the system satisfies all related standards, guidelines and customer requirements. The process of writing a test case can also help reveal errors or defects within the system.

Currently, we are trying to incorporate a lot more open source contributors in the project to write down the test cases. However, we do not have sufficient documentation or way ahead for them to contribute in test cases. 

**Describe the solution you'd like**
@manjitapandey will be writing down the list of test case scenario for the project creation workflow that will help the developers understand the test case scenario, relevant conditions they need to pass and the expected results out of the test cases.
You may find the test case scenario listed in this sheet here:
https://docs.google.com/spreadsheets/d/1z4ctAquRcpXRam5Sb0cnqXT6asAzkwe42MPhV8szH6U/edit#gid=0

**What do each column in the sheet refer to?**

A comprehensive demo of what is in the sheet is outlines with a an example.

Step 1: There is a test case scenario in the _**Test Case Scenario**_ column:
Eg: _Uploading project boundary during project creation_

Step 2: You can manually replicate the condition as viewed in **_Test Steps_** column:
Eg:
1. create project button
2. add necessary infomation on step 1
3. click on upload
4. browse through your files to upload .geojson file

Step 3: The condition you need to pass for the test is viewed in **_Pre-condition_** column:
Eg: User should be able to upload the file with .geojson format only. Please check if the file loads well with geojson.io before uploading the geojson. 

Step 4: The expected result after you pass for the test is in **_Expected Result_** column:
Eg: The input should throw error "File format is not supported" if the user uploads any other file except .geojson format. 

Step 5: You may write down the actual results after you run the test cases you prepare that is an exception to that of expected result

Step 6: The **_status_** column defines if the test case is passed or failed

**Comment by spwoodcock** [comment]
Related: https://github.com/hotosm/fmtm/discussions/1335

I made a quick page to ask any user to confirm working functionality on staging, prior to production deploy.

It's quite basic - feel free to update or suggest changes!

**Comment by spwoodcock** [comment]
I also planned to keep track of releases here

**Comment by spwoodcock** [comment]
The linked discussion is for manual test cases, where I think this issue is about automated tests 👍

**Comment by spwoodcock** [comment]
I sent this to @azharcodeit who is working on backend test cases:

Important for mapping (highest priority)
- auth/introspect
- projects/summaries
- projects/{project_id}
- projects/{project_id}/entities/statuses
- POST tasks/{task_id}/new-status/{status_number}
- POST projects/{project_id}/entity/status
Project creation flow:
- /organisation/
- /central/list-forms
- POST /projects/task-split
- POST /projects/create_project
- POST /projects/{project_id}/upload-task-boundaries
- POST /projects/upload-custom-extract/
- POST /projects/{project_id}/generate-project-data

All other endpoints are lower priority, but eventually we want 100% coverage!
Closing.
