### ISSUE TITLE
Add Playwright tests for project creation workflow

### ISSUE THREAD

**Issue by susmina94** [hotosm/fmtm#1355]
Is your feature request related to a problem? Please describe.
The purpose of a test case is to determine if different features within a system are performing as expected and to confirm that the system satisfies all related standards, guidelines and customer requirements. The process of writing a test case can also help reveal errors or defects within the system.

We have very limited test cases in the platform, which is making the platform unstable with every release.

Describe the solution you'd like
Here are the list of the test case scenario, relevant conditions they need to pass and the expected results out of the test cases.
https://docs.google.com/spreadsheets/d/1z4ctAquRcpXRam5Sb0cnqXT6asAzkwe42MPhV8szH6U/edit#gid=0

**_How can you start writing down the test cases?_**
A comprehensive demo of what is in the sheet is outlines with a an example.

Step 1: There is a test case scenario in the Test Case Scenario column:
Eg: Uploading project boundary during project creation

Step 2: You can manually replicate the condition as viewed in Test Steps column:
Eg:

1. create project button
2. add necessary infomation on step 1
3. click on upload
4. browse through your files to upload .geojson file

Step 3: The condition you need to pass for the test is viewed in Pre-condition column:
Eg: User should be able to upload the file with .geojson format only. Please check if the file loads well with geojson.io before uploading the geojson.

Step 4: The expected result after you pass for the test is in Expected Result column:
Eg: The input should throw error "File format is not supported" if the user uploads any other file except .geojson format.

Step 5: You may write down the actual results after you run the test cases you prepare that is an exception to that of expected result

Step 6: The status column defines if the test case is passed or failed

**Comment by spwoodcock** [comment]
A good option for this is to use Playwright to test the project creation workflow.

I propose we implement this on the frontend.

**Comment by varun2948** [comment]
We have just got started with playwright, will keep you updated on this further @spwoodcock

**Comment by spwoodcock** [comment]
Oh very nice, I was just about to do the same - I'll leave you to it!

Let me know if I can help with the dependencies part - we could make a config to run the tests via docker with all dependencies bundled by default (browsers etc) 👍

**Comment by spwoodcock** [comment]
Looks like Playwright needs some system dependencies:

```
libgtk-3-0 libnss3 libasound2 libgbm-dev
```

**Comment by varun2948** [comment]
@spwoodcock my playwright install is showing weird issue do you know anything about this ?
![image](https://github.com/hotosm/fmtm/assets/37866666/c10311e9-9463-4726-a25f-10ee39be1b96)

**Comment by spwoodcock** [comment]
Any Linux distribution apart from Ubuntu is not 'officially' supported, but should probably work fine.
If you don't encounter any issues, then it should be all good =)

**Comment by varun2948** [comment]
hmm yeah it worked but kept giving warning but thats fine i guess. Thanks sam
