### ISSUE TITLE
Encryption of project id on URL

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1386]
**Is your feature request related to a problem? Please describe.**
This may not be an immediate issue but i don't see any point on why do we encrypted project id on URL. I think it will provide more information if we don't encrypt project id. 

**Describe the solution you'd like**
Non encryption of project id on URL. 

**Additional context**
If anyone is aware of why we have done encryption, please share it.

**Comment by spwoodcock** [comment]
I forgot where we already discussed this, but Varun said it was something that Mohdi did with the original microfrontend and was kept.

We don't need it - 100% agree, remove it 😄
