### ISSUE TITLE
Location extraction isn't visible on project cards

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1388]
**Describe the bug**

**To Reproduce**

1. Go to 'Project card page'
3. Scroll down to 'any recent project card'

**Expected behavior**
The location should be generated automatically from Uploaded AOI and should be seen on project cards. 

**Screenshots**
![image](https://github.com/hotosm/fmtm/assets/97273021/b714a2ce-a32e-426e-b843-64bd46cca59f)

**Additional context**
It used to function previously but hasn't been functional now.

**Comment by spwoodcock** [comment]
This is occurring again.
I am assuming there is something wrong with chaining `computed_field` in Pydantic.
I will solve this with a model_validator at the final stage instead to hopefully fix 🙏
