### ISSUE TITLE
start mapping button is not functional on mobile website and PWA

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1393]
**Describe the bug**
I am unable to click on start mapping of any task on mobile. However it works on laptop. 

**To Reproduce**

1. Go to 'project page'
2. Click on 'any task'
3. Click on "start mapping"

**Expected behavior**
The status of task should be changed to locked for mapping. 

**Screenshots**

**Smartphone (please complete the following information):**

- Device: [Oppo F19 pro]
- Browser [Chrome]

**Comment by spwoodcock** [comment]
Hmm, is this dev stage or prod?

**Comment by manjitapandey** [comment]
It was replicable on all servers. Seems like this issue is there when users aren't logged in. 
The solution could be either allowing user to lock task without logging in or redirecting them to log in page.

**Comment by spwoodcock** [comment]
For now can we allow locking and unlocking without log in? @Sujanadh

**Comment by Sujanadh** [comment]
> For now can we allow locking and unlocking without log in? @Sujanadh

okay but how do we track who updated the status?

**Comment by spwoodcock** [comment]
Good question!

We either don't provide the info of who updated & allow unauthenticated access, or provide a basic API for a simple type of auth.

We talked about email based auth being an option, but it would be very nice if we don't even need an email address!

What do you think about us having a temporary login token option, valid for one week?

The token would have restricted access to only view projects and update task status. 

The user could provide their name in an input field, and the API will generate and return a token in a cookie. 
This token will behave like the OSM cookie, but only be valid for one week

Open to other ideas too!

**Comment by Sujanadh** [comment]
It sounds good to me

**Comment by Sujanadh** [comment]
what about using jwt ? or are we saving token in database for basic authentication?

**Comment by Sujanadh** [comment]
saving user info wont be possible unless we create a separate table for that. if it is temporary approach then we don't have to think much on saving user data. Using svcfmtm might be good as you mentioned.

**Comment by spwoodcock** [comment]
I think it's the way to go for now then 👍

We can work out how to link to private projects later. 

One idea:
- The temp tokens can be granted by the project admin, where they enter an email address.
- Then a link is sent to the user.
- When they click a link in the email it sets a temp cookie via the API.

**Comment by manjitapandey** [comment]
I am unable to test this since. the project area is not visible in mobile.

https://github.com/hotosm/fmtm/assets/97273021/611fb74c-c53e-40d9-b200-00a3e065c7f5

**Comment by spwoodcock** [comment]
This should be testable now.
