### ISSUE TITLE
Unable to download mbtiles on mobile

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1394]
**Describe the bug**
I am unable to download mbtiles on mobile phone. The pop-up to download mbtiles appear and user can select tile source and output format, but when we click on generate button, No layer to be download is seen. 

**To Reproduce**

1. Go to 'Project page'
2. Click on 'Generate mb tiles'
3. Select mbtiles and output format and click on generate

**Expected behavior**
The mbtiles should be generated smoothly.

**Screenshots**
![Screenshot_2024-03-27-10-58-15-90_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/hotosm/fmtm/assets/97273021/9a877d05-85d4-440c-9911-902264b7bd92)

**Smartphone (please complete the following information):**

- Device: [Oppo F19 Pro]

- Browser [Chrome]

**Comment by spwoodcock** [comment]
I believe this is solved. Reopen if not 👍
