### ISSUE TITLE
Images and links not visible as preview on instruction field

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1401]
**Describe the bug**
During first step of project creation, Images and links not visible as preview on instruction field

**To Reproduce**

1. Go to 'create project
2. Click on 'image link on instruction field'

**Expected behavior**
The link should be seen and image should be seen in preview

**Screenshots**
https://vimeo.com/928660136/3093bfc6be?share=copy

**Comment by manjitapandey** [comment]
Latest update: When image is uploaded and user goes to next step and come back to first step, the image is no more visible.

**Comment by NSUWAL123** [comment]
@manjitapandey could you elaborate the issue description and video. I am abit confused so could you replicate the steps in video
