### ISSUE TITLE
Needs word limit on short description

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1402]
**Describe the bug**
FMTM allows unlimited word or character limit for now.

**To Reproduce**

1. Go to 'create project'
2. Click on 'short instruction'
3. Add very long texts 

**Expected behavior**
Since it will be shown on project card on limited space, we need to provide word or character limit on short description during project creation.

**Comment by NSUWAL123** [comment]
what should be the character limit?

**Comment by manjitapandey** [comment]
200 characters
