### ISSUE TITLE
Modification of mobile UI and components to make mobile friendly

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1409]
**Is your feature request related to a problem? Please describe.**
Few components and views are not mobile friendly. The login state is not visible on homepage. similarly, many buttons have hover effect and tooltips on fmtm causing them to be not mobile friendly.

**Describe the solution you'd like**
A modification on mobile design for few pages like login page and project page to make it more mobile friendly for field mappers.

**Additional context**
Further details will be discussed with design team and will be updated on comment of the same issue.

**Comment by manjitapandey** [comment]
![Screenshot_2024-04-01-15-12-48-32_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/hotosm/fmtm/assets/97273021/27b30389-a5c2-4cb5-8d17-73b6c3a5932d)
![Screenshot_2024-04-01-15-38-13-53_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/hotosm/fmtm/assets/97273021/370d0d34-9c5c-4d58-a671-3b236f9dae5a)
![Screenshot_2024-04-01-15-39-02-64_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/hotosm/fmtm/assets/97273021/420cff12-dc07-4a33-a518-d075ec29b772)
![Screenshot_2024-04-01-15-39-09-39_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/hotosm/fmtm/assets/97273021/afc6d2d7-1612-421d-bb56-75797d0ff962)
![Screenshot_2024-04-01-15-39-19-91_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/hotosm/fmtm/assets/97273021/33df2477-1ff6-46fe-a652-883d706167b4)
![Screenshot_2024-04-01-15-39-49-79_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/hotosm/fmtm/assets/97273021/eb95fb89-30c0-42fe-9754-583beb6287e2)

**Comment by NSUWAL123** [comment]
@manjitapandey, hover effects and tooltips are not supported in mobile devices. So adding hover effects and tooltips are not possible for mobiles.

**Comment by manjitapandey** [comment]
I think the term basemap should be changed to tiles.

**Comment by spwoodcock** [comment]
Oh sorry, I changed that. 

I don't think the average user knows what a tile is & basemap is more user facing. Maybe I'm not giving enough credit to the geospatial knowledge of most people.

If it's your experience that 'tile' is well understood, feel free to change it! 😄

**Comment by manjitapandey** [comment]
I just guessed users will get confused if we named it by basemap since it typically means different. What if users tried changing baselayer and they are directed towrds option of mb tiles or pm tiles downloading??

**Comment by spwoodcock** [comment]
Baselayer! That's a much better word 😁

Or 'Offline Map' could also be a possibility. 

I guess only user testing will tell us for sure, but I'll follow whatever you think is best!
