### ISSUE TITLE
Should hide few buttons for not signed in user.

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1414]
**Is your feature request related to a problem? Please describe.**
Now user can access to few buttons like create project button, manage project and review submissions without signing in. Doing so, it causes conflict since user doesn't have access to do so. 

**Describe the solution you'd like**
We can hide or disabled such buttons for not signed in user and should only be enabled if the users are logged in. 

**Describe alternatives you've considered**
Alternatively, user can also be redirected to login pop-up if user click on those buttons. 
![image](https://github.com/hotosm/fmtm/assets/97273021/598dfd86-b65e-46b7-90c1-4bec5b134d12)

**Comment by spwoodcock** [comment]
Hiding is a possibly a nicer user experience, but means the layout may change after removing a button (requires testing).
Disabling a button guarantees a consistent layout.

**Comment by NSUWAL123** [comment]
@spwoodcock, @manjitapandey, I think this issue would solve this issue where sign-in popup is displayed and after a successful sign-in, the users would get redirected to the requested page. What do you think? 
- https://github.com/hotosm/fmtm/issues/1556

**Comment by spwoodcock** [comment]
I believe we have code for `ProtectedRoute` in the frontend right?

So as you say, if the user clicks and is not signed in, then they are prompted to sign in and redirected if they have permission.
If they don't have permission to access the page, an error popup could display saying 'You do not have the required permission'.

Would that work for now?

(perhaps we can hide things like the 'Create Project' button from the user, but to do this we need the user role saved in the frontend - I'm not sure if we have that yet?)

**Comment by manjitapandey** [comment]
> Would that work for now?
yeah that would be perfect. 




> (perhaps we can hide things like the 'Create Project' button from the user, but to do this we need the user role saved in the frontend - I'm not sure if we have that yet?)

We haven't. this could be pushed to later ( mapper roles )
