### ISSUE TITLE
Geolocation permission request is not made correctly

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1428]
**Describe the bug**

- If geolocation is not enabled by default, normally websites request for permissions to access it:

![Screenshot_20240406-115406.png](https://github.com/hotosm/fmtm/assets/78538841/edd7407c-0f59-4fdf-81a0-45aac9aa8318)

- Then the user grants it

![Screenshot_20240406-115415.png](https://github.com/hotosm/fmtm/assets/78538841/a9969929-dc9b-44d8-8d07-1b26896777e0)

- Instead we just get

![Screenshot_20240406-115439.png](https://github.com/hotosm/fmtm/assets/78538841/4e32ad0e-6f64-496c-b1db-e52f1e5274aa)

**To Reproduce**

Disable geolocation permission default for the browser in android settings. 

**Expected behavior**

- The user is promoted for permission.
- This is all done with native web APIs, and not hooking into the Android APIs. 

**Smartphone (please complete the following information):**

- Device: Pixel 6
- OS: Android 13
- Browser: Vanadium, privacy enhanced Chromium. 

**Additional context**:

Just in case this was some Google wizardry, hooking into Android APIs, I tested on OpenStreetMap and its the same:

![Screenshot_20240406-120136.png](https://github.com/hotosm/fmtm/assets/78538841/e33ba65e-afd2-4076-9c79-fbc3f352874f)

**Comment by NSUWAL123** [comment]
@spwoodcock, it seems that for the first time, the browser would ask the user for the location permission where the browser would give 2 options: `allow` and `deny`. If the user `denies` to give location permissions, and the 2nd time if the user again if the user clicks the location button then the browser will give a message: `User denied location`. 
This seems to be the default behavior of the browser to respect users' privacy. 

I had researched and I think the only option left is to clearly tell user where they can change their location settings to enable location services.
Any suggestions?

**Comment by spwoodcock** [comment]
I am testing on openstreetmap.com:
- If I deny the first time, the I get the error you said: `User denied location`.
- I can then click the geolocation icon again and it prompts me again.
- If I accept the second time, it works as it should.

This suggests it should be possible!

I will check the openstreetmap code as an example to see if we can do something similar 👍

**Comment by spwoodcock** [comment]
If the user denies permission on a web browser, then this is remembered for subsequent attempts to geolocate.
The user must refresh the page to try again.
It's normal browser behavior, so it's fine to leave it like that :thumbs

**Comment by spwoodcock** [comment]
### Different browser behaviours

Interesting!
The behaviour is different on Firefox.
Chrome seems to remember your selection, but Firefox does not.

Uploading Recording 2024-04-18 145911.mp4…

Always be sure to test your features on both Chrome and Firefox (and, if possible, Safari would be great too).
Playwright can help with this in future though!

### Closing this issue

When testing on Android I got the following behaviour:
- First prompt for geolocation is denied.
- Clicking the button again allows for a second attempt / prompt.
- If this is denied again, then it needs to be reset in the device settings (refresh doesn't help either) - the same behaviour you show in the video!

I think the current behaviour is fine in this case.

### Related issue

I will close this issue for now & if we encounter any problems in the future we can revisit.

A related issue to this, after recent updates I can't seem to load the dev server at all, unless I delete cache / use incognito.
I don't know if this is PWA related, or caching via the Nginx proxy.
To be investigated - I may make a new issue about it.
