### ISSUE TITLE
Add Frequently Asked Questions (FAQs) to the documentation 

### ISSUE THREAD

**Issue by neelimagoogly** [hotosm/fmtm#147]
-  Include a section for frequently asked questions (FAQs) that users may have about Field Mapping Tasking Manager Application and its use .

-  Provide answers to common questions.

@petya-kangalova and @robsavoye the above is my suggestion and would like to work on it if you allow me and assign me.

**Comment by Ndacyayisenga-droid** [comment]
Hey @petya-kangalova,
Can I work on this?

**Comment by peter-abel** [comment]
Outreachy applicant here, has anyone been assigned on the task above?

**Comment by neelimagoogly** [comment]
@petya-kangalova I have raised this issue , so please give me chance and assign me this.

**Comment by peter-abel** [comment]
> @petya-kangalova I have raised this issue , so please give me chance and assign me this.

you are right.

**Comment by robsavoye** [comment]
A FAQ would be good. Ideally it would be accessible via the wiki too.

**Comment by petya-kangalova** [comment]
@neelimagoogly  thank you and yes, please! That is a good suggestion- please go ahead and work on it. It will be good to think about what the audience for the FAQ will be- is it mainly developers contributing or people who will be using the app? FMTM is still in development- some of the other products in the pinned repos will also benefit from FAQs.  As @robsavoye  having the FAQ accessible via Wiki will be great.

**Comment by neelimagoogly** [comment]
@petya-kangalova and @robsavoye , I have added a PR at #173 regarding this issue. Please review it.
