### ISSUE TITLE
Unable to view building footprint on odk

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1472]
**Describe the bug**
When i try to fill the form, There is option for selecting building footprint but i couldn't see any footprint even though i zoomed in to exact area of interest. I used default form and osm data extract during project creation.

**To Reproduce**

1. Go to 'any project
2. Click on 'start mapping and scan the QR from odk mobile app
3. try filling the form of select building footprint

**Expected behavior**
The foot print should be visible in odk mobile application

**Screens
![Screenshot_2024-04-24-15-10-27-88_171725cd2e369f62c287134214eaed67](https://github.com/hotosm/fmtm/assets/97273021/90cb4633-940a-4572-a992-905fc8387920)
hots**

**Comment by spwoodcock** [comment]
Did you select the task id first? The buildings only populate now after the task id is selected 😄 

The idea is that the task id can be filled by mobile intent, or even better, the Entity itself is selected already.

**Comment by spwoodcock** [comment]
But this raises a good question! Can the features be filtered in the XLSForm to display all if there is no task_id selected, else filter by task_id? I will look into it 👍

**Comment by manjitapandey** [comment]
For now, The building footprints are not visible until task ID is selected. But the catch is the qn to select task ID is optional on default form. I am also curious what will happen if user upload custom XLS form?? Will the building appear if they didn't add qn to choose task ID??
@spwoodcock
