### ISSUE TITLE
Automatically lock a task area if the 'Map Feature In ODK' button is clicked for a feature

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1475]
**Is your feature request related to a problem? Please describe.**

![image](https://github.com/hotosm/fmtm/assets/78538841/b10f9cf5-0b72-4b26-9e95-8f1839372920)

- Currently the user can click the button and map a feature, without locking the parent task.

**Describe the solution you'd like**

- If the user clicks the 'Map Feature In ODK' button, the parent task should automatically be locked.
- Also, the 'Map Feature In ODK' button should be disabled if the task is locked alreadyby another user. 

@manjitapandey does this make sense?

**Comment by manjitapandey** [comment]
I agree with that.
