### ISSUE TITLE
Validate features are mapped sufficiently before task completion is possible

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1476]
**Is your feature request related to a problem? Please describe.**

- Currently the user can mark the task as mapped by clicking the button:

![image](https://github.com/hotosm/fmtm/assets/78538841/fe837015-424f-4cf2-af9b-8e1f9768ccd0)

- This can be clicked even if the user maps no features, or does not map them all.

**Describe the solution you'd like**

- Some basic validation that the task area has been mapped sufficiently.
- Perhaps 80% of the features need to be mapped before the user can mark the area as fully mapped?
- Or we should probably actually make this a warning, rather than a hard requirement, for flexibility:
  - A modal: 'You have only mapped 4/10 features in the task area. Are you sure you wish to mark as complete?'

@manjitapandey

**Comment by manjitapandey** [comment]
My personal opinion would be I will go with the warning message rather than hard requirement.
