### ISSUE TITLE
Statuses endpoint failed on submission made via ODK

### ISSUE THREAD

**Issue by NSUWAL123** [hotosm/fmtm#1478]
**Describe the bug**
`/Statuses` endpoint throws 500 error after building submission made via ODK.

**To Reproduce**
1. Create a project
2. Go to project-details page (Here the `/statuses` endpoint is hit and the response status is 200)
3. Go to ODK and make a submission
4. Go to or Refresh the project-details page and see 500 error on `/statuses` endpoint

**Expected behavior**
/statuses API should not throw a 500 error even if a submission is made.

**Screenshots**
Before submission was made: 
![image_720](https://github.com/hotosm/fmtm/assets/81785002/08902742-feaa-458e-aff9-e72d325cfd8b)

After submission was made: 
![image](https://github.com/hotosm/fmtm/assets/81785002/fd2d35ec-c487-4174-9c7e-5bb568cdfed4)

**Smartphone (please complete the following information):**

- Device: [Laptop]
- OS: [Ubuntu]
- Browser [Google Chrome]
- Version []

**Additional context**

**Comment by Sujanadh** [comment]
endpoint works fine, but when submission is made how odk collect sends status to the odk central? it is passing quoted task status . For eg: 'status' : ' "2" '.

**Comment by Sujanadh** [comment]
@spwoodcock

**Comment by spwoodcock** [comment]
Interesting!

The integer value needs to be quoted, as Entity fields can only be string type.

But it looks like double quoting that needs to be fixed.

Not sure why that would cause a 500 though!

**Comment by spwoodcock** [comment]
Fantastic - great debugging!

Do you think this could be caused by the XLSForm?

The `status` field defaults to `"2"1 and the calculation logic is `if(${digitisation_correct}='no', "6", "2")`

**Comment by NSUWAL123** [comment]
@spwoodcock, currently the /statuses api would return thousands of statuses of features of the entire project.
Is this approach good? As we have to filter that thousands of buildings status to colorize each feature. 

Is returning the statuses of the features bound to that task would be a good approach? like when a user clicks a task then `/statuses` endpoint is called with a filter of `taskId`
