### ISSUE TITLE
The mapped and validated graph isn't updated when activity is recorded in Task activity section.

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1482]
**Describe the bug**
In infographics page, there is a graph to show the number of mapped and validated tasks when user changes the status of task to mapped or validated. But the error here is the graph shows no tasks has been mapped or validated though i have marked multiple tasks as mapped. 

**To Reproduce**

1. Go to 'project page
2. Click on 'tew tasks and mark them mapped and change status of few tasks as validated.'
3. Go to infographics page and view the mapped and validated graph.

**Expected behavior**
The number of tasks mappedd and validated should be reflected on graph.

**Screenshots**
![image](https://github.com/hotosm/fmtm/assets/97273021/30f0de50-6372-4d6c-8ed0-3342dbb76764)

**Comment by spwoodcock** [comment]
Related to: https://github.com/hotosm/fmtm/issues/1483
We can also determine the feautures mapped and validated using their Entity `status` property, instead of requiring a separate endpoint.

**Comment by Sujanadh** [comment]
Ugh i just made a PR on this 😅
