### ISSUE TITLE
Task completion endpoint showing false submission count

### ISSUE THREAD

**Issue by NSUWAL123** [hotosm/fmtm#1483]
**Describe the bug**
When submission made to one task via ODK collect, all other tasks submissions is also incremented. 
For example: 
Assume a project has 10 tasks. When a submission is made to one task via ODK, the submission count of that task should only increment but submissions of other tasks are also incremented .

**To Reproduce**
1. Create a project
2. Go to ODK collect and make a submission to any one task 
3. Go to the project submissions page or  refresh the page and open the network tab
4. See the response of the `/task-completion` API and see incremented submission counts of all the tasks 

**Expected behavior**
The submission count of that specific task should only increase when submission is made. 

**Screenshots**
Here I made 2 submissions to task 5 only but the entire task submission count seems to be updated.
![image](https://github.com/hotosm/fmtm/assets/81785002/80a5ed3d-f4b1-40bc-8006-52bb0cc5d02d)

**Laptop (please complete the following information):**

- Device: [Laptop]
- OS: []
- Browser [Chrome]

**Additional context**

**Comment by spwoodcock** [comment]
Good catch, thanks!

Previously each task was mapped to an XForm.
Now each task uses the same XForm, hence the issue here.

The submissions stuff needs a big overhaul now we are using Entities. The submission count can probably be determined without needing a separate endpoint now.

We could use the response from `/project/id/statuses` to determine how many features have status=2. Those Entities have been mapped and count as a submission.

**Comment by spwoodcock** [comment]
As the response also includes when the Entities were last updated, those values could be filtered and the 'last_submission` value also determined.

![image](https://github.com/hotosm/fmtm/assets/78538841/a6f44756-b99b-44dd-960f-ce325f8561fe)

Do you think you could handle this entirely on the frontend @NSUWAL123 ?
- Remove the call to `task-completion`.
- Get the statuses and last submission time from the `/projects/{project_id}/entities/statuses` endpoint by filtering.

**Comment by NSUWAL123** [comment]
> As the response also includes when the Entities were last updated, those values could be filtered and the 'last_submission` value also determined.
> 
> ![image](https://private-user-images.githubusercontent.com/78538841/325972712-a6f44756-b99b-44dd-960f-ce325f8561fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NDg4MzcsIm5iZiI6MTcxNDQ0ODUzNywicGF0aCI6Ii83ODUzODg0MS8zMjU5NzI3MTItYTZmNDQ3NTYtYjk5Yi00NGRkLTk2MGYtY2UzMjVmODU2MWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDAzNDIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MTM2YWFmNGMxOTcxMjVmNDU2NTVmNWE5MmYwZjIzOTUxNDlkMGFmOWE3YzRhMjQ3MDk1Y2Y5ZGMwZDc1ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sSgTVwo6V3laaaP7fzA_kgLKqGA7XWBd6JheVVADWKQ)
> 
> Do you think you could handle this entirely on the frontend @NSUWAL123 ?
> 
> * Remove the call to `task-completion`.
> * Get the statuses and last submission time from the `/projects/{project_id}/entities/statuses` endpoint by filtering.

@spwoodcock could you elaborate

**Comment by manjitapandey** [comment]
The task endpoint API no longer exists and we are shifting to statusus API. So i am closing this issue for now
