### ISSUE TITLE
The project is created though user upload data extracts on different coordinate system.

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1494]
**Describe the bug**
During project creation, when user upload data extracts of different coordinate system which is not supported by FMTM. The validation isn't right away. The project is created anyways and during QR generation, it shows the error message saying unsupported coordinated system. 

**To Reproduce**

1. Go to 'create project
2. Upload data extract of unsupported format.
3. create project

**Expected behavior**
The project shouldn;t be created if user upload unsupported ccordinate system. Validation of coordinate system should be prior to project creation. 

**Screenshots**
![image](https://github.com/hotosm/fmtm/assets/97273021/bcfb8f6a-efa3-4fe0-9438-52500afce3ea)

**Additional context**
The data extract i used: 

[nepalgunj_building.zip](https://github.com/hotosm/fmtm/files/15148313/nepalgunj_building.zip)

**Comment by spwoodcock** [comment]
This might be partly solved by recent changes where we delete the project if something fails.

It should be investigated in 2024.5.0 during project creation overhaul.

**Comment by manjitapandey** [comment]
I actually couldn't reproduce the issue now since `https://api.dev.fmtm.hotosm.org/projects/75/generate-project-data` goes timeout everytime. And there is no error for unsupported coordinate system.
