### ISSUE TITLE
Swap order of task history tabs

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1495]
**Is your feature request related to a problem? Please describe.**

- We have a 'Comments' tab and 'Task Activity' tab for a task:

![image](https://github.com/hotosm/fmtm/assets/78538841/9f732287-11e3-483e-8a32-f26fbbd2d6d3)

- When we click on a task, two endpoints are called:
  - http://API/tasks/60/history/?comment=false
  - http://API/tasks/60/history/?comment=true
- This is inefficient: we should probably call the endpoint with `comment=true` or `comment=false` depending on which tab the user clicks.

**Describe the solution you'd like**

- Personally I think we should swap the 'Task Activity' tab to be the first (default) tab.
- The `http://API/tasks/60/history/?comment=false` endpoint should be called when the user clicks the task, populating the task activity list.
- Only if the user clicks the 'Comments' tab should the task history `?comment=true` endpoint be called.

Do you agree @manjitapandey ?
Work for next release 👍

**Comment by manjitapandey** [comment]
I guess this will be better one for user experience. Lets go on next release.
