### ISSUE TITLE
Unable to generate osm data extracts

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1497]
**Describe the bug**
During project creation, I am being unable to generate osm data extracts. I encountered 422 error in network panel response saying "Could not get download URL for data extract. Did the API change?". 

**To Reproduce**

1. Go to 'create project'
2. Click on 'generate data extract'
3. See error

**Expected behavior**
The data extract should be generated without any error. 

**Screenshots**
![image](https://github.com/hotosm/fmtm/assets/97273021/00f12fba-d816-4a85-a5d4-b4950c0fe1bc)

**Comment by spwoodcock** [comment]
It's a config error in the deploy variables - we need to just update the access token for it to work 👍

**Comment by spwoodcock** [comment]
I have redeployed with the variable correctly set - hopefully this fixes it 🤞

**Comment by manjitapandey** [comment]
I am still facing the issue. May be @nrjadkry can have a look at this.

**Comment by spwoodcock** [comment]
I found the solution to this.

### Issue

`osm-login-python` does not actually provide the raw token used for OSM auth, but instead provides the token encrypted with the SECRET_KEY variable.

As a result, the svcfmtm user may have the same raw OSM token for both FMTM and `raw-data-api`, but the token required by `osm-login-python` is different!

### Solution

We are currently using the `OSM_SVC_ACCOUNT_TOKEN` variable for both temp login (FMTM token) and data extract generation (raw-data-api). This isn't possible. We either need two token variables, one for FMTM temp login and one for raw-data-api, or alternatively we may need to remove OSM from the FMTM temp login (to simplify).

I thought I was being smart reusing the service account for both purposes, but in the end it over-complicates it 🤦

**Comment by spwoodcock** [comment]
This is fixed in dev / stage, so I will close it.

The proposal above can be moved into a separate issue.
