### ISSUE TITLE
Create initial design documents

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#15]

**Comment by krtonga** [comment]
See https://github.com/hotosm/fmtm/issues/16:

Designs
- [Mapper flow](https://www.figma.com/proto/C1fKGnYiTdsTTxrRSobE11/HOT-FMTM?node-id=1%3A21&starting-point-node-id=1%3A21)
- [Web/Management flow](https://www.figma.com/proto/C1fKGnYiTdsTTxrRSobE11/HOT-FMTM?node-id=780%3A2772&scaling=scale-down&page-id=0%3A1&starting-point-node-id=259%3A779&show-proto-sidebar=1)

**Comment by krtonga** [comment]
Roadmap for Q1 and Q2
- [FMTM Roadmap - HOT Internal](https://docs.google.com/document/d/1idwk8PzezDsod7W9xrsXydBuLPtm9uYHfh56ZCENmik/edit?usp=sharing)
