### ISSUE TITLE
Unable to view tasks list on infographics page

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1511]
**Describe the bug**
When user fills submissions and goes to infographics page, the list of tasks are seen on bottom left. But when users refresh the page, the tasks are not visible 

**To Reproduce**

1. Go to 'project page'
2. Click on 'infographics '
3. refresh the page.'
4. See error on tasks list 

**Expected behavior**
The list of tasks should be seen even after refreshing the page

**Screenshots**
Before
![image](https://github.com/hotosm/fmtm/assets/97273021/070cd300-42c6-4be8-8b3c-3309b8feb950)

After
![image](https://github.com/hotosm/fmtm/assets/97273021/52d9b0a9-170b-4b65-8cff-d9cc51f1ad09)

**Comment by Sujanadh** [comment]
related to #1508
