### ISSUE TITLE
Building footprints missing on scanning the tasks on odk collect

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1512]
**Describe the bug**
When i see buildings on fmtm there are dense buildings but when i load same task on odk only few buildings are seen and few are missing. 

**To Reproduce**

1. Go to 'project page'
2. Click on 'any task to see building footprint'
3. Scan the QR and see the same task footprint on odk collect mobile application

**Expected behavior**
The number of buildings on FMTM project detail page should match exactly with building footprint on odk collect. 

**Screenshots**

![Screenshot_2024-05-07-16-42-44-27_171725cd2e369f62c287134214eaed67](https://github.com/hotosm/fmtm/assets/97273021/a8411d5f-0f12-4459-b4f9-d4b47ec814d0)
![image (9)](https://github.com/hotosm/fmtm/assets/97273021/5236e435-408b-433a-8635-e55f96d64ec4)

**Comment by Sujanadh** [comment]
related to #1510
