### ISSUE TITLE
Not all tasks are loaded on infographics page

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1520]
**Describe the bug**
I created a new project and see the total number of buildings were 8 but when i go to infographics page and see all the number of features, few tasks ids were missing. On inspecting on response, all tasks ids are available on the API. 

**To Reproduce**

1. Go to 'project page'
2. Click on 'infographics
3. Scroll down to 'list of tasks id right to map'

**Expected behavior**
List of all tasks ids should be visible on the list. 

**Screenshots**
![image](https://github.com/hotosm/fmtm/assets/97273021/bb1af0c6-d7a5-40d6-a2ee-31b112a827fc)

**Comment by NSUWAL123** [comment]
This is not a bug or an issue: 

Description:
for example:
Currently, expected and submission count is being calculated using the response from `/statuses` API. **The statuses API only contains buildings statuses.**
So, if a task has no features, the API would also have no status of buildings which is expected resulting to no data for that task i.e. no expected & submission count card seen in the UI.

Screenshot:
Sudden jump from task 2 to 7
![image](https://github.com/hotosm/fmtm/assets/81785002/e9f9f489-b9d8-4d83-8204-abd575d0b102)

No features in task 3,4,5,6
![image](https://github.com/hotosm/fmtm/assets/81785002/02494ece-e3d4-4278-9715-c9a612077657)

CC: @manjitapandey @spwoodcock @Sujanadh

**Comment by spwoodcock** [comment]
Great observation!

For next release, should we still display the task card, but display some text like:

"Task has no features"

?
