### ISSUE TITLE
Used JWT-based authentication regardless of OAuth method

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1539]
**Is your feature request related to a problem? Please describe.**

- For a while we used OSM login only, via osm-login-python.
  - This library takes the OAuth token from OSM, encrypts it with a SECRET_KEY, then provides it to the user.
  - This encrypted token can only be decrypted by osm-login-python (using the same SECRET_KEY), in FastAPI we deserialise the token to OSM details (username, profile picture, etc) via a `login_required` dependency (Depends).
- We have since added a temporary authentication for mappers.
  - This also uses OSM authentication, but instead uses a service account `svcfmtm`.
  - Each user with a temporary login token is technically logged in as svcfmtm.
  - This works fine, but isn't ideal for self-hosted FMTM instances, requiring additional work to set it up (creating an OSM service account, getting the OAuth token).
- It might be better to encapsulate the OSM login in a standardised JWT-based authentication, which will remain the same regardless of login method.
  - This way we could also add other login providers (e.g. Google), although is not preferred as login methods outside of OSM do not provide the user attribution for their edits.

**Describe the solution you'd like**

- Implement JWT-based authentication using [pyjwt](https://github.com/jpadilla/pyjwt/).
- ES256 would be the preferred encrpytion algorithm due to smaller size and better security than RS256 (also asymmetric, pub/priv key pair). However, pyjwt has limited curves available for ES256 (secp256k1 only), which is quite limiting. RS256 is acceptable for our use case, secure until at 2030-2050 with computing advances.
  - First a keypair must be generated:
      ```bash
      $ openssl genrsa -out private_key.pem 4096
      $ openssl rsa -in private_key.pem -pubout -out public_key.pem
      ```
  - The algorithm can be specified in pyjwt: https://pyjwt.readthedocs.io/en/latest/usage.html#encoding-decoding-tokens-with-rs256-rsa
- The payload should include the following [claims](http://www.iana.org/assignments/jwt/jwt.xhtml):

```json
{
"sub": "fmtm|userid",  // iss claim not required if included as unique key 'fmtm|' in sub
"aud": "fmtm.hotosm.org",  // change domain for each instance
"iat": "1716679595"  // UTC Unix token issue time (seconds from the Unix epoch)
"exp": "1716683195",  // UTC Unix token expiry time (seconds from the Unix epoch)
"name": "username (i.e. OSM username)",  // public claim
"email": "email if provided",  // public claim
"picture": "profile picture",  // public claim
"role": "role enum value for FMTM",  // private / custom claim
}
```

- The token should be stored in a secure httpOnly samesite=lax cookie, as currently implemented.
- The requirement to provide a service token for `svcfmtm` temporary auth can be removed in favour of a JWT token of reduced scope:

```json
{
"exp": "1716683195"  // Set to 1 day expiry from grant date?
"temp": true,  // Add additional private claim to specify it's a temp token and handle differently
}
```

- For the generation of the token when OSM login is used, we should verify the OSM login is successful, then if yes provide the custom JWT (it does not contain the OSM OAuth token). If the OSM login fails, do not provide a JWT token.
- We can use this same approach for other providers too - if login is successful for the provider, return our custom JWT with an expiry, else return no token.

**Describe alternatives you've considered**

- The `python-jose` package is outdated and no longer recommended.
- Using a provider like Auth0 to handle this - it's open source with a generous free tier, but rolling our own solution gives more control and less issues if we exceed the free tier / the licensing changes.

## Additional context

- The introspect endpoint can be refactored to simply use the "exp" claim, which tell us if the token is expired or not (i.e. if the user is still logged in). The 'refresh time' should be determined by the **cookie expiry**, so if the cookie is received, then the JWT should be renewed automatically.  
- To use JWT auth an additional env variable is required: `AUTH_JWT_KEY`, which is a private key in the keypair.
- This variable can also be used for services like electric-sql too.

**Comment by manjitapandey** [comment]
I am still encountering the issue the issue of needing to
