### ISSUE TITLE
Better handle PMTile offline map paths

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1552]
**Describe the bug**

- Currently `state?.project?.projectOpfsBasemapPath` is only set when the user clicks the lightning bolt to download/cache PMTiles in the browser.
- When the project is changed (going to project details), the value of `projectOpfsBasemapPath` is not updated. It uses the previous value.
- I added logic to not load the basemap if the projectId does not match the project id in the OPFS file path, but this is a hacky workaround.

**To Reproduce**

- Download a PMTiles basemap.
- Set a console.log on the `projectOpfsBasemapPath` param in `ProjectDetailsV2`.
- Click the bolt to cache in browser.
- Change to a different project.
- See the console log of the path from the previous project.

**Expected behavior**

- Remove the existing logic, including the `projectOpfsBasemapPath` param.
- Instead, when the project details page loads, search the OPFS storage for a directory matching the project ID.
- If there is a pmtiles archive under the project id directory, then we should grab and display it.
- If there is no record in the OPFS for the project, we should not display any basemap.

**Comment by spwoodcock** [comment]
Moved to the mapper app milestone.
No point fixing this on the current project details page, as it will be moved to the mapper app.

**Comment by manjitapandey** [comment]
so can we close the issue for now?

**Comment by spwoodcock** [comment]
It's not done on the mapper app yet!

Next on the agenda 😁

I'll fix the dev deploy today so you can actually see progress 👍
