### ISSUE TITLE
Minor UI misalignment after frontend dependency upgrades

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1566]
**Describe the bug**

- After frontend dependency upgrade to latest versions, including React 19, a few components on the infographics page are misaligned (likely from recharts 2.13.0-alpha.4 upgrade):

![image](https://github.com/hotosm/fmtm/assets/78538841/6d98a86a-553e-4d55-ba3c-549af76bfa24)
![image](https://github.com/hotosm/fmtm/assets/78538841/87a6cb92-9138-405d-809f-780b1c5dfdf9)
![image](https://github.com/hotosm/fmtm/assets/78538841/7dbdfd78-1ec3-4437-8a6a-1ab5a6e84ddc)

**Expected behavior**

- The components are correctly aligned.

**Additional context**

This is the final bugfix before 2024.3.1 release and is highest priority 👍

**Comment by manjitapandey** [comment]
The heading of total contributors table is missing. 
Also the header of submission table is missing.

**Comment by manjitapandey** [comment]
the actions on submission table should be freezed.

**Comment by spwoodcock** [comment]
This is strange.
Are these new issues that have popped up after Nishits recent PRs?
Or did they always exist, but were never flagged?

If somehow the recent PRs have caused new issues, then something is seriously wrong & I agree we should probably come back to this at some point.

But if they always exists, then could we do a thorough scan for all of the issues and ensure Nishit knows about them all, so we can do another PR on it?

**Comment by NSUWAL123** [comment]
@spwoodcock, it seems that the cleanup that you had done on the table component is leading to unexpected broken things like the header missing and the actions header not fixed.
Here you removed the classname which led to this.
![image](https://github.com/hotosm/fmtm/assets/81785002/f1aa66a6-4b53-482f-bc1f-235827248292)

And I really think that we should once make sure that everything is working as intended before we push the code.

**Comment by spwoodcock** [comment]
Damn, my apologies there 🙏

A symptom of working on too many things and not checking thoroughly enough no doubt 😅

This really hammers home how crucial comprehensive testing is.
I think the work on frontend tests with Playwright got dropped, but I will try to pick it up myself in the near future.
