### ISSUE TITLE
statuses API isn't update after submissions.

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1576]
**Describe the bug**
The statuses API is not updated after submissions. This causes expected submission count on project infographics not to increases even after adding submissions. Also the colour of entity is not updated, after submission due to the same issue. 

**To Reproduce**

1. Go to 'project details page'
2. Click on 'a building footprint and fill form on odk''
4. see the features colour isn't updated accordingly.
 Also
 
 1. Go to 'infographics page'
2. see error. 

**Expected behavior**

- [ ] colour of entity should be updated after submission.
- [ ] expected submission count on project infographics should increases after submissions

**Screenshots**
![image](https://github.com/hotosm/fmtm/assets/97273021/c0b392ca-adb0-495b-aa4f-a52021d6329b)

**Comment by spwoodcock** [comment]
Do you think there should possibly be a refresh button on the infographics page?
We could add polling or websockets, but a much easier workflow it:
- User goes to infographics page
- API endpoints are called that are required for the page data
- If the user wishes to update the data while on the page, then there is a refresh button

**Comment by Sujanadh** [comment]
> Do you think there should possibly be a refresh button on the infographics page? We could add polling or websockets, but a much easier workflow it:
> 
> * User goes to infographics page
> * API endpoints are called that are required for the page data
> * If the user wishes to update the data while on the page, then there is a refresh button
> 
> As for the building colours, this will mostly be addressed on the mapper frontend, as it's specific to that.

I think yes, we need refresh button in the infographics page like we do in the submission table, we cannot expect user to go back to page and load the infographics page to update the data

**Comment by NSUWAL123** [comment]
It seems that the entity status is not updated although submission has been done.

**Comment by manjitapandey** [comment]
I don't think the refreshing of page solves this issue, the submission count on left of the map doesn't increase this way. Only the form submission graph is updated. 
For now, i submitted few forms but the submission count of that task isn't updated.

**Comment by spwoodcock** [comment]
Could the nesting of the status field under the `essential` group possibly be the issue? 

The same as the task_id field that is there too!

It could be worth testing deleting the two rows that wrap them in the `essential` group in the xlsform, then updating the form for the project for testing

**Comment by spwoodcock** [comment]
The issue with `task_id` was due to the `relevant` field in the XLSForm.
When the existing location was selected, the `relevant` field was triggered to false, omitting the `task_id` field.

The nesting under `essential` group was not actually an issue.
Instead to update Entity properties, we must use the `save_to` field to point to the Entity property name.
I think this was made mandatory in ODK Central 2024.1.0!

**Comment by spwoodcock** [comment]
The statuses are now updated with latest fix - building colours change:

![image](https://github.com/hotosm/fmtm/assets/78538841/eb6cd1c0-e078-4f2d-a833-7e06ed91b2b2)
