### ISSUE TITLE
error message during submission download doesn't provide sense if there is no submission on that project

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1582]
**Is your feature request related to a problem? Please describe.**
Failed to download submission geojson message doesn't provide sense if there is no submission on that project 

**Describe the solution you'd like**
If there is no submissions on that project, the error message saying "Failed to download submission geojson " message provide confusion to users. 
We have to come up with different error message to avoid the confusion. like "there is no submission in this project". 
Open to other better options

**Describe alternatives you've considered**
![Uploading image.png…]()

**Comment by spwoodcock** [comment]
I think the screenshot didn't quite upload before submitting - could to reupload for clarity 🙏

**Comment by spwoodcock** [comment]
![image](https://github.com/user-attachments/assets/b19866f6-b8fc-4922-8e90-5ee5f5c9440a)

Agree this could be clearer.

If the API returns no submissions, we should have a different error message: `No submission yet for project`.

**Comment by NSUWAL123** [comment]
@spwoodcock, I have made a PR to display dynamic message generated from the backend. So, I think the backend should generate an appropriate message. i.e. should generate an error if it's related to no submission or other thing as it's impossible on the frontend side.
