### ISSUE TITLE
'Map Feature in ODK' button is not enabled if task area is locked

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1587]
**Describe the bug**

- Encountered this when testing XLSForm updates.
- The 'Map Feature in ODK' button is disabled if the task area is locked for mapping.
- This means if the user locks a task, then clicks a building, the button is still probably enabled to map.
- However, if the task is already locked when they load the page (or refresh), the button is disabled, meaning the user can't map.

> Note that I am using the temporary user for testing this `svcfmtm`, perhaps it's related?

**Expected behavior**

- The 'Map Feature in ODK' button should probably be always enabled, to allow any user to map features.
- As long as the user can see the task is clearly locked, this is probably a good enough check.

@manjitapandey this should also be in 2024.3.1 patch 😄

**Comment by NSUWAL123** [comment]
@spwoodcock, as you said in the issue #1475, only `the 'Map Feature In ODK' button should be disabled if the task is locked alreadyby another user`, I had made that functionality. 

Disable button since task locked by personal OSM account where current logged in account is Temporary account:
![image](https://github.com/hotosm/fmtm/assets/81785002/50b89023-8ccf-4c6a-9387-f2a1c7c81d50)

Enabled button since task locked by personal OSM account which is the current logged in account:
![image](https://github.com/hotosm/fmtm/assets/81785002/c975dcc5-11b5-4e29-a568-7981cede5de1)

So now we shall allow any users even if they locked the task or not? Is this the expected behaviour or we should stick with the previous approach?

CC: @manjitapandey

**Comment by manjitapandey** [comment]
I would agree with us sticking to the previous features. If another user has already locked the task, its not so fit for another user to map the feature within the task. 
Since we are not sure we are doing this feature, so I don't think we should include this feature for this release.

**Comment by spwoodcock** [comment]
Apologies @NSUWAL123 , I don't think the implications had been fully thought through.

I have mapped in the field when people mapped in pairs or small groups. 

I think one user can lock the task, but others should be able to map the features within

**Comment by spwoodcock** [comment]
Next release is fine though, after mire discussions. 

Bring it up in the next meeting & I'm sure Ivan has thoughts 👍

**Comment by spwoodcock** [comment]
We didn't get a chance to discuss fully with all involved, but decided to take the easiest route for now:
- Default to allow all users to 'Map Feature In ODK', i.e. do not disable the button.
- This is because sometimes people map in groups / pair and need access to the button, even if they did not lock the task themselves.
- (task locking/unlocking remains only available to the user who locked originally, or the project admin)

**Comment by NSUWAL123** [comment]
@spwoodcock, could you explain this third point

> task locking/unlocking remains only available to the user who locked originally, or the project admin)

**Comment by manjitapandey** [comment]
Hey @spwoodcock , sorry I may have missed the conversation of weekly meeting yesterday regarding this but can you clarify if this is feedback from any mapping experiences??

**Comment by spwoodcock** [comment]
In both Monrovia and Bali people mapped in groups / pairs. Sometimes with only one phone between them, but sometimes with one phone each.

There are two types of locking:
- Task areas
- Entity features

Task areas should be locked by **one** user, then nobody else can modify the locked status apart from the original locker (or the project admin).

Entity features can be 'locked', i.e. just before a user maps a feature, they click the 'Go To Feature In ODK' button and this locks the task and opens ODK Collect:
- As with the task locking, the locker of the feature should be the only one to unlock it / mark complete.
- However **any** user should be able to initiate mapping of features from within a locked task area (even if they did not lock the task themselves).

Does this clarify?
