### ISSUE TITLE
Create ODK Entity via API instead of XLSForm submission

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1588]
**Is your feature request related to a problem? Please describe.**

- Previous version of ODK Central required a temp form to uploaded specifically for entity registration.
- This was been superseded by API-based Entity creation in v2024.1.0.

**Describe the solution you'd like**

- Update osm-fieldwork to allow creating Entity list (dataset) by API.
- Entity properties should also be set.
- Providing an hardcoded UUID is no longer required during Entity generation, so should we remove this code in osm-fieldwork? (it is autogenerated in Central).

**Comment by Sujanadh** [comment]
it will be good enhancement and much simpler workflow.
