### ISSUE TITLE
Map legend cannot be closed on small screens

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1590]
**Describe the bug**

- If the map legend is open on a small screen, it cannot be closed (I think the close button is displayed outside the map viewport).
- Once open, the legend remains open until refresh.

**Expected behavior**

- Clicking somewhere on the screen that is not on the legend should close the legend.
- This handles the case when the 'Close' button is hidden.

**Screenshots**

![image](https://github.com/hotosm/fmtm/assets/78538841/d5ce3f9e-c9d1-4b04-8999-bd8e5c34eb3e)

**Device (please complete the following information):**

- Laptop 1080p
- Windows
- Firefox

**Comment by manjitapandey** [comment]
The issue is still same, If the zoom level of screen is more than 100%. I can't collapse the legend. I think we need to redesign the legend which is smaller and there is small gap between items. Currently, the legend has occupied more of map section. 
@spwoodcock

**Comment by manjitapandey** [comment]
the slightly modified legend. The gap is reduced to make it look smaller and also can we make the legend reponsive to small screen size. @NSUWAL123 
![image](https://github.com/hotosm/fmtm/assets/97273021/e5a3d717-e586-4360-b1dc-0e24578396dd)

**Comment by NSUWAL123** [comment]
@manjitapandey, yes reducing the gap would be perfect. 
But I have also added a functionality to close the  legend on clicking outside the legend.
