### ISSUE TITLE
 Create wireframes

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#16]
Create some initial wireframes of the User interface.

**Comment by krtonga** [comment]
See designs: 
- [Mapper flow](https://www.figma.com/proto/C1fKGnYiTdsTTxrRSobE11/HOT-FMTM?node-id=1%3A21&starting-point-node-id=1%3A21)
- [Web/Management flow](https://www.figma.com/proto/C1fKGnYiTdsTTxrRSobE11/HOT-FMTM?node-id=780%3A2772&scaling=scale-down&page-id=0%3A1&starting-point-node-id=259%3A779&show-proto-sidebar=1)
