### ISSUE TITLE
task_history.action is incorrectly updated to 'RELEASED_FOR_MAPPING' when a task is locked

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1605]
**Describe the bug**

- When a task is locked via the frontend, the database value in `task_history.action` is updated to `RELEASED_FOR_MAPPING`.
- This is either a frontend or backend issue, incorrect use of an enum value. I think a value of `0` is used when we probably need to pass `1` to lock the task.

**To Reproduce**

- Lock a task
- Check the db

**Expected behavior**

The task_history action value is updated to `LOCKED_FOR_MAPPING`.

**Screenshots**

![image](https://github.com/hotosm/fmtm/assets/78538841/dd27a41f-14f6-4512-9822-72d9ba33ca27)

As you can see in the screenshot, the action_text is correct, but the action value is wrong.

**Comment by manjitapandey** [comment]
I am still having this issue of not being able to mark task as more mapping needed during task validation. Are we on same issue or i understood the issue differently. 
unable to update task error message is shown with 500 error on network panel. View image
![image](https://github.com/hotosm/fmtm/assets/97273021/7701635e-8c34-4225-a83f-5e540f9b7473)

**Comment by spwoodcock** [comment]
The PR needs to be merged first I think 😄

**Comment by spwoodcock** [comment]
Let us know if PR 1618 fixed this @manjitapandey 👍

**Comment by manjitapandey** [comment]
I am restricted to test this issue because of #1657

**Comment by manjitapandey** [comment]
![image](https://github.com/user-attachments/assets/81e118fb-19dd-4f32-976b-2b1a96d9b880)

Encountered an issue while the task is validated. The pop-up still shows locked for validation. The state of pop-up is not updated. 

cc: @spwoodcock , @NSUWAL123
