### ISSUE TITLE
Add functional pytest tests for main mapping endpoints

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1614]
**Is your feature request related to a problem? Please describe.**

Key endpoints for mappers are:

- [ ] ~GET auth/introspect~ not tested as requires frontend to handle cookies etc
- [x] GET projects/summaries
- [x] GET projects/{project_id}
- [x] GET projects/{project_id}/entities/statuses
- [x] GET tasks/{task_id}/history
- [x] POST tasks/{task_id}/new-status/{status_number}
- [x] POST projects/{project_id}/entity/status

**Describe the solution you'd like**

Write tests for the above endpoints.

**Comment by azharcodeit** [comment]
This issue will be resolved once the rest of the endpoints are covered with tests that require an access token:

- GET authentication/introspection 
- POST tasks/{task_id}/new-status/{status_number} 

As soon as the access token is figured out, I will prepare the corresponding PRs. 🚀

**Comment by spwoodcock** [comment]
If the introspect one takes a while to work out, then don't worry about it for now.

We can probably more easily handle the login stuff via Playwright including the frontend too.

To test as backend only I believe it would require setting DEBUG=False on the API and also updating the OSM redirect URL to go to the backend and not the frontend
