### ISSUE TITLE
unable to view the commented message during submission validation

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1617]
**Describe the bug**
During the submission validation, I can post the comment on individual submission but there is no place for users to view those submissions. 

**To Reproduce**

1. Go to 'submission table page'
2. Click on 'tick icon on right of each submission to comment'
3. but the comment are not visible anywhere

**Expected behavior**
The comment section should be added on submission details page to view the comments on those submission. 

**Screenshots**
![image](https://github.com/hotosm/fmtm/assets/97273021/3e98f157-3c05-449d-9333-ce732d06eb05)

**Comment by manjitapandey** [comment]
blocked by : #1694

**Comment by spwoodcock** [comment]
Let's use task comments, so this will be a task history entry of type COMMENT, but to distinguish it as a **submission comment** we can have the comment start with `|SUBMISSION|`.

Then when we load the comments on the frontend we can split out these comments into a separate array. 

We could possibly update this in the future to have a separate action `SUBMISSION_COMMENT`

**Comment by manjitapandey** [comment]
submission comment on the submission instance page 
On the submission instance page, user should be able to add comment for that specific submission. The submission comment would be posted from this very page. But the question would be where and how to visualise the submission comments posted here. The UI I have thought was to visualise it on submission details page as posted in image above. But Sam's suggestion was to view submissions comment on project detail page comment section by providing the entity id. 
Let's wait for @spwoodcock confirmation before we move ahead.

**Comment by spwoodcock** [comment]
I think it's fine as you suggested Manjita - submit and view on the submission page
