### ISSUE TITLE
As a project admin, I want to draw or upload my own tasks

### ISSUE THREAD

**Issue by emi420** [hotosm/fmtm#1621]
**Is your feature request related to a problem? Please describe.**

When creating the tasks, it would be really useful to have the possibility of drawing my own tasks or uploading a GeoJSON. This will solve all these situations where the splitting algorithm or "divide on square" doesn't fit the needs of the project. For example if I want to map houses that are on water, or several hamlets, etc, or if I just want to distribute tasks differently for some reason.

**Describe the solution you'd like**

I would like the option to draw tasks one by one or to upload a GeoJSON with a MultiPolygon with all the tasks.

**Describe alternatives you've considered**

An alternative right now is to create a project for each task.

**Comment by spwoodcock** [comment]
It's actually already possible 😉

Upload a multipolygon or featurecollection as the AOI then select the middle option during task splitting.

But this does suggest it's not intuitive to do, so we should probably have better prompts in place!

**Comment by emi420** [comment]
I've tested this and works good! yes, you're right that is not so intuitive, but that will be another issue.

Thanks @spwoodcock ! I'll close this one.
