### ISSUE TITLE
Bulk upload entities instead of pooling requests

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1628]
**Is your feature request related to a problem? Please describe.**

- Currently we pool requests to upload entities.
- This is fine for locally bundled ODK Central, but performance is pretty bad on remote instances, due to multiple API calls.
- There is now support to bulk upload Entities via the Central API (either via JSON or CSV).

**Describe the solution you'd like**

- Add support for bulk uploading Entities in osm-fieldwork.OdkCentralAsync (or .OdkCentral).
- Use this new functionality in FMTM, for hopefully a single API call.

**Additional context**

This was only made possible due to recent ODK Central upgrades.

**Comment by Sujanadh** [comment]
https://docs.getodk.org/central-api-entity-management/#creating-entities
adding this link here.

**Comment by spwoodcock** [comment]
Duplicate of #1588
Closing.
