### ISSUE TITLE
Strip out z dimension on geojson uploads

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1629]
**Describe the bug**

- We don't need z dimension in any of our geojsons.
- Some software includes this in coordinates, e.g. part of a polygon: `[[54, 45, 0], [[55, 45, 0]]]`

**Expected behavior**

- We should remove the z dimension somewhere in `postgis_utils` and try to standardise all geojson usage.

**Comment by Sujanadh** [comment]
@spwoodcock  can you provide me geojson having z coordinates ? that will be great help :pray:

**Comment by spwoodcock** [comment]
I actually got this requirement from a geojson you sent me 😄 

[2024-07-03_Kroo_Bay_AOI.geojson.txt](https://github.com/user-attachments/files/16108392/2024-07-03_Kroo_Bay_AOI.geojson.txt)

I was never aware the z dimension was included in the geojson spec!

**Comment by Sujanadh** [comment]
Oh really didn’t quite look into those coordinates 😂

**Comment by spwoodcock** [comment]
Closing, this is handled by standardised GeoJSON parser
