### ISSUE TITLE
Refine odkcentral setup for development deploy

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#163]
Two issues:
- It would be good to automatically init the admin user for odkcentral when it start, without having the user to enter the commands to create a user and elevate permissions.
- We need to have the option of starting without odkcentral (for external odkcentral setups).

To fix:
- Init the admin user, if using local odkcentral.
- Allow the options for the user to use an external odkcentral, disabling the local odkcentral startup.

**Comment by mohammadareeb95** [comment]
I would like to try this out. Can you please provide some more reference? Thanks

**Comment by spwoodcock** [comment]
Hi @mohammadareeb95, thanks for contributing!

### Issue 1 is in two parts:

**a)** Simplify ODKCentral API Dockerfile, removing manual database variable injection.

I recently made a PR to ODKCentral that allows environment variables to be passed for the database credentials (https://github.com/getodk/central/pull/389). The variables are DB_HOST, DB_USER, DB_PASSWORD, DB_NAME.

The whole section https://github.com/hotosm/fmtm/blob/ae5cb0651b0e979e55a613e51e04d1c69ef2f82e/odkcentral/api/Dockerfile#L59 could be removed from the API Dockerfile, and environment variables passed during ODKCentral start instead.

**b)** Override entrypoint for the ODKCentral API Dockerfile.

Currently we need to run two commands on first API start, to create an ODKCentral user and promote them to admin: https://github.com/hotosm/fmtm/wiki/DEV-2.-Backend#1b-setup-odk-central-user

We need to look into the ODKCentral docs to find a way to do this without requiring a prompt (e.g. with password directly on command line).

Then we could create a new entrypoint for the Dockerfile, which inits the admin user, then **exec**s the existing entrypont:
"./wait-for-it.sh", "${CENTRAL_DB_HOST:-central-db}:5432", "--", "./sub-db-vars.sh"


### Issue 2 is simpler

We just need a way to run `docker-compose up -d` with an option for not running ODKCentral and the additional proxy.

One way to solve this could be with a separate docker compose file that doesn't have the sections included (e.g. docker-compose.noodk.yml).

**Comment by mohammadareeb95** [comment]
Thanks for the explanation @spwoodcock,:smile: I would like to give this a try.

**Comment by mohammadareeb95** [comment]
FROM node:12-slim
    
    WORKDIR /app
    
    COPY package.json yarn.lock ./
    
    RUN yarn install --frozen-lockfile --non-interactive --production=true && \
        yarn cache clean
    
    COPY . .
    
    ENV NODE_ENV production
    ENV PORT 80
    ENV REDIS_URL redis://redis:6379
    ENV SESSION_SECRET your-session-secret
    ENV DB_HOST central-db
    ENV DB_USER central_admin
    ENV DB_PASSWORD admin_password
    ENV DB_NAME central
    ENV ADMIN_EMAIL admin@example.com
    ENV ADMIN_PASSWORD admin_password
    
    EXPOSE 80
    
    COPY entrypoint.sh /
    RUN chmod +x /entrypoint.sh
    
    ENTRYPOINT ["/entrypoint.sh"]
    CMD ["node", "src/index.js"]

In this Dockerfile, a new script called entrypoint.sh is added that initializes the admin user and then runs the original entrypoint command. The entrypoint.sh script will be something like this:
      #!/bin/bash
      
      set -e
      
      # Create admin user
      node src/bin/add-admin-user.js
      
      # Run original entrypoint command
      ./wait-for-it.sh ${CENTRAL_DB_HOST:-central-db}:5432 -- ./sub-db-vars.sh
      
      exec "$@"

This script
-  first initializes the admin user using the add-admin-user.js script
- then runs the original entrypoint command that waits for the database to be ready and substitutes database variables using wait-for-it.sh and sub-db-vars.sh.


To use this updated Dockerfile, you can build the image with:
`docker build -t odkcentral-api .`

And then start a container with:
`docker run -it --rm odkcentral-api`

This will automatically initialize the admin user and start the ODKCentral API server.

**Comment by mohammadareeb95** [comment]
@spwoodcock what do you think about this?

**Comment by spwoodcock** [comment]
Hi @mohammadareeb95, thanks for the input.

The dockerfile as above won't do anything, as we need a dockerfile for the ODKCentral backend/api:https://github.com/getodk/central/blob/master/service.dockerfile

The existing dockerfile we have is fine, we just need to update the entrypoint - the entrypoint script you included should work, but where does the add-admin-user.js come from?

I don't know there was a JS script for this, but if so then it's also an option (instead of via command line).

It would be good to remove this RUN command at the same time: https://github.com/hotosm/fmtm/blob/01c45990a1a73c5d230312ad3feaa0c667e28143/odkcentral/api/Dockerfile#L61

Then set the environment variables that ODKCentral requires from our database variables. https://github.com/getodk/central/blob/0502d5397faf42b641a16487dbcdea10de418dea/docker-compose.yml#L37

Is this doesn't make sense, no worries - I will get around to it when back from holidays - it should be a quick edit.

**Comment by spwoodcock** [comment]
The ideal setup for this would be with a remote build, directly from the odkcentral repo (so we don't have to maintain our own).

```yaml
  central:
    image: "quay.io/hotosm/odkcentral-api:latest"
    build: https://raw.githubusercontent.com/getodk/central/master/service.dockerfile
    container_name: central_api
    depends_on:
    .....
```

The issue is that https://github.com/getodk/central uses submodules, and copies files from those submodules in the dockerfile (there is no way to init the submodule prior to build).

I will update our ODKCentral API config as planned for development / staging.

For production, I plan to use a standalone version of ODKCentral, installed and accessible from odk.fmtm.hotosm.org.
