### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#164]
These are the documentation tasks for our Outreachy intern.

**Comment by mohammadareeb95** [comment]
Can i work on this?

**Comment by srishtig2412** [comment]
Hello, I am an outreachy applicant. Can you assign this to me?

**Comment by Biswajit-Behera** [comment]
Hi, I want to contribute to this issue as Outreachy applicant. Can you assign this to me?

**Comment by Roseford** [comment]
Hi @robsavoye @petya-kangalova,
I sent a mail about updating an outdated documentation, I would like to begin working on this. Could you let me know if I should go ahead or if it is a lost cause? :)

**Comment by Roseford** [comment]
Hi @robsavoye @petya-kangalova,
I just created a PR, please have a look at it. Thanks.

**Comment by Roseford** [comment]
Hi @spwoodcock ,
I just create a PR , please have a look at it. Thanks.

**Comment by petya-kangalova** [comment]
Hi all-  this is not the detailed  issue but an epic @robsavoye  has created.  As mentioned previously we don't assign one issue per person- Outreachy applicants can select and start working on an issue.

@Roseford as good practice, please do link the PRs you have created here as well.

@mohammadareeb95 @Biswajit-Behera @srishtig2412 let me know if that makes sense?

**Comment by Biswajit-Behera** [comment]
> Hi all-  this is not the detailed  issue but an epic @robsavoye  has created.  As mentioned previously we don't assign one issue per person- Outreachy applicants can select and start working on an issue.
> 
> @Roseford as good practice, please do link the PRs you have created here as well.
> 
> @mohammadareeb95 @Biswajit-Behera @srishtig2412 let me know if that makes sense?

Ok👍 
Thankyou for your response

**Comment by Roseford** [comment]
#203

**Comment by Balofire** [comment]
https://github.com/hotosm/fmtm/pull/213#issue-1628263416 
https://github.com/hotosm/fmtm/pull/204#issue-1626059564

@robsavoye @petya-kangalova please do these PRs also count as improving documentation. I thought I should link them here too

**Comment by Roseford** [comment]
Hi @robsavoye 
Now we have a new branch named development where PR are merged first, do you think I should update the documentation on how to  make the development branch the upstream branch so that contributors would be able to pull from there without hassle.

**Comment by robsavoye** [comment]
The Outreachy program is now over. Future documentation changes will be other issues.
