### ISSUE TITLE
Internal server Error trying to create project using multipolygon 

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1640]
**Describe the bug**
Trying to create project using multipolygon and custom data extract , I encountered 500 internal server error on the final step clicking on submit button. 

**To Reproduce**

1. Go to 'create project'
2. Upload multipolygon
3. Upload custom data extract as below
4. Generate osm data extract
5. choose any type of task splitting methods
6. See error

**Expected behavior**
The project should be created successfully. 

**Screenshots**
![image](https://github.com/hotosm/fmtm/assets/97273021/9f8a1629-3ada-4bd5-b4d5-169b499d26aa)

**Additional context**
[AOI_Splits.zip](https://github.com/user-attachments/files/16158751/AOI_Splits.zip)
[project_form_36.xls](https://github.com/user-attachments/files/16158753/project_form_36.xls)

**Comment by Sujanadh** [comment]
I see there is a problem when using multipolygons to select choose area as task; we won't have a single polygon as an AOI so we cann't save the whole tasks as the project AOI, We need to dissolve those polygons to create a single AOI boundary. So problem comes when disjoint polygons are used, We can split those disjoint polygons by task_splitter passing MultiPolygon without dissolving them, but to save them as an AOI, we need to dissolve them into a single polygon.

Options:
- When splitting using task_splitter we will pass MultiPolygon in the same function(merge_multipolygons) we use
![image](https://github.com/hotosm/fmtm/assets/109404840/986c79d1-ee82-430a-bde1-fb7d35d55e95)


- when creating project, we will dissolve those multipolygons even if they are disjoint into a single aoi, but tasks will be splitted based on two undissolved disjoint polygons.
![image](https://github.com/hotosm/fmtm/assets/109404840/0cc353cd-c2e9-474c-bd19-0dfc02d017b7)
