### ISSUE TITLE
Use `digitization_correct` field from XLSForm during conflation

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1648]
**Is your feature request related to a problem? Please describe.**

Based on our call today, something else we have at our disposal is the `digitization_correct` field in the submission.

**Describe the solution you'd like**

**If** this field is present (first check this, as it may not always be), then:
- If the value is `yes`, and then this building should take precedent over the OSM one (if there are conflicts).
- If the value is `no`, then the geometry should be flagged during the conflation review step.

**Comment by Sujanadh** [comment]
isn't checking digisation_correct similar to checking if the geometries are equal? if it is digitally correct then their geometries will be equal.
Should I check this key after checking if they are equal? or if it is digitized correctly then we don't have to check if they are equal or not.

**Comment by spwoodcock** [comment]
No they are two different things:
- If the data extract geometry matches the OSM geometry, then we know there is no conflict with what is in OSM.
- But in some cases the geometry could not match what is there in reality:
  - If the data extract is different to OSM (a conflation issue), but the user specifies the `digitization_correct=yes`, then we take the data extract geometry as priority.
  - If the data extract is different to OSM (a conflation issue), but the user specifies the `digitization_correct=no`, then we either take the newly provided geometry if present, or need to remap the feature.
  - If the data extract is the same of OSM (no conflation issue), and the user specifies the `digitization_correct=yes`, then there are no issues.
  - If the data extract is the same of OSM (no conflation issue), and the user specifies the `digitization_correct=no`, then we either take the newly provided geometry if present, or need to remap the feature.

**Comment by Sujanadh** [comment]
so what I think is:
- If the data extract is different to OSM (a conflation issue), but the user specifies the digitization_correct=yes, then we take the data extract geometry as priority. From backend we will conflate it using submission extract.
- If the data extract is different to OSM (a conflation issue), but the user specifies the digitization_correct=no, then we either take the newly provided geometry if present(what do you mean here? where will we get newly provided geometry? you mean edited geometry while conflating by validator based on the drawing or any material received from submission) default to the OSM geometry if none are provided (it's the best we have, but we probably need to remap at some point to be sure). In this case we will return osm geometry and allow user to edit the geometry.
- same thing to last point

**Comment by Sujanadh** [comment]
if there is partial overlap between data extract and osm feature we will want the latest data from osm right?
in this case , for both correct and incorrect digitization we will return osm feature instead of data extract?

**Comment by spwoodcock** [comment]
You are right, there is no newly provided geometry (geopoint) if the user selects a building!

![Screenshot_20240717-074931.png](https://github.com/user-attachments/assets/ab4dc2f9-38f3-4f43-8205-d101c5eb950d)

There is also this case to consider, if the user selects that the building doesn't exist, we want to flag it for deletion

**Comment by spwoodcock** [comment]
If there is a partial overlap then we return both geoms for the user to decide - manually resolve the conflation

**Comment by spwoodcock** [comment]
I added this related issue

https://github.com/hotosm/fmtm/issues/1660

**Comment by Sujanadh** [comment]
> If there is a partial overlap then we return both geoms for the user to decide - manually resolve the conflation.
> 
> They should have the same feature id so we can flag them as the same building needing resolution

if partial overlap and digitization_correct = true , then return both buildings. If digitisation_correct = false, then? return one? as it needs boundary edit

**Comment by spwoodcock** [comment]
If there is a partial overlap we would normally return both buildings for the user to select.
But because the user already specified `digitization_correct=yes`, we can probably go ahead and accept the new building geometry, returning one building only.

If `digitization_correct=no` then we need to return both for the validator / project admin to decide which one to take
