### ISSUE TITLE
Create FMTM Tutorial

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#165]
Create a tutorial on how to use FMTM for a mapping campaign.

**Comment by Roseford** [comment]
Hi @robsavoye @petya-kangalova,
I would love to work on this, is there a particular format you would like the tutorial to be in?

**Comment by Ndacyayisenga-droid** [comment]
@robsavoye @petya-kangalova where should I include this tutorial ?

**Comment by Roseford** [comment]
@robsavoye @petya-kangalova 
I have written a tutorial on how to use the fmtm tool to create a mapping campaign, the link to the file is attached below
https://docs.google.com/document/d/1KMtCgIXCEulpDs19hkXe4bY-16Y9idjRghEc8Y981s4/edit?usp=sharing

**Comment by Roseford** [comment]
Hi @robsavoye,
I have created an FMTM tutorial here https://github.com/Roseford/fmtm/blob/fixing_issues/docs/Mapping-Campaign-Using-FMTM.md
Please check it out.

**Comment by Roseford** [comment]
Hi @spwoodcock,
I have created the FMTM tutorial at https://github.com/hotosm/fmtm/blob/main/docs/Mapping-Campaign-Using-FMTM.md do you think it would be a good idea to close this issue.

**Comment by spwoodcock** [comment]
Looks good @Roseford! It just needs to be added to the _Sidebar.md to be visible - I'll update it when I'm back at my computer and close this.

**Comment by suhana832** [comment]
can you assign this task to me ?

**Comment by suhana832** [comment]
how many days I have ? to complete this task

**Comment by ivangayton** [comment]
There's no hard time limit! But the first thing would be to reach out to @Roseford who's already been working on this, see what's been done so far, and ask where help is most needed.

**Comment by ivangayton** [comment]
In my view, we could almost certainly use several tutorials, one very comprehensive video style for beginners, one text plus screenshots for more advanced people, and perhaps a slide deck for people trying to deliver the tutorial in person or via video chat.

**Comment by suhana832** [comment]
should I start making it  y my own or collaborate with her ?

**Comment by ivangayton** [comment]
I think you should ask what she prefers! But it also depends what you prefer to do.  Both would be okay; having two different tutorials is not a bad thing, and having one built by collaboration is also great. But it's probably best to first make sure that there isn't too much duplication of effort; it would be a shame for both of you to do the same work separately

**Comment by suhana832** [comment]
I will make sure all of the conditions you mentioned. Thank you ☺️

**Comment by petya-kangalova** [comment]
Hi everyone, thank you for coming in a bit late on this one :) @robsavoye probably we should have given more guidance to people about the tutorial, especially as this specific product FMTM is still in development. Latest version can be accessed here: https://fmtm.hotosm.org/

As @ivangayton  said collaboration is encouraged. 

@suhana832  maybe first looking at what @Roseford  has started. It will be good to start by setting the structure for the tutorial, doing some research from other examples. Types of tutorials and what a good tutorial can capture.

As FMTM is still development- the tutorial will need to be updated and cannot be fully completed.  Let me know if this is helpful.

**Comment by suhana832** [comment]
@petya-kangalova should I still make a new fresh tutorial ?

**Comment by suhana832** [comment]
@petya-kangalova  ,@ivangayton and @robsavoye as this task is assigned to me still. I will continue to work on FMTM tutorial in some new way and as mentioned its not completed fully. I will keep my Tutorial updated as much as I can. but my doubt is can I add it as my contribution and move to next issue or should I keep working on this issue till 3rd April ? kindly reply !

**Comment by robsavoye** [comment]
Most documentation is never actually "finished". :-) Make what progress you can, others may build on it later. Since there was no tutorial, having something is a great start.

**Comment by suhana832** [comment]
hello @petya-kangalova , @robsavoye and @ivangayton have a look at the information I am collecting. I understood the working of FMTM very nicely. 
https://docs.google.com/document/d/1MkUL-WVFi56vlPC4aNMH3kI3wgR4Abp07wib-8CSRXQ/edit?usp=sharing

**Comment by suhana832** [comment]
I will structure the format of  FMTM tutorial and add best possible data.

**Comment by petya-kangalova** [comment]
@suhana832 as per Slack message please link anything you have worked on directly on Github.

**Comment by suhana832** [comment]
Ok : )
Check out the link below

https://docs.google.com/document/d/1MkUL-WVFi56vlPC4aNMH3kI3wgR4Abp07wib-8CSRXQ/edit?usp=sharing_eip_se_dm&ts=64183e80

**Comment by suhana832** [comment]
@petya-kangalova I am working on Tutorial directly , the FMTM website looks uncompleted. I am unable to write steps because some of the options on FMTM website are not working and so I cant assume what they function. Like if I tapped on the logo of HOTOSM then it doesn't load anything about main website. that is why I wanted to talk with you. I will ask rest of the  doubts in the webinar because you said you are busy. kindly reply me.

**Comment by petya-kangalova** [comment]
@suhana832  thank you for linking to the document- it looks like your summary notes from watching the webinar.

It is correct that FMTM is still in development so the tutorial cannot be completed. What you can start with is a suggested structure of how the tutorial needs to look- what information is needed. There are many tutorial for different open source products. Then start to fill with information. @synneolsen  could you link to the slides from the last webinar? The visuals of how FMTM works will be helpful for the tutorial.

**Comment by petya-kangalova** [comment]
Hi @suhana832  yes, once you have worked on the tutorial you can record as contribution.

**Comment by suhana832** [comment]
hello @petya-kangalova maam I have recorded the tutorial url to the contribution. please review it.

**Comment by suhana832** [comment]
https://docs.google.com/document/d/1SkO4xm4GrNRZtAuHP46fMBeWSkHawWLKywi8Q0iyOQc/edit?usp=sharing
@robsavoye and @petya-kangalova this is  link to my document.

**Comment by robsavoye** [comment]
This initial draft of a tutorial needs to be added to the project, and expanded.
