### ISSUE TITLE
Automatically logging off of user while refreshing

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1652]
**Describe the bug**
It may be due to the JWT token we have implemented recently, user is facing problem of automatically logging out of FMTM while refreshing the page after spending more than an hour within FMTM. 

**To Reproduce**

1. Go to 'FMTM'
2. Spend more than an hour on FMTM
3. Refresh the page

**Expected behavior**
The user should be logged in automatically even after refreshing the page. The access token shouldn't be expired so soon. 

**Additional context**
This issue exist on dev server. Please check the development server of FMTM to reproduce the behavior.

**Comment by manjitapandey** [comment]
The issue is very annoying, Have to refresh and log in again every hour. So setting the priority to high.

**Comment by spwoodcock** [comment]
@Sujanadh do you think we should have the login token last 1 day and the refresh token last a week?

We were conservative with the initial setup, but I think user experience is more important than heavily optimised security for FMTM - we aren't a banking app I guess 😆

**Comment by Sujanadh** [comment]
@spwoodcock  that will be resonable to have login token last 1 day

**Comment by manjitapandey** [comment]
The login token is still expiring in less than a day. The issue is not fixed.

**Comment by Sujanadh** [comment]
Is anyone else facing this same issue? But I am not experiencing this issue on the dev server.

**Comment by manjitapandey** [comment]
Yeah tried that. Now It works as expected. Thank you
