### ISSUE TITLE
Support multiple feature selection within single form submission

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1653]
**Is your feature request related to a problem? Please describe.**
I am trying to upload xlsx file where there is the need for selection of more than one feature. The building feature and  road connecting that building. The another case could be selection of main building in case we are surveying associated building.  

**Describe the solution you'd like**
User should be allowed to select multiple features. This increases the use case on FMTM for multiple field surveying scenario. May be we could store the geojson of only the entity we are surveying and in case of main feature, we can just store the feature id. 

**Describe alternatives you've considered**

**Additional context**
This is the user's requirement from the Janakpur field mapping activity. 
[Survey_ready_form (12).zip](https://github.com/user-attachments/files/16230196/Survey_ready_form.12.zip)

**Comment by manjitapandey** [comment]
@Sujanadh , @spwoodcock , need your suggestions on how can we technically achieve this on FMTM.

**Comment by Sujanadh** [comment]
I think we can add geopoint of the main building for the survey of its associate buildings and select the geometry of the associate building.

**Comment by spwoodcock** [comment]
My knowledge of the use case is hazy, but as Sujan says one option and probably the best solution for selecting 'associated' features, is to add a geopoint question in the XLSForm asking the user to 'pinpoint associated feature' on the map.

It is possible to enable `select_multiple_from_file`, but then you would have to distinguish somehow which is the 'main' building being mapped and which is the 'associated'.

If we need the select_multiple capability for something then we can explore this option further.

Otherwise if it's just an issue of form design using geopoints, I think this issue could be closed (maybe we add docs on how to do this)

**Comment by manjitapandey** [comment]
@spwoodcock, the use case here is that user should be able to select associated building as well as the main building which is also present within the same geojson file. Moreover, They also needs to select the road (linear feature) associated with the building from the same geojson. This means we should allow user to select multiple feature. 

> It is possible to enable `select_multiple_from_file`, but then you would have to distinguish somehow which is the 'main' building being mapped and which is the 'associated'.

Exactly, Enabling "Select_multiple_from_file" solves the problem. How do we distinguish which is the main building being mapped and which one is associated.

**Comment by spwoodcock** [comment]
We need to fit around what XLSForms and ODK Collect support, and as far as my knowledge goes we can't distinguish between the geometries using `select_multiple_from_file`.

We could do one of the following:
- Use multiple `select_one_from_file` fields: one of the primary feature, another for an associated feature.
- Provide text or select fields so the user can manually enter which is the primary and which is the associated feature.

As for supporting mixed geometry type - this is something we don't support in FMTM yet and I'm not sure how much effort it would take. In theory I don't see why it would not work (as Entity geometries are simply a javarosa geometry string of any type).

They are two separate issues and should be split 👍 

Is this really a `priority:high` issue that is essential for most users though, or is this an edge case that would be excellent to support, but not the main priority of FMTM?

**Comment by manjitapandey** [comment]
> * Use multiple `select_one_from_file` fields: one of the primary feature, another for an associated feature.

I would go with this option of selecting one from file for multiple times. 
For supporting mixed geometry type, We should definitely create another issue but we need to confirm first, which may take more time. Hence, We could only work on supporting multiple "select_one_from_file" for now.

**Comment by spwoodcock** [comment]
My knowledge of this was hazy previously but I have more clarity now. 

This was a requirement for the Janakpur field survey a while ago too.

We can achieve like this:
- Keep the building selection as we have currently (the main geom)
- Allow the user to create a new Entity list of geometries (from a geojson, we convert to JavaRosa). This will be associated with the project 
- Add a question to select a geometry from the uploaded Entities

Tasks:
- [ ] API to wrap Entity creation functionality
- [ ] update frontend to allow uploading supplementary geojson geometries and provide a dataset name via this API
- [ ] add the select from file question to the form to allow geom selection

We should probably include this in the project creation overhaul!

If we create a stub project first (there is an issue for this), then we can upload as many Entity lists during project creation as we need

**Comment by spwoodcock** [comment]
Work towards this has been done in https://github.com/hotosm/fmtm/pull/1792

It's a simple matter of updating the line here:
https://github.com/hotosm/fmtm/blob/780e7ba730f8511ba92879ff70f2626186df85a2/src/backend/app/projects/project_crud.py#L860
to reference additional Entities on project creation.

For now (until https://github.com/hotosm/fmtm/issues/1790 is addressed at some point), we actually need to pass these addition GeoJSONs through to the `/generate-project-data` endpoint as additional files.

So we need two things still:

- [ ] The UI part to upload a (single) additional GeoJSON, as shown above. We will use the filename to name the Entity list, so should tell the user this (please name your file to describe the feature type you are uploading, e.g. `roads.geojson`.
- [ ] Create a small endpoint `/projects/{id}/additional-entity`:
    ```python
    async with central_deps.get_odk_dataset(odk_credentials) as odk_central:
        await odk_central.createDataset(
            project_odk_id, datasetName="features", properties=fields_list
        )
        await odk_central.createEntities(
            project_odk_id,
            "THE ENTITY NAME",
            entities_list,
        )
    ```
- [ ] Pass the uploaded GeoJSON to this API during the final project creation submit, after task areas have been created and data extract uploaded, but before the `generate-project-data` endpoint is called (this will create the Entity list).
- [ ] Pass the filename (Entity list name) as the `additional_entities` param on `/generate-project-data`. This is a list, so would be `additional_entities: [GEOJSON_FILENAME_WITHOUT_EXTENSION]`.
