### ISSUE TITLE
No easy way for validator to mark task validated. 

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1654]
**Is your feature request related to a problem? Please describe.**
The current workflow is somehow complex for validator. Once the user locks any task for validation from project details page pop-up, they aren't redirected to submission table and validator has no clue on where to validate the submission. 

**Describe the solution you'd like**
The validator should be redirected to submission table with filtered task id, if  they lock any task for validation from project details page pop-up. Moreover, the user should be provided with marking the task validated in the same submission page without them needing to get back to project details page. 

**Additional context**
This improvised the workflow for validator and also help project manager to work with the flow for data conflation. I will also provide the design mark task as validated on submission table page.

**Comment by NSUWAL123** [comment]
As the UI of this workflow was connected to the data conflation UI, I have included this to the data conflation work that I am currently doing

**Comment by manjitapandey** [comment]
It would be better if we could change the term fully mapped on validation page to `Mark as Validated`. 
![image](https://github.com/user-attachments/assets/5e777b4d-48db-4566-8482-1537b65fdc55)
