### ISSUE TITLE
Better handling of digitization_correct field in XLSForm

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1660]
**Describe the bug**

Scenario 1: building does not exist

![Screenshot_20240717-074931.png](https://github.com/user-attachments/assets/c54adb69-e86e-4ad7-96fc-e4631b929af7)

The user has to fill out the form currently, for a non-existant building.

Scenario 2: lumped building

The user cannot specify which part of the building they are mapping.

Scenario 3: split building

The user can mark the other building parts nearby as does not exist (map scenario 2), but should then able to draw the correct polygon

**Expected behavior**

Scenario 1:

The form should be completed immediately. 

This flag will then inform the conflation step to delete the building. 

Scenario 2:

The user should have an optional question to draw the part of the building they are mapping, or a text field comment to describe which part.

Scenario 3:

The user should have an optional question to draw around which buildings need to be grouped, or text field to describe.

**Comment by manjitapandey** [comment]
The solution you present for the scenario 1 contradicts to #1697 , where we have moved the digitization_correct field to the bottom of the form.

**Comment by spwoodcock** [comment]
I think the two issues are incompatible entirely 😅

Do you have any thoughts @ramyaragupathy ?

I know moving the digitisation question to the end was an observed field requirement, but it does mean a workflow like the one proposed here is not possible

**Comment by manjitapandey** [comment]
For now, the existence of building question is set on the begining and more digitization questions are shifted to the end.
