### ISSUE TITLE
Fix .xlsx XLSForm handling and error messages on failed parse

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/fmtm#1667]
Contradicting information on `.xlsx` file format support in custom form upload section. While the error popup informs the format is not supported, a text box right below the `select a form` button informs otherwise.
 
<img width="1234" alt="image" src="https://github.com/user-attachments/assets/0e698e68-2a50-47d3-83c7-66572e23cd34">

cc @NSUWAL123 @spwoodcock @manjitapandey

**Comment by manjitapandey** [comment]
Can you share with me the xlsx file. I have been uploading the same file format but still haven't encountered this type of issue.

**Comment by NSUWAL123** [comment]
This error is generated from the backend from `validate-form` API.
![image](https://github.com/user-attachments/assets/a704a854-4e61-4f8c-980a-66dae0a6add0)

Maybe the form values have some error or some backend issues.

**Comment by ramyaragupathy** [comment]
Here you go @manjitapandey @NSUWAL123 [v3_Bali_Disaster_risk_building_assessment.xlsx](https://github.com/user-attachments/files/16282718/v3_Bali_Disaster_risk_building_assessment.xlsx)

**Comment by spwoodcock** [comment]
Perhaps an error from pyxform library conversion - we did update a patch version of the library, but I would be surprised if it broke something

**Comment by manjitapandey** [comment]
still encountering the issue. 
![image](https://github.com/user-attachments/assets/2b917fef-9033-4deb-bbea-9d98f92db44d)

**Comment by spwoodcock** [comment]
Fixed ready for testing
