### ISSUE TITLE
Improve sharpness of mbtiles output from custom TMS source

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/fmtm#1668]
Using the [5cm imagery we generated using drones](https://map.openaerialmap.org/#/115.58723866939545,-8.446080768503133,17/user/5eb37b4700afed00060e6dfe/66971deb1684770001c33a11?_k=08qcj5
) in Amlapura area of Bali, attempted created a mbtiles for offline access in ODK.

However the output was pixelated and did not match the resolution input. Attaching a screenshot of the output mbtile and the actual image

_screenshot of the 5cm imagery from oam_ | _mbtiles output from fmtm_
------------------------|-----------------------
<img width="944" alt="image" src="https://github.com/user-attachments/assets/da0acf91-a684-4865-8a18-ce7da3cc2c43">|<img width="811" alt="image" src="https://github.com/user-attachments/assets/8b7afb0b-3a4a-40a0-84ea-44d7ff8b54be">

@spwoodcock @manjitapandey @Sujanadh

**Comment by spwoodcock** [comment]
Fixed by osm-fieldwork update
https://github.com/hotosm/osm-fieldwork/releases/tag/0.13.0

Will be installed before next release

**Comment by manjitapandey** [comment]
![Screenshot_2024-07-23-16-42-14-84_171725cd2e369f62c287134214eaed67](https://github.com/user-attachments/assets/040774cc-f401-4fc0-8a46-773f30c9f381)

This is the resolution of mbtiles for now. I guess this has been significatly improved than previous.

**Comment by spwoodcock** [comment]
Depends on if this was tested with a satellite provider or a drone TMS provider.

The image above looks reasonably low resolution, so I imagine this is `esri` or `bing`.
The issue was with drone TMS data that has zoom levels great than 18/19.

I have verified this is fixed though, so all good to close 👍

**Comment by manjitapandey** [comment]
I have tested it with drone TMS provider copying the same TMS layer ramya was using of Bali. So i think we need to reconsider this issue before closing.

**Comment by spwoodcock** [comment]
You tested with the TMS provider and the imagery was still blurry?

**Comment by manjitapandey** [comment]
Yeah the same TMS tile of Bali, The imagery has been improved by still blurry like above.

**Comment by manjitapandey** [comment]
@spwoodcock , any success around this issue. I can also test on other multiple tms layers to validate.

**Comment by spwoodcock** [comment]
mbtile output is working nicely:

![image](https://github.com/user-attachments/assets/6d26b12d-9487-41d4-b44a-0455c17c3c6a)

I'm also checking pmtiles, but mbtiles was the main requirement here for ODK Collect, so closing 👍

**Comment by manjitapandey** [comment]
Yeah, I tested on other mb tiles. The resolution is much higher and satisfactory now.
