### ISSUE TITLE
Frontend task_id is out of sync with db task_id

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1673]
**Describe the bug**

When updating task 9, the popup shows I am looking at task 8:

![image](https://github.com/user-attachments/assets/4f255282-4f22-49e4-874b-adbf44ea2527)

- The backend handling of task_id based on `project_task_index` appears to be correct.
- I think the issue is because the task index starts at `1` to be more user friendly.
- The frontend references the index of the tasks, which will start from `0`:

![image](https://github.com/user-attachments/assets/3972424c-3f91-4abe-8f1d-774ccd79e45f)

![image](https://github.com/user-attachments/assets/fd1c3315-f472-47e3-b895-a1090b484f09)

**Expected behavior**

The task id on the task popup should match the actual task index id from the backend.

**Comment by NSUWAL123** [comment]
@spwoodcock, I think it's working fine. 

Here I have tested with task id of `1260` with task index of 4.

/Project API response:
![image](https://github.com/user-attachments/assets/9c0c5742-01ec-42fb-ac2a-088fb8e210f3)

Post new status and it's response:
![image](https://github.com/user-attachments/assets/bdfb4068-bcd3-42e3-9238-c19a7e88a8db)
![image](https://github.com/user-attachments/assets/16022107-766c-4bad-863a-a0cc72079632)

Task History API fetch:
![image](https://github.com/user-attachments/assets/bce06e65-e6cb-492a-b1c9-1cbc9b6cdeac)
![image](https://github.com/user-attachments/assets/209fda14-1e0d-47c8-b357-789b91103500)

@spwoodcock and @manjitapandey also, could you please confirm from your side too.

And Sam, your `action text` seems to look different from the current action text:
`  "action_text": "Status changed from MAPPED to LOCKED_FOR_VALIDATION by: localadmin",`

**Comment by spwoodcock** [comment]
Thanks for such detail!

I can check this on Monday 👍

I'm testing on the mapper frontend branch, so perhaps it's just an issue on my end. 
I tweaked the action text a bit on the branch.

**Comment by manjitapandey** [comment]
@spwoodcock waiting for your confirmation.

**Comment by spwoodcock** [comment]
This is actually fine 👍 

Perhaps a bug introduced on my local mapper frontend branch, or just a some confusion somewhere - closing!
