### ISSUE TITLE
Zoom to task form view infographics does not load the task

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/fmtm#1675]
While accessing the task list form the `view infographics` page, I chose a particular task number and attmepted to zoom to the task. I was expecting the map to automatically zoom to the specifc boundary, however no action was executed on the map.

![fmtm-zoom-to-task](https://github.com/user-attachments/assets/76d985d7-7af4-4032-9001-a6eab372087d)

I am using a Chrome browser in a mac setup.

cc @spwoodcock @NSUWAL123 @manjitapandey

**Comment by NSUWAL123** [comment]
I exactly replicated the steps that you performed in the same project but it's working for me. Could you again try clicking the `zoom to task` button. 
[Screencast from 19-7-24 11:17:01 पूर्वाह्न +0545.webm](https://github.com/user-attachments/assets/9c969a66-ff77-48da-a27a-e9d1aaffeba1)

@spwoodcock, @manjitapandey, can you also check whether the `Zoom to Task` button works?

**Comment by manjitapandey** [comment]
Works on my device too.
