### ISSUE TITLE
Create test cases for backend API

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#169]
Currently FMTM lacks working test cases. Ideally every endpoint should have unit level test case.

**Comment by spwoodcock** [comment]
Prerequisite #95

**Comment by steph237** [comment]
Greetings @robsavoye and @spwoodcock  I will like to work on this issue please can you throw more light on this

**Comment by biomassives** [comment]
@steph237   there are three endpoints to be tested at odk central that we know about from the api docs below
https://fmtm-api.hotosm.org/docs#/central/list_projects_central_projects_get 

note there are three endpoints listed: GET /central/projects , GET /central/appuser, GET /central/submissions,

**Comment by spwoodcock** [comment]
1. First we need to create a test client for calling our FastAPI endpoints, which we could do as a pytest fixture in tests/conftest.py:

```python
import pytest
from fastapi.testclient import TestClient

@pytest.fixture(scope="session")
def test_client():
    """FastAPI test client for endpoint testing."""
    return TestClient(app)
```
 
2. Then for endpoints which use ODKCentral, we need to also mock the request to it internally, using `requests-mock` (https://pypi.org/project/requests-mock):

e.g.

```python
from backend.config import settings

@requests_mock.Mocker()
def test_list_odk_central_projects(client):
    project_json = {VALID_PROJECTS_JSON_HERE}
    m.get(f"{settings.ODK_CENTRAL_URL}/url/projects", json=project_json)
    response = client.get("/projects")
    assert response.status_code == 200
    assert response.json() == project_json
```

I haven't tested the code above, but it's just an example of what you could do.
Most endpoints require some form of ODKCentral request, but for those that don't, it would be an easy first test (simply using TestClient and validating the response).

**Comment by spwoodcock** [comment]
Decided to use `requests-mock` for ODKCentral API mocking. Closing #95 in favour of this issue.

**Comment by Freedisch** [comment]
@spwoodcock , Is there any update on this issue, I can work on that

**Comment by spwoodcock** [comment]
Hi @Freedisch, there haven't been updates as far as I know, so a contribution (even if just a small start) would definitely be welcome! Thank you 😄

**Comment by robsavoye** [comment]
There are two test cases in the development branch to make sure the testing infrastructure worked. Now that the backend API is stable, it'd be a great addition to add more test cases.

**Comment by spwoodcock** [comment]
Perfect, things have progressed more than I thought - thanks Rob!

The `tests` dir under root seems to be redundant & the correct dir to use is `src/backend/tests`.

Don't forget to branch from the **development** branch @Freedisch 😉

**Comment by Freedisch** [comment]
On it!
