### ISSUE TITLE
Assess adding `SUBMISSION_COMMENT` task action for submission comments

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1694]
**Is your feature request related to a problem? Please describe.**

- We have an endpoint to submit comments.
- We can't distinguish between task comments or submission comments.

**Describe the solution you'd like**

- Possibly refactor `COMMENT` action --> `TASK_COMMENT`
- Add `SUBMISSION_COMMENT` action to enum.
- Allow the endpoint to receive either a task or submission comment.
- These will be filtered / displayed differently on the frontend.

**Additional context**
related to #1617 
The UI for posting and viewing comments is below: 

![image](https://github.com/user-attachments/assets/8a467084-c7b6-43d6-803e-e748e734830e)

![image](https://github.com/user-attachments/assets/0c4f1d45-8d41-4314-9788-9e9a271d7a39)

**Comment by spwoodcock** [comment]
We definitely need a way to save comments.

Should we discuss tomorrow if this should be via a new API, or reusing existing APIs?

If it's a new API, then it also means a new db table, schemas, etc.

**Comment by Sujanadh** [comment]
Is this priority high for the next release?

**Comment by manjitapandey** [comment]
I believe yes, since it is blocking the #1617 . This also significantly impacts user experience when a UI is provided for comments, but they are neither stored nor displayed anywhere.

**Comment by manjitapandey** [comment]
We decided to temporarily pass submission id and submission prefix to store and show the submission based comments. and create a separate endpoint could be task for later.

**Comment by spwoodcock** [comment]
I don't think we will need a **separate** endpoint, so I will update this issue 👍

**Comment by NSUWAL123** [comment]
This has been fixed in the front end in PR #1709 by adding a prefix of `SUBMISSION` text with the submission `UUID`.  I think this would only be a temporary fix for this release and won't be reliable. But in the future, we would probably need a separate API that handles GET & POST for submission-specific comments only like in the ODK. 
What do you think @spwoodcock, @spwoodcock, @manjitapandey ?

**Comment by spwoodcock** [comment]
Agree 💯

It's a temp fix for now 👍
