### ISSUE TITLE
Form category and uploaded form should be prepopulated while editing project form

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1699]
**Is your feature request related to a problem? Please describe.**
When I go to form edit page, the form category is not prepopulated causing confusion to users. This also envokes extra clicking of buttons to choose form category everytime they are updating form. 

**Describe the solution you'd like**
Form category and uploaded form should be prepopulated while editing project form. This would decrease overhead of choosing form category too when they just want to update form, increasing user experience for project managers. 

**Describe alternatives you've considered**

**Additional context**
This is the UI for now.
![image](https://github.com/user-attachments/assets/566c3771-1b28-4cca-b835-80c6fcc531f1)

**Comment by spwoodcock** [comment]
You're right, perhaps it's easier just to display the category type but disable changing it for now. 

We need to extract the type from the API then pass the type when we call the update API

**Comment by NSUWAL123** [comment]
do we need to display the previously uploaded file below the upload file section?

**Comment by spwoodcock** [comment]
No I think it's fine - the user can download the form from the project page if needed 👍
