### ISSUE TITLE
Submission count in infographics page is not updated when custom coordinate upload

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1711]
**Describe the bug**
When user uploads their submission using custom coordinate and not selecting any entities presented, this is not counted as the submission and is not updated on infographics page. 
In the screenshot below, The submission count is shown 0 while the submission is available there in the table. 
![image](https://github.com/user-attachments/assets/22f4318b-afd3-4d8d-b5cd-e2e745a87a4a)

The form submission graphs also shows no form submitted. 
![image](https://github.com/user-attachments/assets/089bca01-76a2-42d8-8858-b452d553e4e8)
 
**To Reproduce**

1. Go to 'project details page and scan the QR'
2. Fill up the form by selecting custom coordinate
3. view the infographics page.

**Expected behavior**
Is this the expected behavior? Needs further discussion on how to manage this inconsistency. 
What would end users understand from the graph. 
cc: @spwoodcock , @ramyaragupathy

**Comment by spwoodcock** [comment]
Will probably address this next release 👍

**Comment by manjitapandey** [comment]
What could be the possible solution to tackle with this inconsistency? 

cc: @spwoodcock , @NSUWAL123 , @Sujanadh

**Comment by NSUWAL123** [comment]
The solution may be to revert back to the previous approach of calculating counts for the infographics using API or work on backend linking the custom coordinate with the building. This problem is due to the calculation of counts from the /statuses API. Since the submission is not linked with any OSM id, this problem is caused.

**Comment by spwoodcock** [comment]
There is a solution in the XLSForms!

https://docs.getodk.org/central-entities/#creating-and-updating-entities-with-one-form

We can use the `create_if` field in the `entities` tab of the **survey** form to create an entity if a geopoint location is recorded. 

Requirement:

- Check that having a mixed polygon and point entity list won't break anything, e.g. the map widget in ODK Collect

**Comment by spwoodcock** [comment]
Blocked by #1730

**Comment by manjitapandey** [comment]
For reference: 
The total submission count on submissions doesn't match with the actual submission count on table and total count on the pagination
![image](https://github.com/user-attachments/assets/9329b27d-1bb3-43ea-b474-054d4af7c662)

**Comment by Sujanadh** [comment]
I will work on this @spwoodcock

**Comment by manjitapandey** [comment]
The issue is not fixed yet
![image](https://github.com/user-attachments/assets/9f3721b9-adb9-4157-bca3-16ce792e0b4a)

**Comment by spwoodcock** [comment]
@manjitapandey should this be open if it's not fixed? Or did it pass a second round of testing?

**Comment by manjitapandey** [comment]
Sorry didn't update here but its fixed while trying again. May be it took time to update
