### ISSUE TITLE
Better frontend validation of input TMS URL for custom imagery

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1719]
**Describe the bug**

- We don't do much validation of the input TMS URL

**To Reproduce**

- `I tested with this URL: https://tiles.openaerialmap.org/5e6785161804990005e37072/0/5e6785161804990005e37073/{ z}/{x}/{y}`
- There was a simple space in the `{ x}`, causing parsing of the URLs and downloads to fail.

**Expected behavior**

- There should be better checking / parsing of the provided URL, to prevent errors.
- Validation should run in project creation and the basemaps modal.

**Comment by manjitapandey** [comment]
but Validation on frontend during project creation is necessary, so that project aren't created with invalid TMS url.
