### ISSUE TITLE
Reword 'Data Extract' for user facing content --> 'Map Features'

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1723]
**Describe the bug**

- Data extract is an obscure term that is too technical.

**Solution**

- Reword to 'Map Features' in the UI.
- There is the project creation stepper to consider.
- Perhaps other places.

**Comment by NSUWAL123** [comment]
![image](https://github.com/user-attachments/assets/078551c1-7162-4ddf-94dd-2022e2775cd9)

Do you mean replacing `Data Extract` with `Map Features` ?
- Updating the stepper title
- Updating texts where data extract is written to `Map Feature`

Should we also reword the texts to -> Use OSM `map feature`, Upload custom `map feature`?

**Comment by spwoodcock** [comment]
Yep exactly!

Be sure to use the plural `Map Features` or `map features` in all cases though 👍 

Thanks 🙏

**Comment by manjitapandey** [comment]
![image](https://github.com/user-attachments/assets/2523d3ba-bff7-4511-ba00-ea6a8724f9e2)
The downloaded file is still named data extact. Its changed elsewise.

**Comment by spwoodcock** [comment]
Good catch 👍 

Fixed https://github.com/hotosm/fmtm/commit/f0530ba03bce0f17b64ed9801cdbe06ac9cbee6e
