### ISSUE TITLE
Explain the custom TMS URL during project creation

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1739]
- There is a button to use a 'custom TMS URL' during project creation.
- It's not very clear what this functionality does to the user.
- We should probably mention OpenAerialMap as an option and link to a document explaining OAM and how this works.

**Comment by manjitapandey** [comment]
You can use the 'custom TMS URL' option to integrate high-resolution aerial imagery like OpenAerialMap [(OAM)](https://openaerialmap.org/). Simply obtain the TMS URL and paste it into the custom TMS field. More details: [OpenAerialMap Documentation](https://docs.openaerialmap.org/).

Does this works on the info section on left side of project creation first step?

**Comment by spwoodcock** [comment]
Good for me! 🙌
