### ISSUE TITLE
Opening the project detail page for a project_id that does not exist should error

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1748]
**Describe the bug**

- If the user goes to the URL `http://fmtm.localhost:7050/project/1`, but a project with ID 1 does not exist, we get this displayed:

    ![image](https://github.com/user-attachments/assets/7d0d623a-b255-44bd-817c-0869ea0534a1)

- We have an informative error to say 'Failed to fetch project' - this is fine.
- However the user experience could be improved here.

**Expected behavior**

- The map and UI should not be rendered with nothing in them - it looks messy.
- Instead we should display a 'Project not found' error page.
- A page should be designed, or we can reuse an existing error page to better inform the user that a project does not exist.

**Comment by NSUWAL123** [comment]
@spwoodcock, I talked with Kailash dai (design team) and he will make a design for a project not found page.
