### ISSUE TITLE
Project creation repeatedly fails in task generation step

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/fmtm#1755]
**Describe the bug**
While attempting to create a project on FMTM as a guest user, it failed at the task generation stage.

**To Reproduce**

1. Go to [https://fmtm.hotosm.org/](https://fmtm.hotosm.org/).
2. Click on 'Explore projects'.
3. When prompted to sign in, login as a guest user.
4. Use the [AOI here](https://gist.github.com/ramyaragupathy/864771d0c2d38d62a036c2a397bda917) and https://tiles.openaerialmap.org/5e0ee67b15d478000501ea5f/0/5e0ee67b15d478000501ea60/{z}/{x}/{y} for project creation workflow.
5. Choose buildings category, there was no custom xls form used. We went with the defaults.
6. Int he data extract stage, run OSM extracts for the given area. It took less than 30 seconds to download all the buildings for the given AOI.
7. In the task generation step, attempted 5 buildings per task with task splitting algorithm. Here it failed  twice with an error message.
8. Then attempted divide by square with 10 meters as input. Again it failed.

However this error is not consistently reproducible.

**Expected behavior**
May be indicate for the user to reduce the number of features per task or reduce the area of task grid.

This was attempted on 13th Aug between 12-1PM UTC

cc @spwoodcock @manjitapandey @Sujanadh @NSUWAL123

**Comment by spwoodcock** [comment]
This seems to have been caused by CPU usage overload on two API containers out of four.

The servers were struggling to return a response, hence the timeout - hopefully this is fixed!

Thanks for the debug info 😄
