### ISSUE TITLE
Add button to 'add new map feature' when mapping, to open ODK Collect

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1764]
**Describe the bug**

- Currently we mostly focus on the flow to tagging existing map features, by clicking on the feature and opening the survey in ODK Collect.
- However another scenario is mapping an entirely new building for which the geometry does not exist yet.
- With XLSForm design we can have a question to add a new map feature.
- However currently the user needs to go directly to ODK Collect and fill out a form to do this.
- This isn't the most intuitive approach, as it requires the user to know this is an option on the XLSForm.

**Expected behavior**

- There should be a button in the UI to 'add a new map feature'.
- This button opens the ODK Collect form (with no feature selected).
- The user can then fill out the question included on the form:
  - Either recording a new geopoint, or drawing a polygon on the map.

**Comment by manjitapandey** [comment]
The button is available but when I choose to map new feature, I encountered the question to select the feature for mapping. 
I don't think this should be expected? 
What do you say? @spwoodcock , @NSUWAL123

**Comment by spwoodcock** [comment]
True, we could probably modify the form / load some data by intent here to improve the workflow.

That should probably be a separate issue, related to backend/osm-fieldwork label.

@Sujanadh could you look at this alongside the other XLSForm changes? 🙏
