### ISSUE TITLE
Rename docker-compose.yml files --> compose.yaml

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1769]
## Issue

- Docker compose recently made the default compose file `compose.yml` instead of `docker-compose.yml`.
- `docker-compose.yml` may be deprecated in future? It's also docker-centric, when we may want to use OCI tools such as Podman compose.

## Solution

- Rename all `docker-compose.yml` files --> `compose.yaml`.
- Update all references to docker-compose file to the new file names.
  - In this repo.
  - Plus in fmtm-installer sh script.

> [!NOTE]
> `yaml` extension is also preferred over `yml` in the official YAML spec.

**Comment by casdal** [comment]
Hi there @spwoodcock ,
 
I would love to work in this one.
Can you please assign it to me.

**Comment by spwoodcock** [comment]
Sure!

Thanks @casdal 😁

**Comment by casdal** [comment]
Hi @spwoodcock,

should I need to modify also this files ?

[docker-compose.development.yml](https://github.com/hotosm/fmtm/blob/development/docker-compose.development.yml)
[docker-compose.main.yml](https://github.com/hotosm/fmtm/blob/development/docker-compose.main.yml)
[docker-compose.staging.yml](https://github.com/hotosm/fmtm/blob/development/docker-compose.staging.yml)

**Comment by spwoodcock** [comment]
> Hi [@spwoodcock](https://github.com/spwoodcock),
> 
> should I need to modify also this files ?
> 
> [docker-compose.development.yml](https://github.com/hotosm/fmtm/blob/development/docker-compose.development.yml) [docker-compose.main.yml](https://github.com/hotosm/fmtm/blob/development/docker-compose.main.yml) [docker-compose.staging.yml](https://github.com/hotosm/fmtm/blob/development/docker-compose.staging.yml)

Yes please! 🎉

**Comment by casdal** [comment]
Thanks you @spwoodcock,

If something need some more work, please just tell me.
#1998

**Comment by spwoodcock** [comment]
@all-contributors
add @casdal for code
