### ISSUE TITLE
Visualising Images on submission details page

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1776]
**Is your feature request related to a problem? Please describe.**
Currently the images uploaded during form submission are not being visualised on submission details page.

**Describe the solution you'd like**
The images should be visualised on submission detail page of that submission as in UI screenshot below. 

![image](https://github.com/user-attachments/assets/bfa504fc-9c27-437a-a697-be2bb6db6aa0)

**Comment by spwoodcock** [comment]
Dup of #1706?

**Comment by manjitapandey** [comment]
Yes, Sorry closing this.
