### ISSUE TITLE
fmtm-splitter refinements for Tokha mapping survey in Nepal

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1779]
**The issue**

- https://github.com/hotosm/fmtm-splitter is quite a tricky beast, as there is such a variable range of inputs.
- We need to test it out on as many real world splitting scenarios as possible to further refine it and fix bugs.

**What we should do**

- Download the Nepalese gov **ward** boundaries for Tokha.
- Use these ward boundaries to split buildings with various parameters for testing.
- Report any issues on fmtm-splitter repo.
- Address as many issues as possible prior to the project creation stage and mapping 1st November.

@ramyaragupathy @manjitapandey

**Comment by manjitapandey** [comment]
Here are the buildings and ward boundary of all wards of Tokha municipality. 
[ward boundary and Buildings_tokha.zip](https://github.com/user-attachments/files/16973641/ward.boundary.and.Buildings_tokha.zip)
