### ISSUE TITLE
Visualising Total features count after the map features are uploaded

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1782]
**Is your feature request related to a problem? Please describe.**
Currently while map features are extracted from osm or custom features are uploaded, it doesn't show the count of features uploaded. 

**Describe the solution you'd like**
Addition of map feature count so that user can get clear idea how to divide the task and how many task will be there on beforehand. 

**Describe alternatives you've considered**

**Additional context**

**Comment by spwoodcock** [comment]
I like this idea - during project creation, probably on the split task section, we could have a simple count for the number of features in the decoded data extract geojson 👍

**Comment by manjitapandey** [comment]
Currently, Both primary and additional features are added to show the total feature count. 
We can rather split them to Primary feature count and additional feature count.

**Comment by spwoodcock** [comment]
Sure that's possible. Should we do this when we focus on the project creation workflow though?
(I know it's a quick fix, so I'll leave it for you two to discuss👍)
