### ISSUE TITLE
Display geopoint location on submission detail page

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1791]
Follow on from https://github.com/hotosm/fmtm/issues/1730

**Describe the bug**

- When a new feature is submitted as a geopoint, we can view it in the validation table.

    ![image](https://github.com/user-attachments/assets/ca2862a1-3d4f-4405-8ab0-4eeb6589cbfc)

- We don't have an easy way to validate the geometry location though.
- Normally when a submission is viewed the geometry is loaded in an OpenLayers map, e.g.:

    ![image](https://github.com/user-attachments/assets/bcedc38b-b533-4fb5-8648-15748dc914a8)

- However for the submitted geopoint, nothing is loaded:

    ![image](https://github.com/user-attachments/assets/353b4d96-05f4-4fcc-99ad-e75f04a1d985)

**Solution**

- The submission detail page (e.g. https://dev.fmtm.hotosm.org/project-submissions/61/tasks/11533/submission/uuid:b2d1205c-72b2-4353-bf6c-1e1904fbf82e) should be able to load points as well as polygons.

- Currently we parse the `xlocation` JavaRosa string from the submission:

```js
  const coordinatesArray: [number, number][] = restSubmissionDetails?.xlocation?.split(';').map(function (
    coord: string,
  ) {
    let coordinate = coord
      .trim()
      .split(' ')
      .slice(0, 2)
      .map((value: string) => {
        return parseFloat(value);
      });
    return [coordinate[1], coordinate[0]];
  });
```

- This logic should be skipped if the `new_feature_point` key is present in the submission json:

```json
{
        ... other fields
        "point": "yes",
	"new_feature_point": {
		"type": "Point",
		"coordinates": [
			0.19569001238613737,
			53.10334032909082,
			0
		],
		"properties": {
			"accuracy": 0
		}
	}
}
```

- If present, handle the rendering differently by loading a Point in OpenLayers instead of a Polygon.

**Comment by manjitapandey** [comment]
The geolocation is not visible in case where no location is provided while filling up of the form. This is actually a loophole on form that we allow user to not choose any feature as well as not provide any geolocation. 
I believe this can be solved by slightly modifying the current xls form to make either geopoint or feature selection compulsory.

**Comment by spwoodcock** [comment]
This actual issue is solved then right?

The issue you mentioned is another one that I will address with the XLSForm updates 👍

**Comment by NSUWAL123** [comment]
Yes if the geometry is provided then it's visible

**Comment by spwoodcock** [comment]
Fixed the XLSForm issue too by making the fields mandatory 👍
