### ISSUE TITLE
Create document of API endpoints

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#18]
Before writing a ton of code, it'd be a good idea to write down the endpoints for the backend. For example, endpoints to create the QR-codes, and one to upload it.

**Comment by krtonga** [comment]
Please see endpoint documentation here: https://docs.google.com/document/d/1sGivyGR6CoApkMspbyfec81y32U7B_b77Lj-ltODIeI/edit?usp=sharing
