### ISSUE TITLE
Frontend implementation for multiple feature selection within single form submission

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1800]
**Is your feature request related to a problem? Please describe.**

Follow on from #1653, as the frontend implementation.

Related https://github.com/hotosm/fmtm/pull/1792 https://github.com/hotosm/fmtm/pull/1799

Issue was described across these links, but consolidating info here.

**Describe the solution you'd like**

During project creation we need:

- [x] update frontend to allow uploading supplementary geojson geometries
    ![image](https://github.com/user-attachments/assets/96742c1a-aef1-45eb-9d0d-d4ca6ccf30c3)
    - There should be an additional button 'Upload Additional Features'.
    - It should use a checkbox, with the upload field hidden until the box is checked. Similar to the custom XLSForm upload.
    - It would probably be good if we can validate the GeoJSON file, in similar way that we validate the AOI area upload (probably not requiring backend).
    - The GeoJSON data and filename (without extension) should be saved in frontend state.
- [x] On the final project submit we need to call the `/projects/{project_id}/additional-entity` endpoint, passing in the GeoJSON file as form data. It should be called after task areas have been created (via API call) and data extract uploaded (via API call), but before the `/generate-project-data` endpoint is called (this will create the Entity list).
    - The param for the API is `geojson`.
- [x] Pass the filename (without file extension) as the `additional_entities` param on `/generate-project-data`.
    - This is a list, so would be additional_entities: [GEOJSON_FILENAME_WITHOUT_EXTENSION].
    - The endpoint should receive the additional list and inject variables into the XLSForm so the user has a question to select the geometry.

**Comment by spwoodcock** [comment]
@manjitapandey this is the final part for the Tokha project requirement 😄

**Comment by manjitapandey** [comment]
unable to create projects with multiple map features. 
Steps to reproduce:
1. upload buildings as custom map feature.
2. click on additional map feature and upload road data.
3. use task splitting algorithm and submit.
4. see error in project creation. 

500 error is encountered on `
https://api.stage.fmtm.hotosm.org/projects/47/additional-entity` api.

**Comment by manjitapandey** [comment]
This feature is functional if we upload point, line and polygon however, there is an errror in case user uploads multiline string as additional features.

**Comment by spwoodcock** [comment]
Good info!

Perhaps we can pass the geogjson through our processors to strip out multi-geom types in FMTM? (in postgis_utils.py` I believe

**Comment by Sujanadh** [comment]
Actually, the problem wasn't due to `MultiPolygon` and `MultiLinestring` but due to some invalid properties in the `geojson` file such as having keywords of `odk` for example` label, uuid , name` and some invalid characters within properties keys which failed in creating dataset columns and entities in `odk-central`.
