### ISSUE TITLE
Duplicate choices after injecting mandatory fields

### ISSUE THREAD

**Issue by Sujanadh** [hotosm/fmtm#1809]
**Describe the bug**
When custom form is used to create a project, mandatory fields are injected in the custom form which resulted into multiple duplicate fields ( such as multiple yes_no field in choice sheet). Because of that while loading form on odk, question labels weren't visible.

**To Reproduce**
Create a project with custom form 
[custom_form.xlsx](https://github.com/user-attachments/files/17145055/custom_form.xlsx)

1. Go to Project detail
2. Click on Download Form
3. See multiple same choice fields
![image](https://github.com/user-attachments/assets/90361630-753c-443b-9b6c-4136d10e27b5)

**Expected behavior**

**Screenshots**
![Screenshot_20240926_135436_ODK Collect](https://github.com/user-attachments/assets/756df6c0-9bf2-4273-afd9-c44b18572d5c)
![Screenshot_20240926_135634_ODK Collect](https://github.com/user-attachments/assets/b778890e-ebbd-4ff9-93d1-d48579d9ddd1)

**Comment by spwoodcock** [comment]
The issue here is not the duplicate name entries, but it's the missing translation fields for the label not being displayed

**Comment by manjitapandey** [comment]
Yes, the missing translation `fields` is also an issue. For the xls form I used, the label for english is as `label::English (1)` but on the mandatory fields we injected the same column for english label is as `label::English (en)`. This causes two column for same purpose and the label for english is provided on  `label::English (en)` column are visible while on another label isn't visible. 
How do we cope with this type of issues?

![image](https://github.com/user-attachments/assets/9b81c1c8-fa1e-4b57-accb-dec15c78b01a)
![image (35)](https://github.com/user-attachments/assets/7ea4bac7-47ac-4cbd-8d17-4b47a9a977ee)

**Comment by spwoodcock** [comment]
`label::English (1)` isn't a valid xlsform column, so that's why it doesn't display anything.

It must be format `label::English (en)`.

If the user uploads an incorrect column name then their form isn't valid and we shouldn't attempt to autocorrect it. Perhaps in future we could have some logic to provide a warning if there are misspellings or slightly wrong column names, but it's not a priority

**Comment by manjitapandey** [comment]
But for the validation we use, the form is valid. I had also tested the form on kobo collect, the form is said to be valid. 

For now this issue can be closed and we can have deeper look into the issue if any user reports such behaviour to be an issue for them. 
cc: @Sujanadh
