### ISSUE TITLE
Implement clear Call to action buttons for mapping/validaiton

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1819]
**Is your feature request related to a problem? Please describe.**
The clear call to action buttons are missing on mapping and validation workflow prompting users to map or validate the task. 

**Describe the solution you'd like**
We can redesign the UI to add clear call to action buttons on FMTM for better user experience. 
 
https://www.figma.com/design/GUKooEhrNwHFTaAaEHxUcS/FMTM?node-id=3253-2920&node-type=canvas&t=VglQkDAQtzzn5ViI-0

**Comment by spwoodcock** [comment]
I think we have captured this in the roadmapping exercise and have it planned for our future designs - closing this issue 👍
