### ISSUE TITLE
User report: custom XLSForm is not being used in ODK

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1832]
**Describe the bug**

"After updating the questionnaire, we uploaded it to FMTM. However, when we connected it with ODK, the form that appeared was still the default building form from HOTOSM. When you check in FMTM, the customized form is available, but on ODK, a different one shows up."

**Possible issue**

- Need to debug why the custom form was not used?
- Does the project creation logic simply default to the default FMTM buildings form?

**Comment by manjitapandey** [comment]
@spwoodcock tried to reproduce the issue but I am not able to using my custom xls form. 
Can you share the xls form that is being used on field? 
cc: @ramyaragupathy

**Comment by spwoodcock** [comment]
Thanks for testing @manjitapandey!

I think this is fixed on stage! We will make a new release and solve this 🎉
