### ISSUE TITLE
Minor frontend updates for better wording / explanations in project creation

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1833]
Based on discussions with @ramyaragupathy and user feedback.

## Issue

- Select 'Category' is no longer good terminology, as we basically use custom XLSForms for all projects now.

- The secondary dataset upload functionality is not explained.

- Info about coordinate systems is not clear on geojson upload. While ideally the use should know about coordinate systems if creating a project, this may not always be the case. GeoJSON is a tricky dataset in that it rarely includes the coordinate system. Normally they should be EPSG4326, but they could equally be web mercator, or even another coordinate system entirely 😅 

## Solution

- Rename 'Select Category' --> 'Upload Survey'
- Add a small bit of info explaining why uploading a secondary geojson might be useful - for mapping features that have related features (e.g. buildings, selecting the road it falls on).
- Inform the user that geojson uploads should be in EPSG 4326 coordinate system.

**Comment by manjitapandey** [comment]
- Though we practically use custom xls form for most of the real field projects, we also provide option for choosing the survey type. So May be we can rename 'Select Category'  to 'Choose the Survey type'.
> Add a small bit of info explaining why uploading a secondary geojson might be useful - for mapping features that have related features (e.g. buildings, selecting the road it falls on).

- Absolutely, we can add that on the notes panel on the left. 

> Inform the user that geojson uploads should be in EPSG 4326 coordinate system.

- This can be added on second step.

**Comment by spwoodcock** [comment]
This is a good small change for now.

In the longer term I'm actually thinning we update the backend and frontend a bit:

- Remove the concept of a 'category' to select. Remove the db field and handling on the backend for this (during create and update form).

- Make a custom form upload the **default**.

- Add a option to 'Alternatively, use or extend from one of our example forms', where the user can select an example form type or do the interactive editing.

Thoughts @manjitapandey ?

**Comment by manjitapandey** [comment]
Sam we can have further discussion on removing categories. Can create a separate issue for that. But for now we can have this changes with the following texts:

- `Additional datasets might be important if your survey consists of more than one feature selection. like if you want to select the building as a primary feature and associated road or nearest hospital, you can upload the additional features of road and hospital data. Note: The additional features won't be used for splitting purpose. `
- `Note: The uploaded geojson should be in EPSG 4326 coordinate system.`

**Comment by spwoodcock** [comment]
Looks good to me 👍 

Maybe some slight rewording on the first:

`Additional datasets might be important if your survey consists of more than one feature to select. For example, selecting a building as the primary feature, with an associated road, or nearby hospital. In this case, the roads or hospital features would be uploaded separately. Note that these features will not be factored in when dividing the primary features into task areas.`
