### ISSUE TITLE
Divide on square option for task split cause page to crash

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1837]
**Describe the bug**
When I try to split task based on square, the page crashes making it unable for me to proceed ahead. This behavior is on both staging and production server. 

**To Reproduce**

1. Go to 'create project'
2. Upload Custom AOI
3. You can upload custom map features or osm map features
4. Click on divide on square and click on generate by providing dimension of squares
5. See error

**Expected behavior**
The tasks should be generated based on dimension provided by users instead of crashing of page. 

**Screenshots**
![image](https://github.com/user-attachments/assets/c344f886-3cd9-4706-b41c-e5914bd0046a)

![image](https://github.com/user-attachments/assets/4fa252af-5aad-41e5-a168-670ebd8abdb3)

**Comment by spwoodcock** [comment]
Testing failed:
- The API works now and returns a 200 always.
- However the task area is always the same, possibly hardcoded to 100m?

See this example where I always get 19 tasks returned, regardless of dimension set.

![image](https://github.com/user-attachments/assets/0c9c38ef-596b-4d12-8995-5f74a61f64c1)

![image](https://github.com/user-attachments/assets/232c34ff-727c-4f70-bb5b-5fa7f5da4200)

![image](https://github.com/user-attachments/assets/b42a5bf5-644a-4509-98d7-55c9f3f2e52c)

The request is sending the dimension correctly:
![image](https://github.com/user-attachments/assets/303ef6f6-b0ca-40e8-b6d8-f0dfa665dd51)

**Comment by manjitapandey** [comment]
couldn't reproduce the behaviour. I tested with 300 and 100 m for divide on square and got different results. 

![image](https://github.com/user-attachments/assets/91bd3a0b-e4d5-47c8-8dbc-4775af9bec7e)
![image](https://github.com/user-attachments/assets/86368f53-705f-4e4f-a273-7e6bd51fc8eb)

**Comment by Sujanadh** [comment]
The issue mentioned by @spwoodcock was due to a payload mismatch in the development branch. Since it's a minor fix, I will update it along with other fixes.
