### ISSUE TITLE
Mapper-Frontend: Mapper Flow

### ISSUE THREAD

**Issue by NSUWAL123** [hotosm/fmtm#1853]
**Is your feature request related to a problem? Please describe.**
If a user loads the project for the time, they should be guided to load the project on ODK and map tasks.

**Describe the solution you'd like**
Build a mapper flow as per design: https://www.figma.com/design/GUKooEhrNwHFTaAaEHxUcS/FMTM?node-id=3373-3146&node-type=frame&m=dev

**Additional context**
The project setup step shall be stored in the local storage.

**Comment by manjitapandey** [comment]
Added additional comments on another issue. #1901
