### ISSUE TITLE
Updating XLSForm throws 500 error

### ISSUE THREAD

**Issue by NSUWAL123** [hotosm/fmtm#1864]
**Describe the bug**
When updating the XLSForm via manage project's form update, API throws 500 error.

**To Reproduce**

1. Go to 'Manage Project'
2. Click on 'Form Update tab'
3. Download => Upload Downloaded Form => Click "Update"

**Expected behavior**
Error should not be generated and XLSForm should be updated

**Screenshots**
![image](https://github.com/user-attachments/assets/ba39385c-523f-4d28-b8b1-42322748f27e)

**Comment by manjitapandey** [comment]
form update shows functional on network panel but when the project is loaded on odk, previous default form is shown.

**Comment by spwoodcock** [comment]
Was this supposed to be closed? I think I reproduced the issue a while ago too, where it looked like a success but actually did not update (might be fixed though!)

**Comment by manjitapandey** [comment]
I tested it on dev server and form was updated successfully as well as changes were reflected on odk form too.
