### ISSUE TITLE
Manage options visible without login

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/fmtm#1889]
Currently, `manage organisations` option is default available without login. This option should be available only for logged in admin users.
<img width="1408" alt="image" src="https://github.com/user-attachments/assets/b1069e85-8e14-42cf-b4cb-3be7463e60f5">

Though this option is visible, upon hitting the link, user prompted to sign-in. It is best to tie it up with user login and access.

**Comment by spwoodcock** [comment]
The decisions taken here are slightly different to TM actually. 

We allow anyone to request the creation of an organisation. This creates an unapproved org item in the db, and is planned to also notify the admin.

Once approved, the requesting user can be elevated to organization admin to manage the org further, create projects within etc.

(the problem we wanted to avoid was having something external like a Google form to apply, but this approach does include an element of trust that the user isn't going to apply for many orgs. We can see who the requester is though, as they have to use OSM login. If multiple unapproved orgs are created, we can simply delete them, maybe on a schedule)

What do you think?

**Comment by spwoodcock** [comment]
Closing this as not planned, unless we discuss and decide to reopen it 👍
