### ISSUE TITLE
The custom ODK collect downloads should be more user friendly.

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1908]
**Is your feature request related to a problem? Please describe.**
Currently, when users clicks on **go to odk** by selecting a task or building on mobile phone with no custom odk collect, there is no error message. 

**Describe the solution you'd like**
User friendly error message like _Make sure to install custom odk collect from here to enable this feature_  can be shown linking to download file. Also 

**Additional context**
![Image](https://github.com/user-attachments/assets/4dff5278-f8c4-4a02-b52a-98dfa8559c38)

I am not sure of technical difficulty of adding this. Please feel free to close this issue if its not possible technically.

**Comment by spwoodcock** [comment]
Unfortunately it's not possible!

It's a catch22: we can only include an error if we build a custom APK and the user has that installed, but we want to display an error without a custom APK installed

**Comment by spwoodcock** [comment]
On the plus side, future plans using Web Forms would circumvent this issue entirely 😄
