### ISSUE TITLE
Project creation fails when other odk credentials used even if provided credentials are correct

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1944]
**Describe the bug**
Project creation fails when other odk credentials used even if provided credentials are correct

**To Reproduce**

1. Create organisation with odk credentials
2. Approve the organisation'
3. create a new project using the same org

**Expected behavior**
The project should be created with other odk credentials too along with hotosm. 

**Screenshots**
![Image](https://github.com/user-attachments/assets/4c36fd40-4a2d-4637-a626-3ce90d1a9d51)

**Additional context**

**Comment by Sujanadh** [comment]
There was double encryption of the password when a new organisation was created; that is the reason for not being able to make a connection to ODK Central while creating a project.

**Comment by spwoodcock** [comment]
I have verified this is fixed 👍
