### ISSUE TITLE
Setup development server

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#195]
To help keep the fmtm.hotosm.org server more stable for both demos, we need a development server that can be abused. Since FMTM creates thousands of tasks and data extracts, it can quickly be overwhelming to navigate via ODK Central. The dev server should run the unstable backend from the development branch and ODK Central. Restarting ODK Central's docker container will clean the database to reduce the mess. While users of FMTM will never look at the ODK Central server at all, during development it's necessary to make sure all the XForms and data extracts are actually being uploaded.

**Comment by spwoodcock** [comment]
Steps:

1. Configure Linux server.
2. Install docker and docker compose V2 CLI.
3. Create svcfmtm user and SSH keypair (without password).
4. Replicate deploy_prod.yml GitHub workflow to deploy_dev.yml, but change the branch to `development`.
5. Create another development environment in the repo settings (dev).
6. Add SSH private key as secret variable for deploy workflow. 
7. Add .env secret with development variables to the dev environment secret variables.
