### ISSUE TITLE
Addition of project name and details on mapper frontend

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1976]
**Is your feature request related to a problem? Please describe.**
Currently, user can click on start mapping button on project cards and directly go to mapper frontend. Doing this, they won't be viewing the project's description. As well as for the mappers to whom mapper frontend link is shared, they won't be able to see the project name and description for now. 

**Describe the solution you'd like**
Addition of project name and description along with the organisation under which the project is created and if feasible project ID should be visible on mapper frontend page if they want to get any project related information. 

**Describe alternatives you've considered**

**Additional context**
Design is yet to be finalised.

**Comment by NSUWAL123** [comment]
@Anuj-Gupta4 , on `/projects/:id/minimal` organization_name is null

**Comment by spwoodcock** [comment]
Thanks @NSUWAL123 👍

@Anuj-Gupta4 the alternative SQL in the same .one function has the SQL for this, so it just needs to be transfer across
