### ISSUE TITLE
Use odk_merge.py to process submissions

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#199]
As part of the post mapping process, the FMTM backend needs to convert the CSV submissions from ODK Central, convert them to OSM, and then use odk_merge to conflate the new data with existing OSM data. This will use the data extract, downloaded from ODK Central for existing OSM data for conflation. The result is an OSM file with the new edited tags merged with existing tags. This file when loaded into JOSM and using the JOSM "updated modified" will then allow the new data to be uploaded to OSM after brief validation.

**Comment by susmina94** [comment]
The user can download the files in osm, csv and geojson formats and upload them to JOSM.
So I am closing this one for now.
