### ISSUE TITLE
Two location points are shown on mapper frontend

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#1992]
**Describe the bug**
In mapper frontend, when user use PM tiles as a baselayer and switch back to openstreetmap as baselayer, two geolocation icon are visible, When the geolocation is now turn off , one location vanishes but one remains. 

**To Reproduce**

1. Go to 'mapper's page'
2. Click on 'geolocation'
3. Go to offline mode and use PM tile on map
4. click on basemaps option ad switch to PM tile and switch back to osm baselayer
5. two location are loaded, turn off geolocation and one still remains
6. See error

**Expected behavior**
Only one geolocation icon should be visible and should be removed if location is turned off. 

**Screenshots**
![Image](https://github.com/user-attachments/assets/42775d37-74cb-4b0a-a259-47cf37e7170b)
https://github.com/user-attachments/assets/06e3fc16-9489-475a-a0c2-6c104522e3e9

**Additional context**

**Comment by spwoodcock** [comment]
Hmm probably the maplibre context / layers again - this is a tricky one, but I'm sure we can work it out together 😄

**Comment by NSUWAL123** [comment]
I tested this issue on #1963 and it seems this issue might be solved. Maybe something related to automatic location on and pmtile layer.
