### ISSUE TITLE
Additional geometries shouldn't be clipped  by project area

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#2004]
**Requirement from Tokha field mapping exercise.**
 As they are uploading road network for additional entity, sometimes the road network could get out of exact project area. The current behavior is while viewing the data on odk the features are clipped by project area. Only the features whose centroid lies in project area are shown. This causes major roads to be removed. 

**Expected Behavior**
 In such cases the additional entities shouldn't be clipped by project geometry.

**Comment by spwoodcock** [comment]
The clipping should probably be based on the geom type in general.

We can determine the geom type on upload.

If linestrings, do not clip them to AOI

**Comment by Sujanadh** [comment]
I think supporting dataset, whether it is polygon or linestring, can still be outside project AOI. I don't think we need to clip additional entities with project AOI at all.

**Comment by spwoodcock** [comment]
True! I think I misread the issue. It makes sense to apply to clipping, as the user has to generate the dataset themselves first (and will likely only provide the exact geom they need)
