### ISSUE TITLE
Use JOSM remote to load OSM XML file

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#201]
After the new ODK data is converted and conflated with existing data, that file should be loaded in JOSM using it's remote support.

**Comment by susmina94** [comment]
@robsavoye The conversion is currently fetching the GPS location and not the building centroid or polygons
Need to urgently look into this.

**Comment by robsavoye** [comment]
That means the mapper didn't use "Select Place", but instead collected their standing location. That's why there is no OSM OID. You can tell, cause the data as the accuracy field in the data, which isn't there when selecting existing OSM data. To me, this looks like a training issue.

**Comment by susmina94** [comment]
Click on Upload to JOSM will open the submissions directly into JOSM.
![image](https://github.com/hotosm/fmtm/assets/108750444/9974ced3-ad3a-46ca-aba8-a5220062f0fc)
