### ISSUE TITLE
Sometimes user faces authorisation issue even though they have access

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#2013]
**Describe the bug**
Sometimes some endpoints randomly fails due to authorisation. The error msg says user is not authorised to do so. But after logging out and logging in again the issue is fixed. I have faced this issue in endpoints like project form update and  getting organisation list during project creation.

**To Reproduce**

1. Go to 'create project'
2. Click on 'see the list of org not visible'
3. Sign out and sign in again
4. See the issue is fixed

**Expected behavior**
The user should be able to do specific task every time if they have access. 

**Additional context**
I am still not able to get the pattern of this error. Its irregular but this may be due to authorisation issue.

**Comment by spwoodcock** [comment]
Which server?

Think this was fixed on dev & I imagined we would release again before Christmas.

But as we will wait until after, either we cherry pick the fix to prod or wait for the new release 😃

**Comment by Anuj-Gupta4** [comment]
It seems to work after rebuilding once locally.

**Comment by manjitapandey** [comment]
Just faced the issue again. Is it due to cache or anything??
I can't see organisation list on dev server though i am admin
![Image](https://github.com/user-attachments/assets/1502bf30-2b53-49a9-a605-2f07ea022f36)

**Comment by spwoodcock** [comment]
Its due to cookie expiry after a time, unless the you visit the page and it's refreshed. So no visit in 3 days would cause expiry I think
