### ISSUE TITLE
Tile output format is not visible while tiles are being generated

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#2032]
**Describe the bug**
In the basemaps section, while trying to generate tiles, the tile output format is not visible to the users. The tile format is only populated when generation is completed. 

**To Reproduce**

1. Go to 'project's page'
2. Click on 'basemaps'
3. download any basemap tiles 

**Expected behavior**
The tile's output status should be populated on the table when the tiles are being generated. 

**Screenshots**
![Image](https://github.com/user-attachments/assets/8ed5a55d-9575-444f-803a-6fe5b34fc3e0)

**Additional context**

**Comment by spwoodcock** [comment]
With the current setup this isn't solvable, as its a computed field based on the final file name that doesn't exist until created (not in the db).

Very low priority though - let's not address this in fmtm, but instead basemap-api in future.

**Comment by manjitapandey** [comment]
Thanks for the clarification @spwoodcock . If its not solvable, it would be better to close this for now.

**Comment by spwoodcock** [comment]
https://github.com/hotosm/basemap-api/issues/1
