### ISSUE TITLE
Optionally create imagery basemap

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#240]
When creating or editing a project, there needs to be a way to create an imagery basemap. This will require selecting the imagery source (ERSI, Maxar, OAM, Topo, etc...), and specifying the output type. This will then trigger downloading the map tiles, which can take hours. The two output types are mbtiles for ODK Collect, and an sqlitedb file for Osmand. Ideally this page can also display on a map the progress of the tile downloads within the project area of interest.

**Comment by varun2948** [comment]
created ui, need backend support in it.
