### ISSUE TITLE
Add support for user roles in the frontend

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#244]
Once there is backend support for roles, the frontend will need to support it. The first priority is to decide how roles get specified for users. I assume the main admin can set the role for project admins, but how do we create the primary site admin ?

**Comment by dicksonguantai** [comment]
@robsavoye This looks like a good first issue for me. Please assign this to me #outreachy

**Comment by robsavoye** [comment]
This needs backend support to be added first, which is currently not scheduled.

**Comment by dicksonguantai** [comment]
@robsavoye maybe I could create a ER diagram for the backend

**Comment by Biswajit-Behera** [comment]
@robsavoye kindly Assign this issue to me!
