### ISSUE TITLE
Add drop menus for create project

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#258]
Currently the create project page lets the project manager upload a project boundary. This should be extended to add two drop down menus. One is the splitting algorithm, which should have 3 choices. The default is squares, the 2nd is uploading a custom multi-polygon of task boundaries, and the 3rd is to use OSM features, which is not implemented yet. If squares is the choice, the grid size needs to be specified.

The other menu is to specify the type of mapping project, buildings, healthcare, etc... The list can be extracted from the XLSForm library. This will need a backend endpoint to get the list of XLSForms from the database. The upload project boundary should probably be disabled until the splitting algorithm and mapping category. Uploading the boundary fires off creating the XForms, appusers, and data extracts.

**Comment by varun2948** [comment]
#268 completed it in
