### ISSUE TITLE
Trigger deployment on successful Quay build

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#262]
Currently we deploy to prod using docker compose --build to build on the server first, making Quay.io redundant.

The burden of image building should be passed to Quay, and the app servers only handle traffic / processing requests.

We can achieve this via Webhook, triggering GitHub action after the Quay build completes.

Related comments:
https://github.com/hotosm/fmtm/pull/207#issuecomment-1479530426
https://github.com/hotosm/fmtm/pull/207#issuecomment-1479536718
https://github.com/hotosm/fmtm/pull/207#issuecomment-1479680383
https://github.com/hotosm/fmtm/pull/207#issuecomment-1482413411

I still haven't been able to determine if adding build arts for Quay is possible. It it's not, then there is no point pursuing this.

**Comment by spwoodcock** [comment]
I'm not sure this is possible in Quay, or if it is then it's very convoluted (involving webhooks etc).

IMO we should just use Github container registry. It's free for Open Source projects like ours.

It will also integrate very nicely into the Github actions / workflows.

**Comment by dakotabenjamin** [comment]
Let me know if we need to enable anything on our end to make sure GCR works.

**Comment by spwoodcock** [comment]
Thanks @dakotabenjamin. Everything seems to work well for now.

I plan to use the `GITHUB_TOKEN` during CI workflows to push 👍
