### ISSUE TITLE
ODKCollect App Link Integration 

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#266]
**Is your feature request related to a problem? Please describe.**
Currently the user must use a QR code generated by FMTM to import the task data into ODKCollect.

**Describe the solution you'd like**
A link within FMTM to open ODKCollect directly, including task boundary and metadata.

**Suggestions**
This can be achieved in Android with App Links: https://developer.android.com/training/app-links

iOS has the same feature, called Universal Links, but ODKCollect does not have an iOS app yet: https://developer.apple.com/ios/universal-links/

This solution would require tight integration with the ODK team and some thought with how to make this a generic solution for many apps requiring this feature (perhaps the ODK team have some ideas).

**Additional context**
App Links are available from Android 6 (SDK 23).
If we require compatability with older versions, Deep Links need to be used (which prompt an app selection dialog).

**Comment by varun2948** [comment]
odk collect doesnt support intent as of now so can't really do unless it is added on the odk collect itself.

**Comment by spwoodcock** [comment]
Yeah the idea is to make a PR for ODK Collect with the ability to accept app links, but I made the issue here as a reminder

**Comment by spwoodcock** [comment]
Dup of https://github.com/hotosm/fmtm/issues/2
