### ISSUE TITLE
Setup standalone ODKCentral on development server

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#285]
**This is more for documentation purposes, so everybody knows where the production ODK Central is located**

Instead of using a local (inaccessible) ODK Central for development, we should have a publicly accessible instance.
This instance should be separate from the main HOTOSM ODK Central, as it will be polluted with lots of tests.

It should run on the dev server.

---------------------------------------------------

After this is complete, we should update the docker-compose file for the development deploy and remove all ODK Central related services.
See previous commit doing this (for prod), which was reverted: https://github.com/hotosm/fmtm/pull/283/commits/27997073009ecb7f68e8a2128979794b6777c16b

**Comment by robsavoye** [comment]
This is done.
