### ISSUE TITLE
Pagination for project summaries

### ISSUE THREAD

**Issue by Mudi-business** [hotosm/fmtm#31]
**Is your feature request related to a problem? Please describe.
The API project summaries defaults to 100. When there are more than 100 projects, pagination will be needed. 

**Describe the solution you'd like**
Pagination needs to be implemented on backend and frontend.

**Describe alternatives you've considered**
Just load everything forever... but this get slow and hard to navigate for the user when there are many projects.

**Comment by petya-kangalova** [comment]
Just had a chat with @prasidha and she will start looking at this issue. She will reach out if any questions either here or on Slack @Mudi-business @robsavoye @ivangayton

**Comment by ivangayton** [comment]
Thanks @petya-kangalova; I missed our meeting because my internet was not working; now back on

**Comment by Mudi-business** [comment]
Hi all , I'm sorry for the late response on this issue, but I believe this issue was referring to server side Pagination to be implemented in the backend at first on `https://fmtm-api.hotosm.org/projects/summaries `and then to be implemented on the frontend. I'm not sure if this has been currently implemented on the backend.

**Comment by robsavoye** [comment]
Actually this wasn't really discussed. Were you planning on having the front end send multiple requests to the backend instead of having the frontend load all projects or tasks and paginate purely on the frontend ?

**Comment by Mudi-business** [comment]
Well if we expect to have many projects later on our database , fetching them all at once  assuming that will take time for the API to respond to such request , but the goal is to fetch them on pages like the first time we can fetch like 10 or 20 and when the user click the next page or choose a number upon page then well request those projects according to that page number, but If we expect just have few projects on our db then we don't need the server side pagination obviously.

**Comment by robsavoye** [comment]
That makes sense, I'll open an issue to handle this on the backend, and ask Prasida to update the frontend.

**Comment by Mudi-business** [comment]
OK
