### ISSUE TITLE
Replace odkconvert with osm-fieldwork

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#310]
The odkconvert project has been renamed to osm-fieldwork. The backend files that referenced odkconvert need to be changed to osm-fieldwork once the new python package is on PyPi.

**Comment by mohammadareeb95** [comment]
@robsavoye I'm willing to take on this for any files that need updating. Not starting right away because I saw that you have been working on some files.

**Comment by robsavoye** [comment]
This is done.
