### ISSUE TITLE
Add optional TMS URL in the menu for selecting the source for basemap imagery

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#339]
It should be possible for the project manager to add a TMS URL as a source for imagery. This option will also need to get an output directory for the map tiles.

**Comment by robsavoye** [comment]
osm-fieldwork now has support to use a custom TMS URL for imagery.

**Comment by varun2948** [comment]
@robsavoye we tried custom tms url with this url it didn't quite work for me and @spwoodcock and i had a brief discussion regarding this and here is what sam had to say regarding the issue 

> 
> There is a param xy you can pass to basemapper
> It swaps the yx to xy
> By setting it true
> I feel like this is an issue parsing the URL you provided instead of producing the base imagery
> It doesn't have very smart handling for URLs currently
> It has to be in a specific format
> So every tms can have it's own format & it's really hard to make a generic URL handler - although qgis seems to have done it. Normal format is directory based z/y/x. The one you shared seems to take params, so x= y= and zoom_level=
> We don't have handling for a tms like that yet (although it could maybe be added)

**Comment by spwoodcock** [comment]
Thabks for following up Varun 👍

It's tricky to handle various types of URL format that might be given.

The question is, have we had demand for custom TMS from users?

If yes, then we can bump up it's priority.

But if no, then we can finalise testing on the PR I made and merge for now (even if it's imperfect / needs improvement).
The main functionality I was trying to make available was selection of output format type: sqlite, mbtiles, pmtiles.

**Comment by robsavoye** [comment]
This is potentially low priority. I added this because when using OSM, each area of drone imagery has a different TMS URL. For the Turkey earthquake I used the mosaic from Kontour, but then added this option to use OAM directly as each of the 20 impact areas had a different URL. It has not been heavily tested though. :-)

**Comment by varun2948** [comment]
@susmina94 have something to say on this custom URL as well.

**Comment by susmina94** [comment]
With the use case of Janakpur household survey, we're trying to create an entire workflow from drone image capture to generating the mbtiles for the custom drone images to field survey.

Although the mbtiles can still be prepared using any other tools, it wouldn't be of high priority.
But yes to make sure the workflow is set within the FMTM, this should come in priority later on.

Thanks @varun2948 for keeping it updated.

**Comment by spwoodcock** [comment]
How do you serve the drone imagery once captured? 

The TMS software will probably determine the URL format.

The issue here is that TMS can be in many formats, so we can eifher:

- Stadardise the TMS we create (URL format) for drone imagery (easier).

- Add extra code to basemapper for handling all sorts of URL types (harder, low priority).

**Comment by spwoodcock** [comment]
Two of the best tileserver implementations directly from PostGIS are pg_tileserv and Martin.

We should use them for setting up a TMS as needed (I can add examples to the scripts dir).

So we should follow their URL convention, which is:

`Server-Url/{z}/{x}/{y}`

With an optional `.pbf` we can handle. 

`Server-Url/{z}/{x}/{y}.pbf`

The TMS part of osm-fieldwork should accept this format as the default IMO. (Support for servers with `x=22&y=54&z=83`, or anything based on URL params, should be secondary).

**Comment by spwoodcock** [comment]
Closing @manjitapandey 
related to recent PRs on custom TMS that should work fine.
