### ISSUE TITLE
Write data extract to postgresql database

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#341]
When downloading, it should be possible to write the data extract to the postgresql server being used by FMTM. The schema needs to be the same as used by Underpass, which is documented here: https://github.com/hotosm/underpass/blob/master/raw/raw.lua. By importing the data extract into postgresql, it'll be possible to do postgis operations on the data, but that's a different issue.

**Comment by petya-kangalova** [comment]
@as7072 as discussed in the call you can first take a look at this issue and ask Rob any questions. Thank you!
