### ISSUE TITLE
Add expand xlsforms table

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#363]
Currently the backend assumes the category is the same as the XLSForm filename. This may not always be the case. Over time, some categories might have multiple related XLSForms, If a category column is added, it would be possible to support the times when the XLSForm filename conflicts with an OSM tag that is used in the XLSForm. In addition to adding the category column, a filespec should be added that refer to the actual XLSForm source file. While for now the title is the same as  the filespec, it should be changed to be a more descriptive title. When uploading a custom XLSForm, the mapper will need to specify both the title and the category.

There is a new function make_data_extract.py:getChoices() which reads in the new config file that maps XLSForm filenames to a category. This returns a dict(). Any place in src/backend that refers to the XLSForm needs to get the value based on the category. For example, PostgresClient() takes an optional argument for the cases the XLSForm name is not the same as the category.

**Comment by nrjadkry** [comment]
@robsavoye , I am trying to solve this issue. Can you please explain a bit more on this.

**Comment by robsavoye** [comment]
Currently everything assume the XLS form basename is the same as the data extract, etc... That turns out to create problems in ODK with name conflicts in XPATH. So the new config file has the category as a keyword, and the value is the XLS form. The basename of the XLSForm is still used as the data extract filename. If the basename is an official OSM tag like "healthcare", the data extract needs to be named something else.

Currently there is only one XLSForm per category, but in the future there may be several. The frontend will need to use  make_data_extract.py:getChoices() to get the list of categories from the config file or the database. The database table for xlsforms will need a category field added.

**Comment by spwoodcock** [comment]
This could be solved by using Entities (tbc)
