### ISSUE TITLE
Basic dumb polygonization of tasks from OSM lines

### ISSUE THREAD

**Issue by ivangayton** [hotosm/fmtm#37]
Campaign Managers need to be able to define an AOI and get it chopped up into individual tasks. 

In the long run, we need this to be a powerful and flexible solution capable of delivering different results based on different contexts and task types; the plan is to institute a "feature bounty" for communities to contribute to this as described in [this document](https://docs.google.com/document/d/1wWu8WkRmFokO5naskexvTfUOiTfULv6Rz3-3O2g6KA0/edit?usp=sharing). However, in the meantime, we need to simply get the scaffolding up and a basic version of task-splitting working (in full recognition that this will, for most campaigns, require additional manual splitting but at least creates a starting point.

We have a manual algorithm using QGIS that can be automated, ideally all in PostGIS, but anything fully automated is fine. Here is a description of the algorithm in QGIS:

## Create the polygons
- The Campaign Manager creates a single polygon for the entire Area of Interest of the project.
  -  This can be done in QGIS, and we can easily implement it in Leaflet for a Web interface, as [per the example here of a tile scraper](https://github.com/HumanitarianStuff/tilehuria-flask) that allows users to define an AOI in a browser ([live demo at turkus.net](https://turkus.net/) at time of writing) but for now just assume Campaign Managers can create an AOI polygon in QGIS.
- Download all line features from OSM. This will mostly be a bunch of roads, waterways, and railways. We'll use these as cutlines.
- Turn the AOI polygon into a line. In QGIS this is `Vector` -> `Geometry Tools` -> `Polygons to Lines`. The line will still describe a polygon, but it'll be treated by the GIS system as a line whose start and end happen to be the same, which allows it to be merged with the layer of OSM lines (you can't merge lines with polygons directly).
- Merge the AOI polygon layer with the OSM line layer. In QGIS this is `Vector` -> `Data Management Tools` -> `Merge Vector Layers`. This produces a new line layer with both components.
  - In the future, this is a point at which we'll want to do a lot more to make these polygons sane and appropriate for field mapping. However, that's a task for later; either the Algorithm bounty mentioned above, or a separate development phase.
- Create polygons of all areas enclosed by the lines in the new layer. This is a bit like the old MS Paint bucket algorithm, which fills any area completely surrounded by lines. In QGIS, we open `Processing` -> `Toolbox, search the resulting pane with `polygonize` (found in `Vector Geometry` in the toolbox). Run the merged vector layer of the AOI and OSM lines through it (no need to check the `keep table structure of line layer` box), which produces a layer called `Polygons`.
- Save the polygon layer as a GeoPackage, because we need a unique ID for each polygon (saving it as a PostGIS layer will also do this; it doesn't matter how you get a UID for each enclosed polygon), but in QGIS saving it as a GPKG works well.
- Good idea to convert the UIDs into padded strings, like `1` becomes `0001` and so on. In QGIS, this can be done in the Field Calculator using the `lpad` function.
- Now you have a polygon layer. It's unlikely to be sufficiently evenly divided for sensible tasking, but it's a start, and can be refined from there either manually or with our eventual automated solution.

## Get the features and split them by task
- Download whatever features you're planning to digitize. If they're point features like most nodes labelled "Amenity" in OSM, good enough. If they're polygon (or even line) features, for the moment we need to convert them into centroids to work with ODK's Select from Map functionality. In QGIS  this is `Vector` -> `Geometry tools` -> `Centroids`.
- Join the UIDs from the polygon layer using `Vector` -> `Data Management Tools` -> `Join Attributes by Location`. This will add a column to the centroid layer, such that every centroid has a field corresponding to that of the task polygon it falls within.
  - There's some complexity around naming this column that I'll explain later, which relates to how the FMTM back end processes the tasks
- Split the centroids into multiple GeoJSON files using `Vector` -> `Data Management Tools` -> `Split Vector Layer`. Select the GeoJSON output format, and create a directory to contain the multiple files. It'll create one file per set of features in each polygon.

**Comment by robsavoye** [comment]
The initial implementation of this just generates a square grid, as this is needed for the project to work at all. This can be improved in the future, possible supporting multiple splitting schemes, but this will have to come later.

**Comment by spwoodcock** [comment]
See https://github.com/hotosm/fmtm-splitter
