### ISSUE TITLE
Create hotosm service account with access tokens

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#371]
Currently I am using three personal access token for:
- Github container registry login.
- fmtm docs.
- osm-fieldwork docs.

Instead we should have a service account in the HOTOSM Org, e.g. svchotosm.
This account should provide all access tokens for these repos.

**Comment by robsavoye** [comment]
What would be the next step to setup a project service account ? I agree we shouldn't be using anyone's personal accounts for the long term.

**Comment by spwoodcock** [comment]
We need an email on the hotosm.org domain, say admin@hotosm.org. I think sysadmin@hotosm.org may exist already, but not certain.

Then we just sign up to GitHub with that email, add to the hotosm org and create service tokens.

**Comment by robsavoye** [comment]
those might be too generic, so how about just fmtm@hotosm.org ?

**Comment by spwoodcock** [comment]
Ideal 👍

**Comment by spwoodcock** [comment]
Spoken with DevOps and they suggested using the sysadmin user, but they would provide the creds directly as environment secrets (we don't know the creds).

Prerequisite blocker see #786.
