### ISSUE TITLE
submissions REST API doesn't work

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#379]
Using the backend API directly on the dev server, I noticed that both
submissions/list-forms and submissions/list-app-users return a 404.

**Comment by varun2948** [comment]
@robsavoye for me both the api is working fine on project id 63 

![image](https://user-images.githubusercontent.com/37866666/235909006-065d64fa-2ac1-4f4a-ad27-96e61e9ed83c.png)
