### ISSUE TITLE
Implement Frontend

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#42]

**Comment by krtonga** [comment]
Associated with merged task: https://github.com/hotosm/fmtm/issues/28

Related to MAPPER FLOW: Mapper should be able to see a list of FMTM projects.

**Comment by krtonga** [comment]
Associated with task in progress: https://github.com/hotosm/fmtm/issues/38

Related to CODE QUALITY: Improve theming for react frontend.

**Comment by biomassives** [comment]
https://bionicjulia.com/blog/axios-wrappers-react-typescript 
im working with expected endpoints to prototype the oauth
