### ISSUE TITLE
Generate OSM data extract

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#46]
Add support for the backend to make a data extract from OSM data for ODK Collect. This will support the XLSForms in the odkconvert XLSForms library.

**Comment by robsavoye** [comment]
This program is actually part of the odkconvert project, but the backend needs to support creating this extract so it can be uploaded with the modified XForm.

**Comment by biomassives** [comment]
i see this in the codebase :+1: src/enviroment.ts

baseApiUrl: "https://api.fieldmappingtm.org"

getting to know what is in the code and where things are at.  what is placeholder, etc,  I can see that tests are being created by petya in the issues but dont see them in the package.json

**Comment by robsavoye** [comment]
On 2/15/23 13:09, G. Willson wrote:

> baseApiUrl: "https://api.fieldmappingtm.org 
> <https://api.fieldmappingtm.org>"

   That URL is now fmtm-api.hotosm.org. The actual data extract is made 
by my odkconvert project, which is a subtree under src/backend now.

> getting to know what is in the code and where things are at.  what is 
> placeholder, etc,  I can see that tests are being created by petya in 
> the issues but dont see them in the package.json

   Mu assumption is there is a lot missing from the package.json file.

	- rob -
-- 
Senior Tech Lead
Humanitarian OpenStreetMap Team
https://www.hotosm.org

**Comment by robsavoye** [comment]
As of #4783baf7, this now works.
