### ISSUE TITLE
Question : Why does Manage Category lead to Manage Projects page?

### ISSUE THREAD

**Issue by susmina94** [hotosm/fmtm#465]
![image](https://github.com/hotosm/fmtm/assets/108750444/12ec8af5-39a3-4f16-9505-2ffb18042b2a)

**Comment by robsavoye** [comment]
I don't think the Manage Category is needed, as when selecting a category during the create project phase, you have the option of uploading one. But it probably shouldn't go to the Explore Project page.

**Comment by varun2948** [comment]
i am removing the manage category button as it is not needed
