### ISSUE TITLE
Menus disappear when changing window width

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#490]
If you resize the browser window, the Explore Project, Manager Organization, and Manage Categories get truncated. They should problem rearrange to a vertical order.

**Comment by varun2948** [comment]
@robsavoye as the menu cant fit in the header I have transferred it into the hamburger menu as every webpage does if the screen is of less width. do you want me to show it on vertical order ?

**Comment by robsavoye** [comment]
No, this sounds fine.
