### ISSUE TITLE
Error downloading submissions

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#495]
For a new project which has no submissions, when you try to convert or download the submission, you get an error because there is no data. The error is: "raise BadZipFile("File is not a zip file")".

The bigger problem is it thinks it's processing submissions if you watch the log, which locks up the browser for a long time, and unable to go back to the Explore Projects page.

**Comment by varun2948** [comment]
@robsavoye on which exact page are you having issue for now its working on two pages that we have download option

**Comment by konishon** [comment]
I created a project and it had zero submissions. Then I proceeded to download the submission and the system froze. 
1. The downloads looked like they started 

![download](https://github.com/hotosm/fmtm/assets/11831955/b045a96a-d510-4b20-b40f-ff76dfc2d246)
2. I was also not able to access other pages in different tabs

![hang](https://github.com/hotosm/fmtm/assets/11831955/de06a1af-66ec-49ed-a935-6882f445e5ce)

@varun2948 does this help?
Here's the link to the project `https://fmtm.naxa.com.np/project/MTAwMTAwMA==/tasks/MTEwMDAwMDAwMDAwMTA=`
