### ISSUE TITLE
Drop the Debug Section

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#496]
The debug section in the FastAPI isn't needed anymore, it was for early stage development. All the functionality should be supported elsewhere in the backend.

**Comment by spwoodcock** [comment]
I had an endpoint in there to auto-populate five projects for testing, from the testdata dir with zips committed to the repo (although probably broken currently with all the changes).

It's to help testing when you spin up a fresh fmtm instance (particularly for contributors that may want to make small commits, but don't have zipped projects readily available to import).

Would it be useful to keep this one, or just go ahead and remove?

**Comment by nrjadkry** [comment]
I have removed this debug section in my latest pr. Waiting for @robsavoye

**Comment by nrjadkry** [comment]
I have removed this debug section in my latest pr. Waiting for @robsavoye

**Comment by robsavoye** [comment]
now that creating projects fully works, it's easier to do that than manually produce all the data files needed for the zip file.

**Comment by robsavoye** [comment]
Producing the zip files is actually pretty technical, but it got us started months ago. I have DEBUG enabled, which is why I still see this. We will definitely keep the backend code for processing the zip file, but I don't think we need to have this accessible from the UI anymore. We can delete the old zip files from the repo though, as they were mostly just used as a demo.
