### ISSUE TITLE
Generating Files is broken

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#497]
When creating a project, it fails to generate any files, so there are no QR codes. The error I see in the log is:
[WARNING] fastapi | generate_appuser_files:1206 | name 'xmlFormId' is not defined

**Comment by varun2948** [comment]
@robsavoye it is fixed u can have a look onto it as of now on the development server its working

**Comment by konishon** [comment]
QR code is also not generating for me, is this a related issue?
![QR](https://github.com/hotosm/fmtm/assets/11831955/c72dc061-a0ee-41a8-9fd3-7f243826c8df)


@varun2948

**Comment by varun2948** [comment]
@nrjadkry can u look into this project on the backend side if the qr is generated or not, as on the payload I don't see qr base64 string its empty string

**Comment by robsavoye** [comment]
I see a similar error with how the XForm ID is passed top the backend. Locally it didn't exist, now it's a type problem if I try the dev server.

**Comment by robsavoye** [comment]
I tracked this problem when running docker locally. The docker image was using osm-fieldwork 0.3.0, which was lacking changes. Updating osm-fieldwork to 3.1 to capture recent changes fixed the problems.
