### ISSUE TITLE
Integrate osmconvert scripts to retrieve submissions for validation

### ISSUE THREAD

**Issue by ivangayton** [hotosm/fmtm#5]
# Integrate osmconvert 
We should be able to use osmconvert (I'm not sure where @robsavoye keeps the code) to convert ODK submissions (which are basically CSV tables) into OSM XML. This should allow validators to download changesets from the FMTM as OSM XML directly and launch JOSM for validation and upload to OSM.

**Comment by robsavoye** [comment]
My code lives here: https://github.com/hotosm/odkconvert.git.

**Comment by ivangayton** [comment]
Perfect, thanks!

**Comment by robsavoye** [comment]
Other than launching JOSM with the output, this now in main. All submissions to a project are downloaded, and converted to an OSM XML file.
