### ISSUE TITLE
Support multiple Form formats

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#508]
Currently the frontend asks to upload an XForm, but expects an .xlsx file. This should support both .xls and .xlsx format for custom XLSForm definitions. This assume it'll be converted on the server side. This should also allow for an .xml file that doesn't need to be converted.

**Comment by varun2948** [comment]
i am expecting all type of file on the frontend input @nrjadkry has to make sure the backend supports all the file format you have listed and I change the name on "Upload XLS form to "Upload .xls/.xlsx/.xml Form"

**Comment by nrjadkry** [comment]
@robsavoye , we can close this issue. Please verify this.
