### ISSUE TITLE
Custom data extracts alongside custom XLSForm

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#509]
osm-fieldwork uses osm-rawdata to generate data extracts.
The `data_models/*.yaml` files define the SQL query that will be used.

Right now a custom XLSForm needs to be mapped to one of the existing data models (categories).

This works fine for a standard XLSForm, however, if we upload a custom XLSForm we need to also be able to specify a custom SQL query to get the data extract we want.

To facilitate this we need to be able to upload a `.yaml` file defining the SQL query alongside out custom XLSForm.

To do this we need:
- Backend: to pass the yaml config file to PostgresClient in osm-rawdata.
- Frontend: UI component to generate the yaml for a project (better UX).

The generated yaml is stored in the `project.form_config_file` table, then passed to osm-rawdata when generating the extract.

**Comment by nrjadkry** [comment]
@robsavoye getFeatures() in PostgresClient() class also needs to accepts sql query for this, since we are calling this function from fmtm.

**Comment by robsavoye** [comment]
The SQL queries are in osm-fieldwork.

**Comment by varun2948** [comment]
@nrjadkry @robsavoye we can close this aswell ?

**Comment by robsavoye** [comment]
No, cause although it's possible to upload a custom XLSForm now, it must be in one of the existing categories, like buildings or healthcare. To be fully custom, we should allow a project manager to upload the config file, which is a few lines of YAML that then turns into the various queries. Otherwise data extracts don't work. For example, think of a biologist out in the field mapping rare toad habitat. That kind of field survey will also benefit from FMTM.

**Comment by nrjadkry** [comment]
@robsavoye, should we ask user to upload the yaml file whenever they create a project and upload a custom form? Can the user create a config file by themselves?
Also, currently osm-fieldwork is accepting a xlsform. We might need to add another parameter in the to pass the yaml file.

**Comment by spwoodcock** [comment]
We should revive this as the potential long term solution for what Jankapur needed.

If a custom XLSForm is selected then the option should pop up for adding a custom SQL query too. We should think about the exact implementation, as sending raw SQL from the frontend to the backend is probably not a good idea.

For Jankapur this would solve the issue of needing both buildings and highways data extracts. We could have a single extract containing both.

**Comment by robsavoye** [comment]
I don't think we want to allow a raw SQL query. My though was to use the simple YAML format, and let osm-rawdata create the query and execute it. Documentation on the format is here: https://hotosm.github.io/osm-rawdata/yaml/. For this use case we could probably simplify it more.

**Comment by robsavoye** [comment]
For osm-fielkdwork, it currently expects to find the YAML files for the default queries in the data_models directory, so it will need to have support to pass one in that is not installed.

**Comment by spwoodcock** [comment]
This is perfect, thank you 🙏

**Comment by spwoodcock** [comment]
Backend done to support the YAML format.

However we still need:
- To think about the UX. A project manager can probably handle creating the YAML without issues, but it would be nicer if they can do it via a UI.
- The UI component to facilitate this.

It's quite a complex structure to handle in a UI though and hard to validate:

```yaml
select:
  - osm_id: id
  - version
from:
  - nodes
  - ways_poly
where:
  tags:
    - building: not null
      amenity: not null
      tourism: not null
keep:
  - building
  - building:levels
  - building:material
  - roof:material
  - roof:shape
  - roof:levels
  - cuisine
  - amenity
  - convenience
  - diesel
  - version
  - name
  - name:en
```

The user would need to input:
1. The tags to filter on, i.e. the `where` key.
2. The tags to keep in the extract, i.e. the `keep` key.

**Comment by spwoodcock** [comment]
This is possible in the current prod:

Custom XLS:
![image](https://github.com/hotosm/fmtm/assets/78538841/9f95a10b-09c3-4955-8786-8a2b54ea7a49)

Custom extract:
![image](https://github.com/hotosm/fmtm/assets/78538841/cf99daa6-52cb-48c4-b8ee-0633b0660897)
