### ISSUE TITLE
Deleting projects doesn't work

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#527]
When trying to delete a project using the backend API, I get this error:
  "detail": "Error creating project on ODK Central: unsupported operand type(s) for +: 'NoneType' and 'str'"

**Comment by robsavoye** [comment]
I still can't delete projects using the backend. I get a 500 status code trying to delete projects I created.

**Comment by nrjadkry** [comment]
@robsavoye
I needed to enter a small alter table query in the xlsforms table  to fix this issue. I have done that. Please review this issue. This should now work.

**Comment by robsavoye** [comment]
I don't see a PR for your bug fix.

**Comment by nrjadkry** [comment]
@robsavoye There was no issues in the code, just needed to execute alter table query. So, no PR.

**Comment by robsavoye** [comment]
Ok, I assume this has been done on the dev server ? I can recreate my local database.

**Comment by robsavoye** [comment]
This now works for me.
