### ISSUE TITLE
Add favicon to frontend static files for Firefox

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#540]
## Issue

- Currently we don't have a favicon for the frontend (to display in the browser tab).
- It would look more professional imo if we had a HOT favicon.

## Solution

- Add a `public` dir configured in webpack to service static assets from.
- There should be a `favicon.ico` in that directory.
- Browsers will pick up and display the favicon.

**Comment by varun2948** [comment]
@spwoodcock i am seeing the favicon on my side . is it not visible for you ?
![image](https://github.com/hotosm/fmtm/assets/37866666/2165ff5b-b798-4c26-a24b-1fae925999ee)

**Comment by spwoodcock** [comment]
Hey @varun2948!

You are right, the favicon is present on chromium browsers I am using. 

This seems to only be an issue in Firefox.

I will investigate further.

**Comment by spwoodcock** [comment]
The issue is that we use favicon.png, not favicon.ico.

All browsers support .ico, but .png support is not guaranteed. 

I think we should add a .ico file to solve this.

(happy to do it when I get time)

**Comment by varun2948** [comment]
oh i see the issue is on firefox browser I guess I will try to fix it for firefox
