### ISSUE TITLE
Add support for uploading custom data extract

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#541]
When creating a project, support should be added to the create project page to upload a custom data extract after uploading the project AOI. This will support doing custom SQL queries not supported by the data  models, as well as work around bugs in the field with data extracts.

**Comment by nrjadkry** [comment]
@robsavoye , please review this too.

**Comment by robsavoye** [comment]
Review what ? This is no patch in this PR. :-)

**Comment by nrjadkry** [comment]
This was in the previous pr you have merged. Now we can upload custom data extracts from frontend too.
