### ISSUE TITLE
Upload Custom Form returns a blank error in UI and 400 error in console

### ISSUE THREAD

**Issue by konishon** [hotosm/fmtm#544]
# Description 

![image](https://github.com/hotosm/fmtm/assets/11831955/ffd6eaf6-0ca6-4f61-8988-4b9f621891de)
![image](https://github.com/hotosm/fmtm/assets/11831955/ceedd26b-72ff-4cca-955e-17ef9899c3a0)

**Comment by konishon** [comment]
Here's the link to the form https://drive.google.com/file/d/1ejH6JA6ILMucDgY-fKAwNNEIkjMdobDC/view?usp=sharing

**Comment by robsavoye** [comment]
Did you specify an existing category for the custom XLSForm ?
