### ISSUE TITLE
Project deletion frontend implementation

### ISSUE THREAD

**Issue by konishon** [hotosm/fmtm#545]
**Is your feature request related to a problem? Please describe.**
I encountered an issue while creating a project where the form upload failed,(#544) resulting in a project being created without a form. However, this project is not useful to me as it lacks the necessary form. I was expecting the project completion form to continue the process, but instead, it redirected me to the project details page. Therefore, I would like to have a delete project feature to remove this unnecessary project from the system

- I created a project but need to change the grid size. Initially, I intended to send only one surveyor, but now I plan to send multiple surveyors, which requires adjusting the grid size accordingly.

**Describe the solution you'd like**
For the project created without a form due to a failed upload, I would like to have a delete project feature that allows me to remove this project completely from the system. This way, I can eliminate any trace of the project without a form.

I would also like to have a project edit feature that enables me to modify the grid size of the created project. This way, I can adjust the grid size to accommodate the multiple surveys I intend to send, ensuring proper alignment and display of the survey content. This modification is necessary to adapt the project to my updated requirements and optimize the survey presentation.

**Describe alternatives you've considered**
An alternative solution for changing the grid size could be to create a new project with the desired grid size and manually transfer the survey content. However, this approach is time-consuming and prone to errors. Having a project edit feature to modify the grid size directly would be a more efficient and convenient solution.

**Additional context**
Related to #544

**Comment by robsavoye** [comment]
Assuming this now works on the backend, we do need some kind of project management functionality to delete or archive projects. Note that deleting a project from FMTM should also archive the ODK Central project as well. Central keeps archived projects for 30 days before they're totally gone.

**Comment by spwoodcock** [comment]
The is an endpoint `/delete/{project_id}` that can be used on the backend.
It should be thoroughly tested and implemented on the frontend.

However, this is blocked until #243 is complete, as we can't allow unauthenticated users to delete projects (without knowing if they are a project admin).

**Comment by spwoodcock** [comment]
Checking the SQLAlchemy schema we have DROP CASCADE in place for all related tables, so deleting a project should delete project info, tasks, associated user role entries 👍 

No point adding an archive feature until later - definitely useful, but not critical for now (org admins should just be careful).

I will add a button to the frontend to call this endpoint and we are set 😄
