### ISSUE TITLE
Enable Editing of Project Basic Details, Location, Grid Size, and Form

### ISSUE THREAD

**Issue by konishon** [hotosm/fmtm#551]
# Is your feature request related to a problem? Please describe.
When managing projects, I need the ability to edit the basic details, location, grid size, and project form after the project has been created. Currently, there is no option to modify these crucial elements once the project is set up, which limits my flexibility and requires unnecessary workarounds.

# Describe the solution you'd like
I would like to have the following features for project editing:

1. Edit Project Basic Details: Enable the modification of project basic details such as project name, description and any other relevant information. 

2. Edit Project Location and Grid Size: Provide the ability to edit the project location and adjust the grid size. This feature ensures that I can accurately reflect the project's physical location and make necessary changes to the grid size to accommodate the number of surveyors and optimize survey content alignment.

3. Edit Project Form: Allow editing of the project form, including adding, modifying, or removing form fields.

# Describe alternatives you've considered
Currently, the only alternative solution for editing these project elements is to create a new project from scratch.

**Comment by robsavoye** [comment]
This is also related to: https://github.com/hotosm/fmtm/issues/66, so it's been on the TODO list.

**Comment by robsavoye** [comment]
Actually your issue has much more information than #66, so I'm going to close that one, and reopen this one.

**Comment by spwoodcock** [comment]
@manjitapandey project editing of basic information has been added right? 

Updating the project AOI, task areas, xlsform, and data extract, are more difficult tasks as we need to update all the info in ODK Central and generate new access tokens. In which case the old xforms, appusers, and tokens would be invalidated. 

Outside of editing basic info for a project and user roles, I think the user may as well just delete the project and create a new project (the process has been streamlined significantly anyway).

Any other thoughts?

**Comment by robsavoye** [comment]
Not all editing changes require regenerating all the files. For example, if somebody edited the instructions, that doesn't require regenerating anything. The only thing that should force new xforms for example, would be changing the XForm. App users probably won't change unless tasks are regenerated.

**Comment by manjitapandey** [comment]
Yes, The project editing adding the basic details like Project name, Description, Odk credentials and XLS forms has been added. 
![image](https://github.com/hotosm/fmtm/assets/97273021/73b6dc1d-9617-4356-943d-36776ee219e0)
![image](https://github.com/hotosm/fmtm/assets/97273021/b888a1d5-8454-45e2-b9f9-26c3a7438824)

**Comment by spwoodcock** [comment]
> Not all editing changes require regenerating all the files. For example, if somebody edited the instructions, that doesn't require regenerating anything. The only thing that should force new xforms for example, would be changing the XForm. App users probably won't change unless tasks are regenerated.

If we change the AOI or data extract, we probably also need to regenerate the task areas, so would need to regenerate QR codes
