### ISSUE TITLE
Task splitting is broken

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#554]
In the current development branch task splitting is broken. You can see in this screenshot it looks like splitting worked fine.

![Screenshot from 2023-06-29 16-04-03](https://github.com/hotosm/fmtm/assets/71342768/b1de2cc8-8d0e-4583-ada5-d575ed0b11e0)

But when you click the Next button, there is only one task. Also note the count is wrong, there should be 95 tasks, not 6494.
![Screenshot from 2023-06-29 15-40-25](https://github.com/hotosm/fmtm/assets/71342768/45611c2d-4938-4a42-82da-1f01832e73bc)

This is a blocker, as it's broken on the development server too.

**Comment by varun2948** [comment]
@robsavoye we can close this right ?

**Comment by robsavoye** [comment]
yes, it's fixed.
