### ISSUE TITLE
Modification of AOI Splits: Enhancing AOI Split and Feature Set Management with Download and Upload Functionality

### ISSUE THREAD

**Issue by konishon** [hotosm/fmtm#564]
**Is your feature request related to a problem? Please describe.**
Users currently do not have a straightforward way to obtain copies of the AOI split and feature set artifacts generated by the FMTM system. This lack of download functionality restricts users from accessing and utilizing these artifacts outside of the FMTM system. Additionally, users are unable to upload modified versions of the AOI split and feature set, limiting their ability to make customized adjustments.

**Describe the solution you'd like**
1. Enable users to upload modified versions of the AOI split and feature set.
2. Provide the AOI split as a downloadable GeoJSON file and the feature set as a separate file format (e.g., CSV, GeoJSON).

**Describe alternatives you've considered**
An alternative approach would be to develop an in-app editing tool within the FMTM system. However, implementing a full-fledged editing tool can be complex and time-consuming. By providing download and upload functionality, users can leverage existing external tools, such as QGIS, which are widely used and provide robust editing capabilities. This approach allows users to work with familiar tools and workflows while reducing the development effort required for an in-app editing feature.

**Comment by robsavoye** [comment]
We discussed this in a meeting late last night, and being able to upload, download, or change all the required files is a high priority right now. Since almost all field mapping projects use their own data models, the goal is to let them manually change anything they want, but still use FMTM for the ODK data processing and task assignment functionality.
