### ISSUE TITLE
Improved Auto-Fill for ODK Central URL and Username Fields

### ISSUE THREAD

**Issue by konishon** [hotosm/fmtm#566]
**Is your feature request related to a problem? Please describe.**
Entering the ODK Central URL and username every time when accessing the FMTM platform can be inconvenient and time-consuming. This repetitive task becomes a hassle for users who frequently use the platform.

**Describe the solution you'd like**
Instead of building a new feature within the FMTM platform, I propose leveraging the auto-fill option provided by web browsers. The desired solution includes the following:

1. Enable auto-fill for the ODK Central URL field: When users start typing the URL, the browser should suggest previously used URLs based on the user's browsing history. This feature saves time by eliminating the need to manually enter the complete URL every time.

Example:
In most browsers, you can make your browser display values previously entered in input fields by giving a name to the input. For example:

```html
<input type="text" id="centralURL" placeholder="ODK Central URL" name="centralURL">
```

2. Enable auto-fill for the ODK username field: Similar to the URL field, the browser should remember the username previously entered by the user. As the user starts typing, the browser should suggest and auto-fill the username based on past entries, saving time and effort.

Example:
It may vary depending on the browser and user privacy settings and sorts, and it should be on by default, but try adding `autocomplete="on"` to your input tag.

```html
<input type="text" id="username" placeholder="Username" name="username" autocomplete="on">
```

By enabling the auto-fill functionality of the browser for these two fields, users can easily access the FMTM platform without the hassle of typing the ODK Central URL and username repeatedly.

Reference: https://stackoverflow.com/questions/16444496/make-text-input-fields-remember-previously-entered-data 

**Describe alternatives you've considered**
An alternative approach would be to include a "Remember Me" checkbox or a "Save Login Credentials" option within the FMTM platform itself. However, leveraging the auto-fill feature provided by web browsers is a widely-used and established method that users are already familiar with. This approach also eliminates the need for additional development work on the FMTM platform.

**Comment by robsavoye** [comment]
I'd also like to see this feature, as I'm creating many projects when I'm doing testing.

**Comment by robsavoye** [comment]
A patch to improve this has been deployed to the development server, please test it. I'll be testing it too, but it's your bug report. :-)
