### ISSUE TITLE
Enhanced GPS Functionality and Location Permission Handling in Mapping Application

### ISSUE THREAD

**Issue by konishon** [hotosm/fmtm#571]
**Is your feature request related to a problem? Please describe.**
Currently, when clicking on the GPS icon in the mapping application, it does not function as expected. It only shows a loader briefly and does not provide the user's current location. This behavior can be confusing and frustrating for users who expect to see their location on the map. 

**Describe the solution you'd like**
I would like the GPS functionality to be enhanced with the following features:
1. If the user is clicking on the current location icon for the first time, show them the default dialog to ask for location access permission.
![image](https://github.com/hotosm/fmtm/assets/11831955/f3704810-9861-4c08-a314-c7c4853c0fff)

2. Check if the user has location permission enabled. If permission is granted, display the user's current location as a blue dot on the map.

3. If the user had previously selected "No" when asked for GPS location permission, display an info window or message saying "FMTM does not have the permission to display your location in 'Learn Mode'."
![image](https://github.com/hotosm/fmtm/assets/11831955/9b8ab97f-2863-41e9-b7c7-21b7ab6e59a0)

**Describe alternatives you've considered**
One alternative solution could be to display a generic error message when the GPS icon is clicked, indicating that the location cannot be accessed. However, this would not provide specific instructions or information to guide the user in enabling location permissions or understanding the implications of their choice.

**Additional context**
Example for solution 1
![image](https://github.com/hotosm/fmtm/assets/11831955/f3704810-9861-4c08-a314-c7c4853c0fff)

Example for solution 3. 
![image](https://github.com/hotosm/fmtm/assets/11831955/0fa24f00-608a-4c7b-9d07-36999a890fbc)

![image](https://github.com/hotosm/fmtm/assets/11831955/9b8ab97f-2863-41e9-b7c7-21b7ab6e59a0)

Example for solution

**Comment by ivangayton** [comment]
In the original prototype Kristen built, we had this sorted. The site would display a popup asking for permission to use location, and then it worked.

Perhaps we can look at her old code?
