### ISSUE TITLE
Improving contribution guidelines

### ISSUE THREAD

**Issue by konishon** [hotosm/fmtm#573]
1. **Tagging "Good First Issue"**: To encourage new contributors, it's helpful to add a "good first issue" tag to tasks that are relatively easy to complete. These issues should be well-defined and require minimal prior knowledge of the project.

2. **Submitting a Pull Request (Server and Client Components)**:
   - Provide step-by-step instructions on how to fork the repository.
   - Explain how to clone the forked repository locally.
   - Detail the process of creating a new branch for the proposed changes.
   - Describe how to make the necessary changes and test them locally.
   - Explain the process of pushing the changes to the forked repository.
   - Instruct contributors on how to submit a pull request from their forked repository to the main repository.
   - Emphasize the importance of providing a clear description of the changes made in the pull request.

3. **Code Style Guides Document**: It's crucial to maintain a consistent code style throughout the project. Include a document or a reference to an existing code style guide that outlines the preferred coding conventions, formatting, and best practices for the server and client components. This will help contributors align their code with the project's standards.

4. **Work in Progress Pull Requests**: Encourage contributors to mark their pull requests as "work in progress" if they are still developing or refining the changes. This helps prevent premature merging and allows for early feedback from maintainers and other contributors.

5. **Review Process**: Outline the review process for pull requests, including expectations for maintainers and contributors. Explain how feedback will be provided, and encourage contributors to actively participate in discussions and address feedback promptly.

6. **Code of Conduct**: Include a code of conduct that sets the expectations for respectful and inclusive behavior within the community. Provide information on how to report violations and ensure that all contributors adhere to the code of conduct.

**Comment by spwoodcock** [comment]
It would be good to ask contributors to run the existing tests (+ providing instructions on how) to see if their edits break existing functionality.

**Comment by spwoodcock** [comment]
I think everything here has been fulfilled in one way or another.
