### ISSUE TITLE
Support mbtile, sqlite, pmtile basemap generation

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#586]
Imagery basemaps are very useful in the field when the map data isn't very complete. Osm-fieldwork has a **basemapper.py** program which downloads map tiles from several different sources. It creates an XYZ map tile store on disk, and using a boundary polygon, extracts the tiles that fit in that boundary. It can write both .mbtiles for ODK Collect, and sqlitedb files for Osmand. Both output formats should be supported.

**EDIT** mbtiles have been implemented. We still need mbtile and pmtile at some point.

**Comment by spwoodcock** [comment]
Blocker #693

For reference:

- This can be handled nicely in the background via a separate worker such as celery.

- The files need to persist across container restarts, meaning we should add a docker volume to the compose stack for storing them.

**Comment by manjitapandey** [comment]
The .mb tiles for odk collect has been implemented and supported. but the sqlitedb files for Osmand is still remaining. I wanna know what is the significance of implementing sqlitedb files for Osmand ? How important is it for our FMTM project?

**Comment by manjitapandey** [comment]
The .mb tiles for odk collect has been implemented and supported. but the sqlitedb files for Osmand is still remaining. I wanna know what is the significance of implementing sqlitedb files for Osmand ? How important is it for our FMTM project?

**Comment by robsavoye** [comment]
Osmand is often used to navigate to or in the area people are mapping. Since it uses the same exact tiles as the mbtiles, it's only a single option to specify the output format. While it is possible to do this manually using osm_fieldwork's BaseMapper class, it'd be nice to see this in FMTM as well. Not the highest priority right now though.
