### ISSUE TITLE
Project Info page has Nan% Completed instead of an integer

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#588]
![Screenshot from 2023-07-11 09-30-57](https://github.com/hotosm/fmtm/assets/71342768/a5cb59d3-1142-4d35-b2d9-d497e653fac8)

**Comment by nrjadkry** [comment]
@varun2948 This happens if we have 0 features in the task and when the submissions count is also 0.  0/0 gives nan

**Comment by robsavoye** [comment]
I'd think it would be easy to trap that condition, and force Nan% to be 0%.

**Comment by varun2948** [comment]
already implemented this @robsavoye
