### ISSUE TITLE
Add a delete button to the Edit Project page

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#596]
It would be nice to be able to delete projects, since I'm cresting many for testing. While this is possible from the backend, it'd be better to be able to do this using the front-end. I'd assume that the Edit Project page would be the place to add this.

**Comment by nrjadkry** [comment]
We don't have user roles and permissions as of now. So, is this good to have that feature now? Unauthorized users might delete the real projects which we don't want to be deleted. I guess We should restrict backend api too.

**Comment by robsavoye** [comment]
You have a point. Since I can do this through the backend, we shouldn't add this to the UI till we implement roles.

**Comment by susmina94** [comment]
Yes, this will be introduced with the user roles implementation so closing this for now.
Noted down in the document.
