### ISSUE TITLE
Choose Area as Tasks doesn't work

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#598]
I'm not 100% sure what **Choose Area as Tasks** is actually supposed to do, but assume it's to use the entire project AOI as a single task. Selecting this splitting option however generates this error:

![Screenshot from 2023-07-12 08-34-32](https://github.com/hotosm/fmtm/assets/71342768/a516a93b-fa16-4551-babf-2263f4da2541)

**Comment by nrjadkry** [comment]
@robsavoye Choose areas as tasks can be used when we have multiple polygons in the project area and we want to use those polygons as the task polygons. (When we don't want to divide aoi by square, we would want to use choose areas as tasks)


And for the issue, I will look into it.

**Comment by robsavoye** [comment]
So Choose areas as tasks is where a custom task polygons file gets uploaded ?

**Comment by varun2948** [comment]
yes @robsavoye we select choose areas as task when we are uploading multipolygon

**Comment by robsavoye** [comment]
Right now if I select this option, it does nothing. I get one large task that is the project AOI. Is this where the custom task polygons get uploaded ? If so, it needs a way to put in the filename.
