### ISSUE TITLE
Mouse Stuck on Uploaded AOI in FMTM

### ISSUE THREAD

**Issue by ArbyC** [hotosm/fmtm#599]
Description:
When using the FMTM tool, I encountered an issue where my mouse pointer became stuck when clicking over the uploaded AOI (Area of Interest) on the interface. The mouse cursor did move freely and seemed to be locked onto the AOI, making it hilariously difficult to navigate or interact with other elements of the application.

Steps to Reproduce:

Open FMTM application.
Upload an AOI file, possibly a multi polygon.
Click and drag on the polygon boundary to reshape it.
Double click on any location. 

Expected Behavior:
The polygon should be reshaped and mouse freed from the snap.

Actual Behavior:
The mouse cursor gets stuck or locked onto the click location and drags the map when moved freely. It becomes difficult to interact with other elements of the application or perform any actions.

Additional Information:
Operating System:  Windows 11
Web browser (if applicable):  Google Chrome 

Possible Workaround:
The mouse moves freely if next button is pressed.

Please investigate this issue and provide a fix as soon as possible. If any further information is needed, feel free to reach out for clarification. Thank you for your attention to this matter.

**Comment by robsavoye** [comment]
Just to be clear, was this using the dev server at Naxa, the production one at HOT, or a local docker container ? I assume you meant the dev server.
