### ISSUE TITLE
Splitting an AOI into individual tasks

### ISSUE THREAD

**Issue by ivangayton** [hotosm/fmtm#6]
# Splitting an Area of Interest (AOI) into individual tasks

Choosing how to divide an area into tasks for field mapping is an interesting challenge. The [HOT Tasking Manager](http://tasks.hotosm.org/) for remote mapping divides an area of interest into a grid of squares. Remote mappers can use their computer screen to float virtually in the air above their task area, but field mappers must physically visit every point in their task area! Crossing rivers, railways, and trunk roads is inconvenient and sometimes dangerous. Therefore a grid of squares—which ignores physical access issues—is not great for field mapping.

We would like to evaluate different automated strategies to divide an Area of Interest into individual tasks for field mapping. This problem really has two distinct parts:
- What are the most convenient shapes for subdivisions for given types of field mapping tasks?
- How can we automate subdivision into those shapes, in a way that works and produces a reasonable result for many different settings?

[This document](https://docs.google.com/document/d/1wWu8WkRmFokO5naskexvTfUOiTfULv6Rz3-3O2g6KA0/edit?usp=sharing), which describes a crowdsourcing campaign to implement a good algorithm (an idea that we're proposing to help involve a wide range of community developers and volunteers), also describes the problem in detail, as well as presenting some ideas for addressing it.

**Comment by robsavoye** [comment]
This works now.
