### ISSUE TITLE
Optimise PWA for low connectivity environments 

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#611]
**Is your feature request related to a problem? Please describe.**
- FMTM may be used in areas of poor connectivity.
- Ideally it should still work well if the connection is intermittent.

**Describe the solution you'd like**
- Creating a manifest and service worker config file should make this a PWA (that can also be installed as an app, improving UX).
- A few caching options will be available for GET requests, keeping a subset of features available even if connectivity drops.
- Perhaps a banner should be displayed indicating the user is offline.
- Caching of POST requests may also be possible, deferring the sending of data until connection is restored.
- We could even go so far as to cache all tasks in IndexDB via something like Dexie.

**Additional context**
- A field campaign recently experienced issues with low connectivity.
- Loading the app before going to an area with no internet would be required.
- Caching tasks via IndexDB would also reduce load on the API. We would have to check there are no performance implications for users with older phone models and weigh up what is best.

**Comment by spwoodcock** [comment]
@varun2948 if you end up working on this.

For reference I have implemented something similar in an app of my own https://GitLab.com/mastweb/frontend.

I use dexie for persisting data in indexeddb and then caching strategies with workbox.

**Comment by varun2948** [comment]
@spwoodcock sure I will have a look at this, once I get freed up from the other features.

**Comment by spwoodcock** [comment]
We can further optimise where needed in the future, but the standard PWA should have sufficient caching for offline use.
Will be included with https://github.com/hotosm/fmtm/issues/1313
