### ISSUE TITLE
development branch is broken

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#635]
After updating my local git repository, and checking out the development branch, it has this bug, and doesn't start.

fmtm_map         | webpack compiled successfully
fmtm_main        | ERROR in ./src/utilities/CustomizedModal.tsx 9:0-44
fmtm_main        | Module not found: Error: Can't resolve '@mui/base/ModalUnstyled' in '/app/src/utilities'
fmtm_main        | 
fmtm_main        | ERROR in ./src/views/Tabbed.tsx 5:0-50
fmtm_main        | Module not found: Error: Can't resolve '@mui/base/TabsUnstyled' in '/app/src/views'
fmtm_main        | 
fmtm_main        | ERROR in ./src/views/Tabbed.tsx 6:0-58
fmtm_main        | Module not found: Error: Can't resolve '@mui/base/TabsListUnstyled' in '/app/src/views'
fmtm_main        | 
fmtm_main        | ERROR in ./src/views/Tabbed.tsx 7:0-58
fmtm_main        | Module not found: Error: Can't resolve '@mui/base/TabPanelUnstyled' in '/app/src/views'
fmtm_main        | 
fmtm_main        | ERROR in ./src/views/Tabbed.tsx 8:0-65
fmtm_main        | Module not found: Error: Can't resolve '@mui/base/ButtonUnstyled' in '/app/src/views'
fmtm_main        | 
fmtm_main        | ERROR in ./src/views/Tabbed.tsx 9:0-72
fmtm_main        | Module not found: Error: Can't resolve '@mui/base/TabUnstyled' in '/app/src/views'
fmtm_main        | 
fmtm_main        | webpack compiled with 6 errors
fmtm_api         | 23-07-26 17:58:47.755 [DEBUG] app.main | startup_event:126 | Starting up FastAPI server.

**Comment by varun2948** [comment]
@robsavoye did u try rebuilding the whole docker? "docker-compose build"

**Comment by robsavoye** [comment]
yes, of course. :-) I usually do a docker-compose down -v, and then docker-compose build --no-cache. I deleted my source tree and branches and started over, so this error is now gone, but replaced by a different error when running locally. While localhost:8000 accesses the backend fine, localhost:8080 just hangs, and I never get the home page. It looks like the frontend has stopped talking to the backend.

**Comment by varun2948** [comment]
@robsavoye can u now again pull development branch and let me know did it got fixed?

**Comment by robsavoye** [comment]
The previous error I "fixed" by deleting my source trees and starting over, so I assume it was from a bad merge. The current problem with localhost:8080 is still there, I never get to the home page, it just spins. I assume this is caused by using localhost instead of fully qualified domain names.

**Comment by varun2948** [comment]
@robsavoye i have configured pwa setting to remove the reset functionality can u rebuild the docker as everything right now seems fine on both of our end.

**Comment by robsavoye** [comment]
In a clean merge of the development branch to main, I still get this error when running docker locally.

**Comment by robsavoye** [comment]
after updating the lock file, this now works. It should have been done by docker, but for some reasons that wasn't working.
