### ISSUE TITLE
Irregular size of project boxes.

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#648]
**Describe the bug**
the size of box is not regular, some are longer than others. i will prefer to make every boxes of equal regular size.

**Screenshots**
![FireShot Capture 211 - Field Mapping Tasking Manager - fmtm naxa com np](https://github.com/hotosm/fmtm/assets/97273021/b95a514e-67fd-4329-af2a-ae9fa31a53b8)
 In this image, the box of project number 25 is slightly longer than others.

**Comment by nrjadkry** [comment]
@varun2948 This is the design issue. I

**Comment by susmina94** [comment]
This has also been incorporated with the new UI design.
Thank you for your keen concerns.
