### ISSUE TITLE
No form is seen when form is downloaded in mobile (Kobo collect) by scanning Qr code.

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#649]
**Describe the bug**
No form is seen when form is downloaded in mobile (Kobo collect) by scanning Qr code.

**Screenshots**

![Screenshot_20230731_173439_ODK Collect](https://github.com/hotosm/fmtm/assets/97273021/2194b9eb-0623-4407-8ed4-f3bd3b3786b1)

![Screenshot_20230731_173448_ODK Collect](https://github.com/hotosm/fmtm/assets/97273021/4bffdcc9-dc7b-4c13-bcc6-05dbb2641c77)

**Smartphone (please complete the following information):**

- Device: [e.g. samsung m12]

**Comment by robsavoye** [comment]
You have to use ODK Collect, as Kobo Collect is lacking the select_one_from_file feature used by FMTM to load the OSM data extracts.

**Comment by manjitapandey** [comment]
Its the same in both odk and kobo. no form can be seen

**Comment by nrjadkry** [comment]
@manjitapandey can you provide us which project are you using?

**Comment by manjitapandey** [comment]
https://fmtm.hotosm.org/project_details/MTEwMA==
