### ISSUE TITLE
List all tasks in menu and on interactive map

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#65]
The frontend must list all the tasks in a menu and an interactive map. This needs to allow the end user to select a task to map, In addition, the display should also include the task status.

**Comment by petya-kangalova** [comment]
@prasidha1 thank you for expressing interest in volunteering and contributing to this project!! It is much appreciated. On dependency to start working on tasks is that projects need to be set first #64.

Happy to speak and @robsavoye  can add more details.

**Comment by varun2948** [comment]
@robsavoye i guess this is also somewhat completed ?

**Comment by prasidha1** [comment]
Hi team,

This is complete from my end.

Thanks and Regards
Prasidha
