### ISSUE TITLE
editing the organisation name and info

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#651]
**Is your feature request related to a problem? Please describe.**
once the organisation name and info related are set there is no case to edit them later.

**Describe the solution you'd like**
it would be better if the organisation name could be edited later by only the person who created the organisation. and also edit other detail information.

**Comment by spwoodcock** [comment]
Is this done with the new organisation flow @manjitapandey ?

**Comment by manjitapandey** [comment]
https://dev.fmtm.hotosm.org/edit-organization/63
yes, now org admin can edit few fields for organisation. 
However, for now, there isn't proper place we can reach to this page. We are thinking of incorporating it when creating user individual page. 
we have to go through URL for now.
