### ISSUE TITLE
Description of project isn't seen 

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#653]
**Describe the bug**
the description cant be seen once we open the project though there is a description and dropdown arrow.

**Expected behavior**
the description written during project creation need to be seen after clicking in dropdown arrow 
**Screenshots**
![FireShot Capture 212 - fmtm - fmtm hotosm org](https://github.com/hotosm/fmtm/assets/97273021/e4f3b742-08d7-4362-9869-b3e2b12e5dae)

**Comment by susmina94** [comment]
This is being worked on with the new UI.
Thank you for your recommendations.
