### ISSUE TITLE
sign in problem

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#665]
**Describe the bug**
there is serious signin problem. a new user cant sign in. and if the user has already signed in and after signing out the account is automatically signed in if you click in any project.

**Screenshots**
https://vimeo.com/851533444/51f17c553c

**Comment by nrjadkry** [comment]
@manjitapandey . Please do a hard refresh (Ctrl + Shift + R) and look into it again. 
We have removed normal login and only have the osm login option.

**Comment by manjitapandey** [comment]
if you once sign out, it automatically signs in if you click on any project or click on create new project. this problem is still not solved.
