### ISSUE TITLE
Support drawing project boundary with mouse

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#67]
Projects can be created by uploading a GeoJson file, but often people want to be able to draw an area of interest using a mouse.

**Comment by cybraia** [comment]
Hi, is it a frontend work? If yes, please give me more details and I would be happy to work on this. Thanks!

**Comment by ivangayton** [comment]
Hi @cybraia, yes, this is front end work! (sorry for slow response; we're just onboarding a lot of developers right now so we're not as quick as we'd like to be). I'll add some details shortly.
