### ISSUE TITLE
polishing of task splitting algorithm

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#670]
**Describe the bug**
when we use task splitting algorithm on the basis of number of buildings, some zones includes only 1-5 buildings whereas some includes 100-150 buildings which is not consistent. moreover there comes lines within AOI, what does those lines imply?

**Expected behavior**
consistency in the number of behaviour also incorporate the building densities and number of buildings within the AOI

**Screenshots**
![FireShot Capture 223 - Field Mapping Tasking Manager - fmtm naxa com np](https://github.com/hotosm/fmtm/assets/97273021/3557b360-03bb-45ed-92a6-24890916a746)

**Comment by robsavoye** [comment]
The task splitting algorithm is currently being improved. The code has been migrated to a python module,
https://github.com/hotosm/fmtm-splitter, which is easier for testing the changes efficiently. Pretty soon this wil get merged into the backend, replacing the existing code.

**Comment by susmina94** [comment]
@manjitapandey I think we can close this issue too.
Since we are working in improvising the algorithm.
