### ISSUE TITLE
form order in odk collect

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#672]
**Describe the bug**
when we download form , the sequence of form in kobo collect is random(not in the sequence that we uploaded)

**Comment by robsavoye** [comment]
FMTM only works with ODK Collect, not Kobo Collect. Kobo Collect needs to implement the select_one_from_file feature.

**Comment by ivangayton** [comment]
Normally this should be sorted simply by waiting 3 months; Kobo Collect is just ODK Collect with the logos and default server URLs changed, and it gets updated every 3 month straight from the ODK Collect repo.

[The Kobo Collect repo](https://github.com/kobotoolbox/collect) shows that there are only a few changes from ODK Collect, none of which should substantially alter the function (look at the `10 commits ahead` for a list of the changes).

For now, we can inform users "If something doesn't work in Kobo Collect, please install ODK Collect, but anything that works in ODK Collect will work in Kobo collect in a maximum of three months."

**Comment by manjitapandey** [comment]
solved
