### ISSUE TITLE
Support uploading and downloading of files

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#68]
There are multiple files associated with each task. A QR code, a possible data extract from OSM, other external data files used by ODK Collect. Each project and task also has a boundary. It needs to be possible to both upload and download individual files, or groups of files. Downloads of submissions may also have attached media files like photos or audio that need to be downloaded as well.

**Comment by biomassives** [comment]
concept: https://www.bezkoder.com/material-ui-file-upload/#Rest_API_for_File_Upload_Storage

**Comment by robsavoye** [comment]
I just pushed a PR that implements this for some files on the backend. Once the PR is approved, it'll extract either the project or task boundaries from the database and send a GeoJson file to the frontend. This can then be used for display or downloaded to disk.

What is missing from the issue now is the uploading and downloading of media files.

**Comment by robsavoye** [comment]
Since I just created an issue for uploading custom task boundaries as a multi-polygon, that will need to be a separate operation from  uploading XForms and data extracts.

**Comment by prasidha1** [comment]
Sure Rob

**Comment by varun2948** [comment]
@robsavoye can we close this or is this still have something ?

**Comment by prasidha1** [comment]
Hi team,

This is not complete by me.

Thanks and regards
Prasidha

**Comment by varun2948** [comment]
It is completed
