### ISSUE TITLE
Number of contributers

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#682]
**Describe the bug**

The project's landing pages show the number of tasks submitted as the number of contributors which is confusing. For example the Rwanda Buildings Assessment shows 238 contributors, but we had only 27 contributors.

**Expected behavior**
Clear and countable number of contributers as in tasking manager

**Screenshots**

![FireShot Capture 229 - fmtm - fmtm hotosm org](https://github.com/hotosm/fmtm/assets/97273021/e4c5ac9f-2ab8-47bd-9938-204ad775d2f4)

**Comment by manjitapandey** [comment]
@robsavoye any idea on what can we do to solve this issue?
P.S. odk collect doesn't need user login so anyone can scan QR code and start mapping, How can we track the number of contributers in this situation?

**Comment by susmina94** [comment]
I think introducing the user roles and permissions will avoid this issue.
@manjitapandey we can close this as of now.
Cause it's on our to do list already
