### ISSUE TITLE
the popup with QR code covers the tasks

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#683]
**Describe the bug**
When you click on a task, the popup with the QR code covers the tasks. It would be good if the popup does not cover the tasks, may it can be displayed in a side panel outside of the map window

**Expected behavior**
It would be good if the popup does not cover the tasks, may it can be displayed in a side panel outside of the map window

**Screenshots**
![FireShot Capture 230 - Field Mapping Tasking Manager - fmtm naxa com np](https://github.com/hotosm/fmtm/assets/97273021/370841ae-6f0e-4030-8a59-34eaf291cd4f)

**Comment by susmina94** [comment]
It's fine for now.
