### ISSUE TITLE
Conversion of mapped data

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#684]
**Describe the bug**
It is currently not possible to access the mapped data. It is possible to download the csv and the JSON files, but the Convert button (which should be able to convert the data into OSM files is not working).

**Comment by robsavoye** [comment]
This should be enabled as of this morning, I approved the PR.

**Comment by manjitapandey** [comment]
the issue is not solved, the clicking on convert shows no change.

**Comment by susmina94** [comment]
The new package needs to be pushed for this to be tested.
