### ISSUE TITLE
Converting OSM layers into point-only GeoJSON for ODK

### ISSUE THREAD

**Issue by ivangayton** [hotosm/fmtm#7]
# Converting OSM layers with points and polygons into point-only GeoJSON for ODK

ODK Collect, at this moment, only allows `Select_one_from_file` (select from map) from point-only layers. Therefore if a layer of features to be tagged, such as buildings, contains mainly polygons, it is necessary to convert those polygons into centroids to make them available to ODK Collect users.

This is really trivial in QGIS (just use the `Vector` -> `Geometry tools` -> `Centroids` tool), but in PyGDAL it turns out to be rather complicated and messy; [the default solution ](https://www.giserdqy.com/ogr/30345/#Save_centroids_of_input_Layer_to_an_output_Layer) seems to involve a lot of iteration to copy over attributes, when all we nominally want is to replace the polygon geometry with point geometry.

There are a lot of ways to attack this problem, and probably many of them would be fine, but we do need to simply pick one and go with it. I'm guessing the most straightforward option will be to use [PostGIS's ST_Centroid](https://postgis.net/docs/ST_Centroid.html) function; we already plan to have the geometry in PostGIS so manipulating it with PostGIS's native tools seems sensible.

Otherwise, implementing the disgusting iterated solution above would probably work.

**Comment by robsavoye** [comment]
Check out https://gitlab.com/rsavoye/xforms/-/blob/main/Makefile. This uses ogr2ogr to extract OSM data from postgres to create the GeoJson file for ODK Collect.

**Comment by ivangayton** [comment]
That link goes to a 404. Can you re-check it?

**Comment by robsavoye** [comment]
Use my new make_data_extract.py program instead. That creates the geojson file for ODK Collect from either a postgres database, or Overpass. All the work is done in classes, so would be easy to integrate into the backend directly.

**Comment by robsavoye** [comment]
This is working, and now in main. Data extracts are also uploaded to Central from the FMTM backend. It currently uses a local postgres with the OSM data in it. A future task will be using the Underpass raw database instead.
