### ISSUE TITLE
Design Issue on Manage Organizations

### ISSUE THREAD

**Issue by susmina94** [hotosm/fmtm#701]
![image](https://github.com/hotosm/fmtm/assets/108750444/cc5f3986-7bc9-42d6-a5c9-328de4000ec1)

If the user adds a long description of the organization, the card is distorted

**Comment by manjitapandey** [comment]
I think the logo should be shifted to the right so that the descrepancy will be eliminated whether the description is long or short.

**Comment by manjitapandey** [comment]
the organisation creation from create project shows different pop up but the organisation creation from manage organisation tab opens up differently. it would be better if organisation creation UI is same from both ways.

https://vimeo.com/857480758/031f6acc55

**Comment by varun2948** [comment]
@manjitapandey @susmina94 two of you are saying two different things on this. :smile:

**Comment by susmina94** [comment]
@manjitapandey We've designed the add organization pop-up in a different way
considering that if the same UI is displayed, the user will have access to projects via the two same pages.

To reduce the duplication, we've redesigned it as that of now.
So that should be okay.

I still need to check out the design of the card and close if it's done.
