### ISSUE TITLE
Calculate number of submissions in a task 

### ISSUE THREAD

**Issue by susmina94** [hotosm/fmtm#704]
As a project manager, I would want to know how many forms have been submitted within a task.
So that I can keep track of user's activity

**Comment by nrjadkry** [comment]
@susmina94 Project info page gives that exactly. 
Do you have any idea, where else can we show this?

**Comment by susmina94** [comment]
![image](https://github.com/hotosm/fmtm/assets/108750444/e49e0649-2073-4e7c-9278-0824dd60b54a)

Here we have, 0 out of 5 tasks

5 indicates the number of features within that task
But it can always exceed the number of features.

For eg: Only 5 buildings have been remotely mapped.
But I find there 7 buildings in the field within that area.

I will not use the select tasks for the extra 2 buildings but collect the GPS location of those buildings as we won't have it mapped already.

In this case , the form submission count and the count on project info could differ.

So I would suggest in displaying total form submissions as well as total features surveyed.
So that we can find the discrepancy and maybe digitize the incomplete features while uploading on JOSM.

**Comment by susmina94** [comment]
![image](https://github.com/hotosm/fmtm/assets/108750444/9b7711a9-a9dd-4cb2-8185-b205493c052b)

Otherwise something like this will show up.
It going beyond 100%

@nrjadkry

**Comment by susmina94** [comment]
@robsavoye @ivangayton

**Comment by susmina94** [comment]
I can view the submissions count as well.
Thanks
