### ISSUE TITLE
Project cancel option to terminate the project creation process.

### ISSUE THREAD

**Issue by susmina94** [hotosm/fmtm#707]
As of now, I don't have any option to cancel the draft projects while creating one.
The only alternative is refreshing the tab to entirely create a new project

I navigate to another page and come back the project draft is still there.

**Comment by varun2948** [comment]
@susmina94 this had been fixed please have a look

**Comment by varun2948** [comment]
@nrjadkry yo cancel garna milni wala banauna parni bho

**Comment by susmina94** [comment]
This could be incorporated with the new UI changes that we've considered.
Since we have an entire new UI design, I'll remove it as bug instead have it as a feature.
