### ISSUE TITLE
Splitting algorithm doesn't function.

### ISSUE THREAD

**Issue by susmina94** [hotosm/fmtm#708]
![image](https://github.com/hotosm/fmtm/assets/108750444/f9c247a4-66f5-4e6c-964b-b62c12a955ae)

**Comment by nrjadkry** [comment]
@susmina94 
data extract process is now running. So, this should work as before.

**Comment by manjitapandey** [comment]
![image](https://github.com/hotosm/fmtm/assets/97273021/032055bf-5208-46b2-837a-6a29ae17a3d4)
 
the issue is still not fixed, it generate task but leaves buildings and generate zones randomly and also out of the POI.

**Comment by varun2948** [comment]
@nrjadkry

**Comment by susmina94** [comment]
It think it's working fine as of now. 
Yes the splits need to be even more smooth and precise.
But this issue is related to when the algorithm wasn't functioning at all.
So removing it for now.
