### ISSUE TITLE
Incompatible options for form category

### ISSUE THREAD

**Issue by susmina94** [hotosm/fmtm#710]
I selected the wastedisposal option and this showed me no files or directory error.

Let's only display the options that the platform is compatible with atm.
We shall add in these options later on instead of having this error onboard.

![image](https://github.com/hotosm/fmtm/assets/108750444/8f09d5e5-272d-4d22-9b0c-36d37bec7ef3)

![image](https://github.com/hotosm/fmtm/assets/108750444/fc0758d6-ac48-44f1-ade2-796443ead9ac)

**Comment by varun2948** [comment]
@nrjadkry what to do about this ?

**Comment by susmina94** [comment]
![image](https://github.com/hotosm/fmtm/assets/108750444/8aba389d-17f1-45a9-8235-9f199339adad)

![image](https://github.com/hotosm/fmtm/assets/108750444/b6be2bf8-7f2d-4ab8-a0a5-acba834e7716)

The user experience doesn't seem right.
Is the QR code not generating because of the form category selection is "Waste Disposal"?

No clue of what went wrong here.
If I am choosing other category for eg" health", its working fine.
