### ISSUE TITLE
UI change suggestions

### ISSUE THREAD

**Issue by susmina94** [hotosm/fmtm#711]
![image](https://github.com/hotosm/fmtm/assets/108750444/0399da75-16e2-4dc0-81d4-d3f31442c925)

Until the qr codes are generated in the background 
We can use the percentage section of contributors to display the status of the qr code generation.

And once the status is completed, better show the contributors count.

**Comment by varun2948** [comment]
it might not be a best idea to fetch api on this page constantly as discussed with @nrjadkry

**Comment by susmina94** [comment]
I got that.
Might need to think of something else.
