### ISSUE TITLE
I can't download the submissions in bulk in a single file for CSV format.

### ISSUE THREAD

**Issue by susmina94** [hotosm/fmtm#722]
**Is your feature request related to a problem? Please describe.**
I wanted to download the submissions of the entire project. But the Download submission in csv button exports csv of individual tasks zipped in different folders. This is very cumbersome to check the entire data in every folder. 

**Describe the solution you'd like**
I would expect the submissions in a single csv format instead.
We could have the download option for submissions of each task in the task list view instead.

**Comment by nrjadkry** [comment]
@robsavoye does osm_fieldwork support exporting all the data of a project in a single csv?

**Comment by robsavoye** [comment]
We only want to download the JSON version through ODATA, as it's more complete than the CSV version. The CSV file drops some location data when used with FMTM, which the JSON format doesn't. Also since the backend is now using OdkCentral.getAllSubmissions(), that downloads the JSON submissions for all the tasks of a project, and converts that to OSM XML at the same time.

**Comment by robsavoye** [comment]
The problem with CVS is that in some occasions, it looses data when using OSM data extracts. The JSON format doesn't. CSV is fine for anyone wanting to load it into a spreadsheet, but neither format can be displayed in JOSM or QGIS without some kind of conversion to convert the coordinates to something usable. I do agree, FMTM should allow to download both, but for conversion to OSM, we want to only use the JSON format. All the conversion is going on behind the scenes, so nobody will notice.

**Comment by susmina94** [comment]
@robsavoye @ivangayton has mentioned he has found a way to download the bulk submissions in csv format as well.
But there are issues if the form has repeat groups in it.

I will create a fresh issue for the repeat groups as discussed in the meeting.
