### ISSUE TITLE
Count of tasks is wrong

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#728]
This project only has 7 tasks, so not sure where the wild totals come from.

![Screenshot from 2023-08-16 09-28-36](https://github.com/hotosm/fmtm/assets/71342768/7b17cc8c-3050-4181-a09f-4d4df7d7b5fd)

**Comment by nrjadkry** [comment]
This is buildings count not the task count, @varun2948 please update that.

**Comment by robsavoye** [comment]
Ah... :-) We might want to change the label then so it says that instead of tasks.

**Comment by manjitapandey** [comment]
but the feature count shows buildings one more than the actual number of features.

![image](https://github.com/hotosm/fmtm/assets/97273021/91a25b0c-6f85-4aa0-8c75-d640e7e1bbe6)

in this image, the numbers of buildings are 2 but it shows 3 in count

**Comment by manjitapandey** [comment]
@nrjadkry daii

**Comment by manjitapandey** [comment]
![image](https://github.com/hotosm/fmtm/assets/97273021/78a18732-b6ea-41c0-acf5-a4d91222247c)

**Comment by nrjadkry** [comment]
@manjitapandey If you look closely, there is a point along with 4 polygons.
Some of the osm data do not have polygons and instead have point. So, points are extracted for some of them.
