### ISSUE TITLE
uploaded custom footprint disappears in define task tab

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#734]
**Describe the bug**
when we upload custom data, the uploaded footprint is shown in data extract tab but disappers in define task tab.

**To Reproduce**

1. Go to "create project"
2.upload custom data extract footprint
3. Scroll down to 'define task'

**Expected behavior**
to show custom footprint in define task tab also till the task is generated.

**Screenshots**
[New Recording - 8_18_2023, 1_04_38 PM.webm](https://github.com/hotosm/fmtm/assets/97273021/092fe7cb-d1dc-43cb-adc9-a55ad3df6cf4)

**Comment by nrjadkry** [comment]
@varun2948

**Comment by manjitapandey** [comment]
solved
