### ISSUE TITLE
Migrate from old user accounts --> OSM users in DB

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#744]
**Is your feature request related to a problem? Please describe.**
- We had an legacy login that has now been removed, see #735.
- If an OSM user attempts to login, but the username is already taken by a legacy user, they can't.
- Users can no longer log in to legacy accounts.

**Describe the solution you'd like**

### 1
- Update legacy usernames to append `_legacy` or something similar. I think @nrjadkry may have already worked on this.

### 2
- Projects / tasks associated with these users should be migrated to OSM user accounts.
- To do this for each corresponding user we would have to coordinate with them to make OSM accounts.
- Perhaps a good middle ground is to migrate the tasks / projects to a service account for OSM (FMTM account?).

Open to suggestions for how to best solve this.

**Comment by nrjadkry** [comment]
I have added  _legacy to all the users created using manual login process.
