### ISSUE TITLE
Project name should accept other characters too.

### ISSUE THREAD

**Issue by susmina94** [hotosm/fmtm#754]
**Describe the bug**
I cannot add special characters while naming a project

**To Reproduce**
![image](https://github.com/hotosm/fmtm/assets/108750444/93caae93-452a-496b-86fe-19e7ba5b364f)

**Expected behavior**
It should support numeric as well as other special characters.

**Comment by nrjadkry** [comment]
@varun2948

**Comment by nrjadkry** [comment]
@varun2948

**Comment by nrjadkry** [comment]
Project_buildings  If the project name is like this with underscore, it conflicts when setting up the forms. As the form id are extracted from this project name, we had to not allow users to have underscore.
Form is are normally extracted like this. Project_buildings_task_id  , then form id is the 3rd object splitted by _

**Comment by susmina94** [comment]
That means, the form id is separated by underscore so we can't allow underscores.
Then maybe not allow just the underscore then? Because I think it's normal for the users to add - or , or colon in the project name.
It might not just be text.

**Comment by susmina94** [comment]
![image](https://github.com/hotosm/fmtm/assets/108750444/d014e781-9f7b-4dca-b4fb-84a3f13600e3)

The validation message show "-" instead of "_" underscores
