### ISSUE TITLE
The statistics do not match with the field activities.

### ISSUE THREAD

**Issue by susmina94** [hotosm/fmtm#755]
**Describe the bug**
The statistics do not match with the field activities on the side bar of Project Info.

**To Reproduce**

1. I submitted 2 different forms selecting the same feature within a task
2. But the stats on project info shows 3 out of 18 features have been completed.
3. Which is wrong

**Expected behavior**
I think if we could possibly not allow selecting a single feature twice for submission, that would help keep data accurate.
Validation would be much easier.
Or maybe have a check in the backend if the OSM ID has already been registered during a submission.

**Screenshots**
![image](https://github.com/hotosm/fmtm/assets/108750444/3746bd6b-5a5c-424e-86f3-1855da93d5bc)

**Comment by robsavoye** [comment]
You're using ODK Collect on an iPhone ?

**Comment by susmina94** [comment]
Haha nope! I missed removing the default texts down there.
