### ISSUE TITLE
MB tiles generation

### ISSUE THREAD

**Issue by manjitapandey** [hotosm/fmtm#759]
**Describe the bug**
.mb tiles are not generated when we click on generate after selecting tile sources

**To Reproduce**

1. Go to 'Generate MB tiles'
2. Click on 'esri'
3. click on generate tiles

**Expected behavior**
A smooth generation of mb tiles 

**Screenshots**
![image](https://github.com/hotosm/fmtm/assets/97273021/6528156b-6916-4d79-a456-e8c3f01918c1)

**Comment by spwoodcock** [comment]
Thanks @manjitapandey - can you confirm this is on development and not production?

I think this may be solved by #758 I just merged.
Please test and let me know 👍

**Comment by nrjadkry** [comment]
@spwoodcock I don't think it worked.

**Comment by spwoodcock** [comment]
Hopefully it's fixed now.

The tile download creation path was wrong:
`PermissionError: [Errno 13] Permission denied: 'app/tiles/bcb04913-51bb-486e-9dd2-36586cce131d'`

And putting the tile_path_instance creation in the try block resulted in:
`UnboundLocalError: local variable 'tile_path_instance' referenced before assignment`
when we get an error (i.e. not setting the task to failed in the DB)

It's now deploying to development.

**Comment by nrjadkry** [comment]
@spwoodcock It is still the permission issue
`PermissionError: [Errno 13] Permission denied: '/opt/app/tiles/0dc55687-33cb-458f-8d1c-e6c5606abc15`

**Comment by spwoodcock** [comment]
For some reason the tiles dir is still owned by root after the volume mount:
![image](https://github.com/hotosm/fmtm/assets/78538841/5893c0c9-e226-4e3f-a103-665e83fb0763)

I will update the dockerfile to pre-create the dir to solve this.
(I assume this works for images, because app/images already exists in the repo).

**Comment by spwoodcock** [comment]
Sorry about the hassle!

The issue should now be fixed 🎉 

![image](https://github.com/hotosm/fmtm/assets/78538841/006cb53e-f9f7-4242-821a-f1cf9f864a14)

I moved the files up one dir into /opt/tiles.
