### ISSUE TITLE
Can't use splitting algorithm

### ISSUE THREAD

**Issue by susmina94** [hotosm/fmtm#761]
**Describe the bug**
I can't regenerate tasks by updating the average building count by splitting algorithm.

**To Reproduce**

1. I chose the default 5 count size for avg building count
2. Click "Generate Tasks"
3. The tasks were generated
4. I receive an error message after I click Next
5. The error message is "Choose the number 9 or above" 
6. I change the building count to 10 and click generate tasks
7. I can't see the splits on map
8. But I can go Next.

**Expected behavior**
1. The default value should be set to 9 if that's the min value that platform accepts.
2. The updated splits need to be viewed on the map as well.

**Screenshots**
![image](https://github.com/hotosm/fmtm/assets/108750444/5c69a12b-f8a7-4625-8ea0-f34b7d8c3975)

**Comment by manjitapandey** [comment]
Now it splits the task at any number of buildings provided. it would be better if there is threshold value for splitting.

**Comment by susmina94** [comment]
I'd suggest that the threshold could be any number except negative and 0.
That's ultimately the user's role in adding numbers.
