### ISSUE TITLE
Invalid task option for the workflow

### ISSUE THREAD

**Issue by susmina94** [hotosm/fmtm#775]
**Is your feature request related to a problem? Please describe.**
As you can see in the image below, there are total 8 tasks
But only 6 features 
If there would be a feature where the managers could cross mark the tasks with 0 features so that mappers wouldn't have to take care of that, that would save time and help the managers assign people based on that stats.

**Describe the solution you'd like**
Maybe have "Invalid task" in the workflow for such tasks.
Also showing feature count for each task on the map.

This could also be automatic and not a manual task.
The script automatically makes a decision "Invalid Task" after noticing 0 feature count.
![Uploading Screenshot_2023-08-25-13-25-42-498_org.odk.collect.android.jpg…]()

This would also help avoid the issue that appears in ODK Mobile app, due to 0 feature count. Attached below is the image 

**Additional context**
![image](https://github.com/hotosm/fmtm/assets/108750444/9583f123-5c05-4e37-be72-962028d99ba3)

**Comment by varun2948** [comment]
@nrjadkry is this fixed or anything we can do on this ?
