### ISSUE TITLE
Provide Submissions as OSM XML, GeoJSON, and/or CSV for Validation with JOSM, QGIS, or a spreadsheet

### ISSUE THREAD

**Issue by ivangayton** [hotosm/fmtm#8]
When a task (which, we remember, corresponds to a form in ODK) is complete and marked "Ready for validation," the validator is most likely to wish to view the results in:

- JOSM, therefore OSM XML
- QGIS or some other GIS software, therefore GeoJSON
- A spreadsheet, therefore CSV (or possibly .xlsx)

The most likely path here is:

- Validator (who is logged in as a validator on a PC, not as a mapper on a phone) clicks on a square marked "Ready for validation."
- They see a popup offering them a few options:
  - Open in JOSM (which mirrors the process that the HOT Tasking manager uses; it launches JOSM with the OSM XML open)
  - Download OSM XML
  - Download GeoJSON
  - Download CSV
  - Download all assets (probably a ZIP file with the OSM XML, GeoJSON, and CSV bundled together)

Once the validator has the data in their hands, we have no further responsibilities toward them other than to allow them to mark the relevant square "Complete and validated". It might also make sense to add a status for "and also uploaded to OSM".

**Comment by robsavoye** [comment]
The odkconvert program can generate OSM XML and GeoJson from either a CSV file downloaded from Central, or the raw XML instance file copied off your device. This will need to be incorporated into the backend and front-end. For now it's terminal based, but all the work is done in classes, so easy to use from other programs.

**Comment by robsavoye** [comment]
This currently work in main, all submissions are downloaded by the backend, and converted to OSM XML and GeoJson. This currently lacks frontend support, but in the backed this now works.
