### ISSUE TITLE
Filtering of data extracts is disabled

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#817]
Cleaning the data extract is commented out, and if uncommented, only works with a custom XLSForm. Data cleaning needs to  work for all XLSForms. Without data cleaning, ODK Collect will never launch, which basically means FMTM doesn't work at all.

**Comment by nrjadkry** [comment]
Data cleaning of osm-extracts for existing forms in done in osm-fieldwork. For uploading the custom data, we need to clean them in the fmtm.

**Comment by robsavoye** [comment]
Have you tried the data extracts in Collect ? It was not doing any filtering all when I tested it.

**Comment by robsavoye** [comment]
If you go to the dev server, create a small project, and download the data extract, you can see many tags not in the choices sheet of the XLSForm. This prevents ODK Collect from launching.

**Comment by robsavoye** [comment]
This is starting to look like a possible bug in the ODK Collect beta package, but does seem to work (so far) in the official play store package.
