### ISSUE TITLE
Display of file generation is blank

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#818]
The window that used to show the files being generated is blank. Looking at the log, they do get created, and when done, the project exists and works normally.

![Screenshot from 2023-09-09 08-08-18](https://github.com/hotosm/fmtm/assets/71342768/50d892b5-811a-4e69-8764-05a9bf2837b2)

**Comment by robsavoye** [comment]
This works correctly on the dev server, but not when I am running a local docker container. I'm not sure what the difference is,

**Comment by susmina94** [comment]
@nrjadkry dai Could you please verify if the issue persists ?
If not, I guess we can close this one too.
