### ISSUE TITLE
Explore adding AllContributors Bot

### ISSUE THREAD

**Issue by petya-kangalova** [hotosm/fmtm#83]
**[HOTOSM is taking part in Outreachy internship May to August 2023](https://www.outreachy.org/outreachy-may-2023-internship-cohort/communities/humanitarian-openstreetmap-team/). I will be adding suggested tasks for interns as issues and tagging with "Outreachy".**

Is your feature request related to a problem? Please describe.
This is not related to specific FMTM feature. It will be useful to explore adding the All Contributor Bot to this repository: https://allcontributors.org/docs/en/bot/installation

Describe the solution you'd like
We would like to reward contributors to this repository, and not just those contributing with code.

Describe alternatives you've considered
I haven't see many alternatives to this- recently came across it! I would love to hear if others in the community have used it, installed in their repo? It looks like you need to tag people manually.

**Comment by Ndacyayisenga-droid** [comment]
@petya-kangalova @spwoodcock can I work on this issue?

**Comment by spwoodcock** [comment]
Hi @Ndacyayisenga-droid thanks for your willingness to contribute! Feel free to start and send a PR 😄

**Comment by Ndacyayisenga-droid** [comment]
@spwoodcock can you take a look at mp PR please https://github.com/hotosm/fmtm/pull/132

**Comment by AugustHottie** [comment]
Hi @petya-kangalova @spwoodcock it doesn't look like there's an Issue regarding rewarding open source contributors. Can I create the issue?

**Comment by petya-kangalova** [comment]
@Ndacyayisenga-droid  thanks for the PR- will take a look by end of the week. @robsavoye 

@AugustHottie  good spot- created one here https://github.com/hotosm/fmtm/issues/135

**Comment by spwoodcock** [comment]
Merged #132 as I thought it was a simple config, but the allcontributions bot didn't seem to run.
This needs to be re-vistited at some point.

**Comment by spwoodcock** [comment]
This was my lack of understanding of how the bot works. It seems it's functioning: it will add a PR with a contributor if you comment in the correct format, see https://github.com/hotosm/fmtm/issues/135#issuecomment-1459496380

@all-contributors
please add @ivangayton for projectManagement code review ideas.
please add @robsavoye for maintenance mentoring code review ideas.
please add @krtonga for code docs tool ideas.
please add @biomassives for code.
please add @Mudi-business for code.
please add @petya-kangalova for docs eventOrganizing ideas.
please add @spwoodcock for code review infra ideas.

Sorry if I missed anyone!

**Comment by spwoodcock** [comment]
Issue solved, thanks again @Ndacyayisenga-droid

@all-contributors
please add @Ndacyayisenga-droid for docs.
please add @mohammadareeb95 for docs.
please add @AugustHottie for docs.

**Comment by spwoodcock** [comment]
@all-contributors
please add @Mudi-business for code.
please add @petya-kangalova for docs eventOrganizing ideas.
please add @spwoodcock for code review infra ideas.

**Comment by spwoodcock** [comment]
This is painful...

https://github.com/all-contributors
please add @petya-kangalova for docs eventOrganizing ideas.
please add @spwoodcock for code review infra ideas.

**Comment by spwoodcock** [comment]
This is painful...

@all-contributors
please add @petya-kangalova for docs eventOrganizing ideas.
please add @spwoodcock for code review infra ideas.

**Comment by spwoodcock** [comment]
@petya-kangalova the all-contributions tool is quite cool, but I can foresee potential issues with the PR based approach.

If a PR isn't merged for a contribution before another one is made, then it causes a merge conflict that has to be resolved manually.

Alway, it's good for now! Maybe the bot will be refined in the future!

@all-contributors
please add @mohammadareeb95 for docs.
please add @AugustHottie for docs.

**Comment by spwoodcock** [comment]
@all-contributors
please add @mohammadareeb95 for doc.
please add @AugustHottie for doc.

**Comment by spwoodcock** [comment]
@all-contributors
please add @mohammadareeb95 for doc.

**Comment by spwoodcock** [comment]
@all-contributors
please add @Ndacyayisenga-droid for docs.

**Comment by spwoodcock** [comment]
@all-contributors
please add @mohammadareeb95 for docs.

**Comment by petya-kangalova** [comment]
Thanks @spwoodcock  and @Ndacyayisenga-droid  for working on this and sorry to hear it took a while and that is maybe not working properly and a bit bodge. The idea was to explore if this is a good solution.
