### ISSUE TITLE
OSM login fails on iOS

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#834]
**Describe the bug**

Field testing with users on various devices.

Login creates an error on iOS.

**Comment by spwoodcock** [comment]
I have an iOS device for testing now.
Once set up I can debug this.

**Comment by varun2948** [comment]
@spwoodcock sure sam

**Comment by spwoodcock** [comment]
The reason for this is that `window.open` does not work properly on Safari iOS within callbacks:
https://stackoverflow.com/questions/76613689/window-open-functionality-is-not-working-in-safari-browser

Possible solution: **Open the window right before you start the async call but not inside the call**

```js
const popup = window.open('', 'OSM Auth', settings);
fetch(`${import.meta.env.VITE_API_URL}/auth/osm_login/`)
  .then((resp) => resp.json())
  .then((resp) => {
    win.location = resp.login_url;
  });
};
```

Need to test.
