### ISSUE TITLE
Multi-arch image builds

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#837]
- Currently we use buildx to build docker images.
- There are probably flags to build multi-arch, possibly using different GitHub runners if needed.
- Running FMTM should support a large number of architectures, including Apple silicon and raspberry pi.

**Comment by fatumahomar** [comment]
Hi @spwoodcock is this issue included in the contribution of Outreachy

**Comment by spwoodcock** [comment]
Hi @fatumahomar, thanks for the interest in contributing!

This task is coding related, so unfortunately doesn't qualify for Outreachy.
Please see https://github.com/hotosm/fmtm/issues/863 and info from Petya.

However, if you know a good solution to this issue and still wish to contribute, feel free to do so.
It would be greatly appreciated and set you in good stead with the team 🙏
