### ISSUE TITLE
Improve Github Project Documentation

### ISSUE THREAD

**Issue by petya-kangalova** [hotosm/fmtm#84]
[HOTOSM is taking part in Outreachy internship May to August 2023](https://www.outreachy.org/outreachy-may-2023-internship-cohort/communities/humanitarian-openstreetmap-team/). I will be adding suggested tasks for interns as issues and tagging with "Outreachy".

Suggested list of tasks for Outreachy contributors [can seperate  into individual issues]
- [ ] 1.1. Research best practices on Github product  documentation, including system and process documentation (ex. contributor guidelines, testing, translation, API documentation, etc.) For example, see example of API endpoint with description that is missing from other endpoints  https://github.com/hotosm/fmtm/blob/ccf3719663c11db599163b38e0f7889e277f529a/src/backend/projects/project_crud.py#L216 We would also need support with creating test cases for API endpoints.
- [ ] 1.2. Based on the research, suggest improvements to existing documentation starting with the [Field Mapping Tasking Manager Github repo](https://github.com/hotosm/fmtm).
- [ ] 1.3. Create new documentation where missing for [Field Mapping Tasking Manager Github repo](https://github.com/hotosm/fmtm).
- [ ] 1.4. Suggest a consistent documentation structure that can be replicated for other pinned repositories in the HOTOSM Github

**Comment by harshithakolipaka** [comment]
hey, @petya-kangalova, I found the feedback form missing in the current documentation.So, I would like to add a user feedback form on the documentation and the product itself. This can help identify areas for improvement and can lead to a better overall user experience.

**Comment by Ndacyayisenga-droid** [comment]
Hi @spwoodcock @petya-kangalova can I work on this issue?

**Comment by spwoodcock** [comment]
Hi @harshithakolipaka, great idea! I'm not sure exactly where the feedback form should submit to, but @petya-kangalova might have a better idea.

@Ndacyayisenga-droid you can most definitely help by contributing anything you see missing from the docs!

**Comment by Ndacyayisenga-droid** [comment]
@spwoodcock @petya-kangalova am going to do 1.1, 1.2 and 1.4 on google docs then share the link
I would probably send a PR for 1.3

Does that sound like a good Idea?

**Comment by Ndacyayisenga-droid** [comment]
> [HOTOSM is taking part in Outreachy internship May to August 2023](https://www.outreachy.org/outreachy-may-2023-internship-cohort/communities/humanitarian-openstreetmap-team/). I will be adding suggested tasks for interns as issues and tagging with "Outreachy".
> 
> Suggested list of tasks for Outreachy contributors [can seperate into individual issues]
> 
> * [ ]  1.1. Research best practices on Github product  documentation, including system and process documentation (ex. contributor guidelines, testing, translation, API documentation, etc.) For example, see example of API endpoint with description that is missing from other endpoints  https://github.com/hotosm/fmtm/blob/ccf3719663c11db599163b38e0f7889e277f529a/src/backend/projects/project_crud.py#L216
>    We would also need support with creating test cases for API endpoints.
> * [ ]  1.2. Based on the research, suggest improvements to existing documentation starting with the [Field Mapping Tasking Manager Github repo](https://github.com/hotosm/fmtm).
> * [ ]  1.3. Create new documentation where missing for [Field Mapping Tasking Manager Github repo](https://github.com/hotosm/fmtm).
> * [ ]  1.4. Suggest a consistent documentation structure that can be replicated for other pinned repositories in the HOTOSM Github

As it looks like @petya-kangalova has the scope of this issue, I have tried to make a quick generic write up of how we can improve the github project documentation. Most of my pointers are generic since am not familiar with fmtm repository. Just incase any of my pointers is out of proportion, the google document can be edited by whoever has the link so feel free to edit or add a comment where need be. So we can start editing the project documentation following the guildlines.
checkout my pointers here https://docs.google.com/document/d/1f00K75wnQNh-MHBcsrjTIrlNPnNVtvZqnpF53wwdwxs/edit

cc @spwoodcock @petya-kangalova

**Comment by NikkyXO** [comment]
@petya-kangalova  i will like to know if  this issue still available,
 i noticed that the other issue with outreachy tag is taken by same person

**Comment by Balofire** [comment]
@petya-kangalova  After doing task 1.1, here are my suggested improvements for 1.2 in a google doc. Please review and tell me if I'm moving in the right direction before I attempt 1.3 https://docs.google.com/document/d/1EIGJ108dM06dP26GnZfEEZhWDgXAmcxN0bTwp8F1XQs/edit?usp=sharing

**Comment by Balofire** [comment]
Hi @petya-kangalova These are my suggested documentation structures for  1.4. Please check out my suggestions and make  any needed corrections and comments 
https://docs.google.com/document/d/1PsMYAKVqjJlkm9tPIYUSptDG0SRSKSTrE_X1zk1SOYc/edit?usp=sharing

**Comment by Gutopro** [comment]
Hi @petya-kangalova can you please review my task 1.1
 https://docs.google.com/document/d/1roxJfRjjZZ510P1RwB2mv-RvdYwcIaK_V__t8WAywOA/edit?usp=sharing
