### ISSUE TITLE
Tidy up / refactor codebase

### ISSUE THREAD

**Issue by susmina94** [hotosm/fmtm#846]

**Comment by spwoodcock** [comment]
Thanks @susmina94!

Do we need the create-issue-branch bot btw?
I think it's actually counter productive:
- An issue is made, then a branch immediately.
- The issue branch gets out of sync with development branch.
- Create rebasing / merging difficulties for the issue branch.

I think it would be easiest to create branches locally, as needed (i.e. when someone starts working on the issue).

**Comment by spwoodcock** [comment]
This isn't actually done, but it's an ongoing process. 

Lots of work to fix all the linting errors and make pre-commit happy.

We can keep this closed though and address this in small bit as we complete other issues.
