### ISSUE TITLE
Map functionality to geolocate and get direction to features

### ISSUE THREAD

**Issue by susmina94** [hotosm/fmtm#853]
The GPS location is available at the moment but I also want to get direction to the specific features inside a task.

I should be able to select a feature and Get Direction to that feature from my location.

**Comment by varun2948** [comment]
@spwoodcock we might need a direction api like maybe graphhopper or valhalla something like this to get the direction from current location to tasks

**Comment by spwoodcock** [comment]
Needs more research, but I heard about this at FOSS4G: https://github.com/GIScience/openrouteservice-py

Otherwise Valhalla is the way, self hosted or the demo server.

**Comment by varun2948** [comment]
we mostly use graphopper in naxa for routes.

**Comment by spwoodcock** [comment]
Anything written in Java that include the words 'memory efficient' in the first sentence I am skeptical of 😂

I would need to assess it's footprint to add to the FMTM stack, but I feel it might be too heavy.

Running a global instance for many projects (I assume you do this at NAXA), would solve the problem though.

I have never used either, but do you know why Graphopper was chosen over Valhalla? (to help me assess)

**Comment by susmina94** [comment]
Duplicate issue with #915
