### ISSUE TITLE
Implement ODK workflow for accessing two geojson files in a form for Janakpur Pilot Project

### ISSUE THREAD

**Issue by susmina94** [hotosm/fmtm#856]

**Comment by robsavoye** [comment]
Two data extracts ? Then you'd need two XForms, one for each extract.

**Comment by robsavoye** [comment]
In that case we'd need to add a YAML file to osm-fieldwork to extract both highways and buildings, and the merge the highway and buildings XLSForms together. Personally, I think it's work better to have two XForms and data extracts than overload one. Why does this have to be in the same XForm ?

**Comment by nrjadkry** [comment]
We wont need to merge those forms. We are uploading a custom form for this Janakpur project as well as the data extracts.

But, for the future, we might need to explore merging two forms too.

**Comment by nrjadkry** [comment]
We wont need to merge those forms. We are uploading a custom form for this Janakpur project as well as the data extracts.

But, for the future, we might need to explore merging two forms too.

**Comment by robsavoye** [comment]
I think merging the 2 XForms and data extracts together is a bad idea. I assume this will be supported by uploading a custom XForm and data extract ? I'm curious about the mapper data flow to map both of these in the same XForm.

**Comment by nrjadkry** [comment]
Acutally, mapper wants to map a buildings. But to know which exact buildings, selecting a road is also provided here. So, two data extracts have two be uploaded.
@susmina94 knows more why such a form is designed.

**Comment by robsavoye** [comment]
I'd just use a basemap of the highways, and then focus on mapping buildings, rather than making a larger and messier data extract.

**Comment by robsavoye** [comment]
The basemapper program can make an imagery from Google Hybrid, which has highway names.

**Comment by spwoodcock** [comment]
I agree we should avoid overcomplicating things.

Would downloading imagery with highway tags solve the issue here @susmina94 ?

I'm not sure I entirely understand the requirements.
Does the user want to map both buildings and highways at the same time?
Or is highway information only required to improve the accuracy of building tags?

**Comment by spwoodcock** [comment]
Closing.
Will eventually be replaced by https://github.com/hotosm/fmtm/issues/509

**Comment by susmina94** [comment]
@spwoodcock  @robsavoye 
We actually want the users to select a road segment while mapping a building so that we can have the road segment id in the same set of submissions.

The road data extract is not just for the visual inspection for the users but they would have to instead either select the road so that we can map the road id or manually enter the road id by viewing the basemap with road ids.

I still have to see what Rob actually meant with the feature collection dataset approach.
You may look into what we're trying to work around in this project.
https://fmtm.naxa.com.np/project_details/MTAwMTEwMTE=

**Comment by robsavoye** [comment]
The XLSForm can access both highways and the buildings. For highways you only can set a single node, but with the OSM ID, any tags added can be attributed to the highway. I you used the highway data extract for Janakpur, it'd work the same. In this case the custom XLSForm would need a custom YAML for make_data_extract to have most be in the same extract. I can easily manually make you an extract with both, or you can using osm-fieldwork, or even ogr2ogr.
