### ISSUE TITLE
Switch from npm -> pnpm

### ISSUE THREAD

**Issue by JoltCode** [hotosm/fmtm#882]
**Is your feature request related to a problem? Please describe.**
Not particularly, just would improve DX.

**Describe the solution you'd like**
Switch from NPM to PNPM, and then tweak the associated docker scripts.

**Describe alternatives you've considered**
I suppose Yarn and Bun are alternatives, but on the whole PNPM is more performant than Yarn, and from experience is more reliable too. And for Bun, I don't believe it's quite prod ready yet, although I'd say it's 100% something we can look forward to using in the future. 

**Additional context**
N/A

**Comment by spwoodcock** [comment]
Hey @JoltCode, thanks for the suggestion!

I completely agree - PNPM is a great tool, and much more performant.
We used NPM as it was just set up like that from the start.

Would be highly appreciated if you wanted to make a PR for this 🚀

**Comment by JoltCode** [comment]
> Hey @JoltCode, thanks for the suggestion!
> 
> I completely agree - PNPM is a great tool, and much more performant. We used NPM as it was just set up like that from the start.
> 
> Would be highly appreciated if you wanted to make a PR for this 🚀

Ah awesome! Of course 😄

**Comment by varun2948** [comment]
Hey @JoltCode we would love a testing PR for Bun aswell after your pnpm implementation.
