### ISSUE TITLE
Switch from webpack -> vite

### ISSUE THREAD

**Issue by JoltCode** [hotosm/fmtm#883]
**Is your feature request related to a problem? Please describe.**
Switch from using webpack to vite, it's so so much quicker, less config required and has quite a few other benefits.

**Describe the solution you'd like**
Switch from webpack -> vite.

**Describe alternatives you've considered**
Not really any I can think of at the moment.

**Additional context**
N/A

**Comment by spwoodcock** [comment]
Again, completely agree here 😉

I use Vite for many other projects. 

What do you think though @varun2948 ?

**Comment by varun2948** [comment]
Yeah its totally doable now and we should switch onto Vite as it is whole lot faster and maybe we could also think about having Bun ? but Bun is at its early phase we just could try it to switch build time and runtime faster but yeah definitely a go to for Vite for now .
