### ISSUE TITLE
Use fmtm-splitter for task splitting

### ISSUE THREAD

**Issue by robsavoye** [hotosm/fmtm#885]
The task splitting code has been pulled out of the FMTM backend, and turned into a standalone module where it can be shared between multiple projects. Since it literally the same code with a wrapper, it should relatively easy to integrate. That new module is here: https://github.com/hotosm/fmtm-splitter

**Comment by nrjadkry** [comment]
@spwoodcock Please go ahead, you can work on this.
I have not yet worked on this, I was actually planning on working this week in this issue.
