### ISSUE TITLE
Allow downloading data extract from FMTM and support upload of the same data extract back to FMTM

### ISSUE THREAD

**Issue by susmina94** [hotosm/fmtm#889]
Problem:
I cannot view the data extract generated by FMTM. I would like to see if there is any standard format for the data extract so that I can custom upload or edit the extract provided by FMTM.

Solution:
1. I want to download the data extract generated by FMTM.
2.  I want to update and modify the data and re-upload the data extract back to FMTM before generating QR code

**Comment by spwoodcock** [comment]
I hope not much work has been done implementing these endpoints 🙏 
I think it's mostly been superseded by https://github.com/hotosm/fmtm/issues/934

So to address your questions:

### 1) Download the data extract generated by FMTM

- Once https://github.com/hotosm/fmtm/issues/934 is implemented then this should be trivial.
- The data extract will be available in flatgeobuf format on the raw-data-api S3 bucket (with a URL that won't change.
- We can add a link to the S3 URL in our database, which is returned when the user requests an extract download.
- A user clicks download and the frontend just redirects to the returned URL to download.
- Note: we could possibly also specify to download only a  **subset** of the data (i.e. with a bbox specified).

### 2 Update and modify the data and re-upload

- If the data extract isn't exactly how we would like, we can go back and tweak the params and regenerate  the extract.
- If it's still not good enough using the filters on raw-data-api, then we can give the user the option to upload a custom data extract (we need this functionality anyway for some users).
  - We should have a small endpoint that accepts this new extract, then uploads it to **our** S3 bucket, also inserting the URL into the database.
  - The uploaded data extract would have to be parsed and ideally converted to flatgeobuf for efficient access.
