### ISSUE TITLE
Project creation workflow: stepper overlaps map component

### ISSUE THREAD

**Issue by khushishikhu** [hotosm/fmtm#893]
**Describe the bug**
I think the bar of create new project is blocking the sight as well as it creates a bad UI for the user, being the things not aligned. It needs to be fixed.

**To Reproduce**

1. Go to 'CREATE NEW PROJECT'
2. Click on UPLOAD AREA
3. Scroll down to the bottom

**Expected behavior**
The bar sholus be fix a bit UP, so that it won't create a messy view of the page

**Screenshots**
![Screenshot 2023-10-11 113145](https://github.com/hotosm/fmtm/assets/65439761/823b8ad1-82ce-4647-8de1-d24332744584)

**Smartphone (please complete the following information):**

- Device: Laptop
- OS: Windows 11
- Browser: Chrome

**Comment by spwoodcock** [comment]
Hi @khushishikhu!

Thanks for the issue, any feedback is greatly appreciated 🎉 

We are in the process of a redesign for the project creation workflow & I agree this should be incorporated.

I have assigned our senior frontend dev to this task, or, of course, we would welcome any contribution 😄

**Comment by susmina94** [comment]
@khushishikhu 
We have switched to the new UI for the project creation workflow. This mitigates the issue you raised.
Thank you!
