### ISSUE TITLE
Choose from a library of ODK XLSForms for OSM field mapping

### ISSUE THREAD

**Issue by ivangayton** [hotosm/fmtm#9]
When a Campaign Manager creates a project, they basically select three parameters:

1. An Area of Interest
2. A task-splitting strategy
3. A data model/questionnaire

Here we're focusing on 3, the data model/questionnaire, which is implemented as an [ODK XLSForm](https://xlsform.org/). We should provide a library of basic, common, high-quality XLSForms that cover many OSM field mapping scenarios. 

Those forms should incorporate standard, valid, community-accepted tags, as well as the data models being developed by HOT's Data Team.

They should be accompanied by YAML files allowing @robsavoye 's odkconvert (specifically the [osmdump module](https://github.com/hotosm/odkconvert/blob/main/ODKDump.py) to convert the resulting submissions smoothly into OSM XML.

When a Campaign Manager creates a project, they should be able to choose from this library of forms. 

Some (well, many) Campaign Managers will need to modify forms to collect data specific to their project. That's the subject of another issue, #10!

**Comment by robsavoye** [comment]
Right now the XLSForm library is accessible from the backend, but needs frontend support so project managers can choose one. There is also support for uploading a custom XLSForm.

**Comment by robsavoye** [comment]
This now works.
