### ISSUE TITLE
Implement Statistics For Github Repo 

### ISSUE THREAD

**Issue by varun2948** [hotosm/fmtm#901]
I saw these fancy repository stats on this repo https://github.com/steven-tey/novel should we integrate this? 
![image](https://github.com/hotosm/fmtm/assets/37866666/b8711322-bcb6-4b45-bbf4-55a748302e72)

**Comment by spwoodcock** [comment]
Looks pretty neat! I like the idea, why not 👍 

Seems to be generated with a tool called [Axiom](https://axiom.co/).

**Comment by spwoodcock** [comment]
I just got permissions to add this - now in the readme:

![image](https://github.com/hotosm/fmtm/assets/78538841/c2a50adf-5d66-4d71-99d8-8de3096381a4)
