### ISSUE TITLE
Error handling for AOI in projected coordinate system

### ISSUE THREAD

**Issue by susmina94** [hotosm/fmtm#911]
**Describe the bug**
I uploaded an AOI which was in projected coordinate system. There was no issue with upload however, when I tried to split the task, I could not generate tasks and the api showed pending status only.

**To Reproduce**

1. Go to Create Project
2. Click on Upload AOI
3. Use any splitting algorithm
4. The tasks aren't generated
5. The api status is pending

**Expected behavior**
If the projected coordinate system isn't supported in the platform, it should've shown error while the user uploaded the file stating "The platform only supports file in geographic coordinate system" 

**Screenshots**

![Image](https://github.com/hotosm/fmtm/assets/108750444/c9703abb-c6e0-4e6d-8fa5-8329009f040b)

**Comment by spwoodcock** [comment]
Good catch, thanks!

Geojson can have a optional `crs` field to specify the coordinate system, so even better would be if we could parse this and covert the geom to web mercator. 

Failing that, we give a not supported error, as you say 👍

**Comment by robsavoye** [comment]
We want to only use an SRID of 4326, which is very common. Or we can add code to transform it to 4326.

**Comment by spwoodcock** [comment]
EPSG 4326 as default for sure 👍

We should also support 3857, as this is a web map after all.

Support for anything other than that via the geojson crs key is just a bonus.

So two things we should consider to facilitate this:

- Allow loading in file formats other the geojson (often with better crs support inbuilt, e.g. geopackage).
- If a crs other than 4326 is identified, attempt to convert. Otherwise give an error.

**Comment by robsavoye** [comment]
I think for a project AOI, at least when I make one with QGIS, JOSM, or ogr2ogr, it usually defaults to 4326. It would be easy to transform the crs, but I'm curious what software produced an AOI with a different crs ?

**Comment by spwoodcock** [comment]
You are right that GeoJSON default is generally EPSG 4326.

This is not necessarily an optimisation we need if we are only looking at GeoJSON.
But GeoJSON is a format for the web, and many GIS users work with other formats, such as geopackage, shapefiles, you name it.

Although we don't support e.g. geopackage upload now, we need to be able to handle different CRS if the user uploads one other than EPSG 4326. At the bare minimum, we need error handling to tell them their CRS is not supported.
