### ISSUE TITLE
The project details page crashing down

### ISSUE THREAD

**Issue by susmina94** [hotosm/fmtm#914]
**Describe the bug**
I click on a freshly created project to view the detailed page.
But it throws an error as shown in the screenshot below.

**To Reproduce**

1. Go to Projects
2. Click on a Project
3. Shows error

**Expected behavior**
If there are any error with input file, it should throw an error with a proper validation messages so that the user understands what is the problem and how they can resolve it the next time.

**Screenshots**

![Image](https://github.com/hotosm/fmtm/assets/108750444/81ce9080-7abe-42a5-b1e2-d4e37e87dd2e)

**Comment by spwoodcock** [comment]
Unrelated to this issue, but just a comment on the screenshot (cc @varun2948 )

The error page looks great, but on second thought I'm not sure how appropriate the image is. 

A use case for FMTM is to support earthquake response & the image shows people running from an earthquake 😅

**Comment by varun2948** [comment]
hmm, yeah @spwoodcock came to think of it we should change the illustration to something else maybe a laptop not working kind of thing will change that to something non related with these kind of humanitarian illustration.
