### ISSUE TITLE
OSM login button is hidden on mobile

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#929]
**Describe the bug**

- This has been an issue for a while now, I just forgot to mention it.
- The 'OSM Sign In' button get hidden when the breakpoint is activated (on mobile).
- The menu items are in the sidebar, but the OSM Login is not.

**To Reproduce**

Testing using Firefox.

Large screen (desktop):
![image](https://github.com/hotosm/fmtm/assets/78538841/920cdffd-ca25-46e9-8293-ac1831700443)

Small screen (mobile):
![image](https://github.com/hotosm/fmtm/assets/78538841/19e5950f-c736-417a-b4bc-10b1f2495d6e)

**Expected behavior**

We should have an OSM Login button in the sidebar at least.
Or don't hide the login button - it is probably best being sticky.

**Additional context**

While we are there, it might be nice to replace the 'OSM Sign In' text with an icon.
Something like the material icons account icon.

**Comment by susmina94** [comment]
**Issue 1**
Replace OSM Sign In text with Sign In only in the desktop view as well.
The text appear in two lines and doesn't look nice.

![image](https://github.com/hotosm/fmtm/assets/108750444/2bcae143-7325-4911-9959-728ce4a228a2)

**Issue 2**
The tasking manager displayes the user photo along with the user name after signing in.
Can we also display the same for the users.

![image](https://github.com/hotosm/fmtm/assets/108750444/c2c82ca0-f811-48d1-9d4c-994d23866587)

**Comment by spwoodcock** [comment]
There is a `url` field returned from the `/auth/me` endpoint that we should persist to the user store.

Then it's easy to set that as `src` for a profile picture.
