### ISSUE TITLE
Open mbtiles modal on mobile should close the bottom menu

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#936]
**Describe the bug**

When opening the mbtiles modal on mobile, it is hidden by the bottom menu.

**To Reproduce**

Go to https://fmtm.naxa.com.np/project_details/MTEwMDA=
on mobile.

**Expected behavior**

The bottom menu will close when the mbtiles modal is opened.

**Screenshots**

![image](https://github.com/hotosm/fmtm/assets/78538841/95f87005-c9ee-4e5b-abfe-ffc45fd151fa)

**Smartphone (please complete the following information):**

- Device: Pixel 6A
- Browser: Chromium based

**Comment by susmina94** [comment]
**Issue**

The outline of the boxes strikethrough the texts Format and Source
 
![image](https://github.com/hotosm/fmtm/assets/108750444/8fc0a1af-7737-4bda-aaef-6f6a5828ad7e)
