### ISSUE TITLE
Redesign pagination & project summaries endpoint

### ISSUE THREAD

**Issue by susmina94** [hotosm/fmtm#944]
## Original Issue

**Describe the bug**
Since we have the infinite scroll in projects page, the text displaying the range doesn't make sense. 

**To Reproduce**

1. Go to 'Explore Projects"

**Expected behavior**
Add the text "Total Projects : N" , where N = project count instead of showing n of n projects

**Screenshots**

![Image](https://github.com/hotosm/fmtm/assets/108750444/0d486c27-8c5b-463f-b45c-c70a5f7a79d8)

## New Issue

- Pagination of the backend is partially addressed by: #225
- This is an approach where we can only limit the number of results, not actual pagination (?page=1, ?page=2, etc).
- We need true pagination as we grow, or the API call to fetch projects will either return too much data, or we will be unable to return data past ?limit=100.

## Proposed Solution

**Backend**

- Add pagination to the `summaries` endpoint so we can include ?page=1 syntax.
- Only return approx 13-20 project - assess what is best.
- Move the results list under the key `results`.
- Create one other top level key in the JSON called `pagination`, where pagination details are included (number of pages, total number of projects, etc).

**Frontend**

- Add `Showing x of x projects` to the home page, based of `pagination.total` key.
- Access the project summary content via the `results` key instead.

**Comment by spwoodcock** [comment]
This needs a redesign using pagination on the backend as well as frontend.

Tasking manager displays 13 results out of the total:

![image](https://github.com/hotosm/fmtm/assets/78538841/3075a8a5-f008-412d-b276-575fdf924610)

In the API they implement pagination like this:

![image](https://github.com/hotosm/fmtm/assets/78538841/add9a35f-d863-41e6-9788-54cbb5ae47d8)

So they get the total project count from the database as part of the summaries, then only return 13 summaries in the `results` key.

What do you think of having something similar?

**Comment by spwoodcock** [comment]
I reassigned the task - feel free to divide as needed.
