### ISSUE TITLE
User should be able to go to individual project details page even if the AOI is exact duplicate

### ISSUE THREAD

**Issue by susmina94** [hotosm/fmtm#945]
**Is your feature request related to a problem? Please describe.**
I zoomed in to a project location where it showed me there are two projects. But no matter how much I zoomed in to the location, I could not view the marker point to get into the project details page. I don't even know which project id is that specific project. I can't go to its details page.

This is probably due to the centroids of the AOI fall at the same exact place.

**Describe the solution you'd like**
However, if such case appears, we shall allow the user to click on that circle of the centroid location where the markers of two individual projects will branch out into two places. Now the users can click on those markers to get inside of that project.

**Describe alternatives you've considered**
Another alternative would be to filter out projects in the Table of Contents based on the location user zooms in to. 

For eg: If I zoom into Nepal, the projects list in the Table of Content also gets filtered by location/zoom extent. That way I will have the two project cards on the TOC and will be more clear and identifiable.

![Image](https://github.com/hotosm/fmtm/assets/108750444/1d056031-87fc-482b-b1bd-04882342f3b3)

**Comment by spwoodcock** [comment]
This is built into ol-ext clustering (which we use), where when you click a clustered point, and you have a suitable zoom level, the cluster expands to multiple points.

Example of pop-out clusters:
https://viglino.github.io/ol-ext/examples/animation/map.animatedcluster.html

I implemented this myself a while ago using ol-ext (wrapped in Vue):
https://gitlab.com/mastweb/frontend/-/blob/main/src/components/MapOpenLayers.vue?ref_type=heads
In action: https://app.mastweb.ch

**Comment by varun2948** [comment]
yeah i also have implemented in my other projects and for this we just need enhancement on the current cluster so yes we will integrate this later on.
