### ISSUE TITLE
Research mocking odkcentral requests for API testing

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#95]
- We want to run tests with pytest against the FastAPI backend.
- To do this we will need to mock the odkcentral API.
- Research request mocking tools for Python.

**Comment by robsavoye** [comment]
it's entirely possible to do this using netcat.

**Comment by spwoodcock** [comment]
We could use https://pypi.org/project/requests-mock/ to solve this.

**Comment by robsavoye** [comment]
The ODK Central API documentation also uses mock requests, so that should work fine.
