### ISSUE TITLE
Map ODK Central Credentials with organization name

### ISSUE THREAD

**Issue by susmina94** [hotosm/fmtm#966]
@ivangayton suggested mapping the ODK central credentials with the selection of organization name

For eg:

If I select NAXA as organization name, the fields (ODK URL and Username) are prefilled with the ODK credentials used by NAXA as an organization.

The users will of course have the option to use any other ODK credentials, but that would be very less often.
This is a good UX for people setting up a project on a regular basis.

However, we need to assure that ODK password are not prefilled, and are not misused.

 

![Image](https://github.com/hotosm/fmtm/assets/108750444/c1c4e640-31c5-420d-adfa-5156b733d08f)

@spwoodcock Any thoughts on this?

**Comment by spwoodcock** [comment]
IMO the password could probably be prefilled too, just not displayed.

My thoughts for better UX:

## Organisation Creation

- When entering the details for an organisation, we could also add optional fields:

```
Default ODK Central Details:
URL: xxx
Username: xxx
Password: xxx

Note: these credentials should be for a service account user in your ODK Central instance.
```

- The credentials can be stored in the organisation table (entirely optional).

# Project Creation

- On project creation, the organisation is selected.
- There is an additional checkbox to "Use default credentials."
  - Checking this will disable the manual entry.
  - The credentials are extracted from the organisation database table on submit and saved in the project table (never being sent to the frontend).
- If the user does not check the box, then they can enter their details manually.

This way we can have prefilled default ODK credentials for an organisation service account, but also allow users to enter any credentials they want.

What do you think?

**Comment by varun2948** [comment]
dependent with the user role we have to finish user roles and permission first inorder to work on this.

**Comment by spwoodcock** [comment]
Yeah ideally, but adding user roles is a big task.

We could add a solution to this by inputting (default) odk credentials on organisation creation and storing them in the db.

In the long term we would want DBOdkCreds and a link table to organisations and projects.

In the short term we could just save as three extra fields on the organisation table.

### Prefilling Credentials

Once the creds are in the db, we could simply have a checkbox on project creation to 'use default ODK details'.

The project_create endpoint would have to accept this flag and get the creds from the db if set.

This is the best I can think of, as prefilling the values on the frontend (even if obsfucated), would require returning the password in a response that tech savvy users could inspect.
