### ISSUE TITLE
Restrict jumping to the project setup workflow until the mandatory fields are completed by the user

### ISSUE THREAD

**Issue by susmina94** [hotosm/fmtm#979]
**Describe the bug**
CURRENT WORKFLOW

I can jump into Step 5 from Step 1 without completing the mandatory fields for steps in between.

_For eg: I can just click on Selecting splitting algorithm without uploading an AOI and click on Submit.
This would for sure result an error._ 

But I think this is a very bad workflow.
We know that the steps are incomplete without the mandatory fields so we should restrict the users to shift from one step to another in general.

 **Expected behavior**

1. Let's not allow the users to jump directly into different steps via the nav bar of the project setup workflow.

2. Let's ensure we have validations to the mandatory fields, before the user moves on to the next step.

Validations should include:

1. Verify if the ODK central credentials exist or is already available or is registered
2. Validate if the uploaded AOI follows the convention or not (If its on the correct coordinate system)

**Comment by spwoodcock** [comment]
Easy way to solve this is to only enable the final submit if all stages are validated.

We should track the completion of each stage on the stepper.

Would also be great if we had different icons in the stepper, depending on if the stage was validated:

- All stages have no status/icon by default.
- When you click to 'next' the next stage, or click on the stepper, the stage should be validated.
- If validation fails, show a red cross, if validation passes, a green tick.
